Repository GenericMappingTools/gmt, pull requests merged in 2020-09, with the labels that each got.

#4137 Skip record if gmt_create_array() returns error and thus prevent crash.
  src/sample1d.c
Labels: backport 6.1

#4145 Improve the checklist
  .github/ISSUE_TEMPLATE/release_checklist.md
Labels: backport 6.1

#4144 Add 6.1.1 to changes.rst
  doc/rst/source/changes.rst
Labels: backport 6.1

#4148 Missing definition for Add_-h in two modules
  doc/rst/source/grd2cpt.rst
  doc/rst/source/makecpt.rst
Labels: backport 6.1

#4150 Remove an unused var and let build-release scp the files
  admin/build-release.sh
  src/postscriptlight.c
Labels: backport 6.1, bug

#4152 Ensure files on remote server has correct permissions
  admin/build-release.sh
Labels: backport 6.1, bug

#4124 Region for 3s tiles fails if not multiple of 3s
  ci/azure-pipelines-mac.yml
  test/grdimage/rounding.ps
  test/grdimage/rounding.sh
Labels: bug

#4244 Improve the Developer documentation for how to debug
  doc/rst/source/debug.rst
Labels: documentation

#4262 Allow histograms with custom bar width and optional shift
  doc/rst/source/histogram.rst
  doc/rst/source/histogram_common.rst_
  doc/rst/source/pshistogram.rst
  src/pshistogram.c
  test/pshistogram/altwidth.ps
  test/pshistogram/altwidth.sh
Labels: new feature
