Repository GenericMappingTools/gmt, pull requests merged in 2020-08, with the labels that each got.

#3799 Special attention when tile grids are passed to grdimage
  src/gmt_map.c
  src/grdimage.c
Labels: backport 6.1, bug

#3804 Must close file before delete it
  src/gmt_remote.c
Labels: backport 6.1

#3805 Fix reST styling issue in #1605
  doc/rst/_static/style.css
Labels: backport 6.1

#3809 Handle GMT_IS_DUPLICATE flag to GMT_Open_VirtualFile
  src/gmt_api.c
Labels: backport 6.1

#3811 Adding API test for plotting a global matrix/grid for different central meridians
  src/testapi_matrix_360.c
  test/api/apimat_360.sh
Labels: backport 6.1, bug

#3815 Modern keys fix
  src/gmt_api.c
  src/grdcontour.c
  src/grdimage.c
  src/psbasemap.c
  src/pscontour.c
  src/pshistogram.c
  src/psmask.c
  src/psrose.c
  src/pssolar.c
  src/psternary.c
Labels: backport 6.1, bug

#3817 Use the currrent default export type, not GMT_DOUBLE
  src/gmt_api.c
Labels: backport 6.1, bug

#3818 Migrate the "Code Check" CI job from Azure Pipelines to GitHub Actions
  .azure-pipelines.yml
  .github/workflows/code-validator.yml
Labels: backport 6.1

#3813 Try to get matrix as grid to work with changing central meridian
  src/gmt_api.c
  src/gmt_grdio.c
  src/grdimage.c
  src/testapi_matrix_360.c
  test/api/apimat_360.ps
  test/grdimage/globalgrid.ps
Labels: backport 6.1

#3823 Add reference to float matrix test for grdimage
  src/testapi_matrix_360_ref.c
  test/api/apimat_360_ref.sh
Labels: backport 6.1, bug

#3825 gmt.conf.rst: make table of FORMAT_GEO_OUT terms
  doc/rst/source/gmt.conf.rst
Labels: backport 6.1

#3826 Wrap testapi programs for testing
  test/gmtest.in
Labels: backport 6.1

#3831 Need to use masks to assign complex_mode variables
  src/gmt_api.c
Labels: backport 6.1, bug

#3833 DEmote warning -E+r to DEBUG
  src/gmt_dcw.c
Labels: backport 6.1

#3835 Keep track of allocation modes for grids and x/y vectors separately
  src/gmt_api.c
  src/gmt_grdio.c
  src/gmt_hidden.h
Labels: backport 6.1, bug

#3829 Handle matrix via reference for grid input
  src/gmt_api.c
  src/gmt_grdio.c
  src/gmt_prototypes.h
  src/grdimage.c
  src/testapi_matrix_360.c
  test/api/apimat_360_ref.ps
Labels: backport 6.1, bug

#3839 Only turn on clobber background if it can work
  src/gmt_prototypes.h
  src/gmt_support.c
  src/pscoast.c
Labels: backport 6.1, bug

#3851 Ignore classic history when modern session starts
  src/gmt_init.c
Labels: backport 6.1, bug

#3849 Add special check for non-rotated global grids
  src/gmt_map.c
  src/gmt_project.h
  src/psxy.c
  src/psxyz.c
Labels: backport 6.1, bug

#3855 fix a typo
  doc/rst/source/cookbook/map-projections.rst
Labels: backport 6.1

#3848 Reading/writing a matrix from/to a grid file
  doc/rst/source/api.rst
  src/gmt_api.c
  src/gmt_nc.c
  src/testapi_grid2matrix.c
  src/testapi_imageshading.c
  src/testapi_matrix_360.c
  src/testapi_matrix_plot.c
  test/api/apimat2grd.ps
  test/api/apimat2grd.sh
  test/api/apimat_360.ps
  test/api/apimat_360_ref.ps
Labels: backport 6.1, bug

#3858 Needed to expact variable columns to deal with missing z
  doc/rst/source/splitxyz.rst
  src/splitxyz.c
Labels: backport 6.1, bug

#3860 Let -R handle east < west for common cases
  src/gmt_map.c
Labels: backport 6.1, bug

#3863 Clarify that pen colors can be specified in RGB hexadecimal
  doc/rst/source/cookbook/features.rst
Labels: backport 6.1, bug

#3865 Move non-official GMT install instructions to wiki
  INSTALL.md
Labels: backport 6.1

#3868 Wrap testapi_grid2matrix so that Windows test can find it
  test/gmtest.in
Labels: backport 6.1

#3871 UPdate -JP description in the Cookbook
  doc/rst/source/cookbook/coordinate-transformations.rst
Labels: backport 6.1, bug

#3873 Ensure a duplicated grid via gmt_new_grid has the minimum padding required by module
  src/geodesy/gpsgridder.c
  src/gmt_grdio.c
  src/gmt_prototypes.h
  src/grdclip.c
  src/grdfft.c
  src/grdgradient.c
  src/grdhisteq.c
  src/grdvolume.c
  src/greenspline.c
  src/potential/gravfft.c
  src/potential/grdflexure.c
Labels: backport 6.1, bug

#3874 Make sure grdivew can access default CPT when a cpt is needed
  src/grdview.c
Labels: backport 6.1, bug

#3881 colorbar doc improvement
  doc/rst/source/colorbar_common.rst_
Labels: documentation

#3883 Add basic legend at top of man page
  doc/rst/source/legend_common.rst_
  doc/scripts/GMT_seislegend.ps
  doc/scripts/GMT_seislegend.sh
Labels: documentation

#3884 Forgot to update the gmt.rst file
  doc/rst/source/gmt.rst
Labels: documentation

#3885 Set z_hinge=0 if +h is used but hinge isn't given
  src/gmt_support.c
Labels: backport 6.1

#3878 Simplify CI steps on Linux and macOS
  .azure-pipelines.yml
  ci/azure-pipelines-linux.yml
  ci/azure-pipelines-mac.yml
  ci/config-gmt-unix.sh
  ci/install-dependencies-linux.sh
  ci/install-dependencies-macos.sh
Labels: backport 6.1

#3888 Add a CI job to compile GMT without optional dependencies
  .azure-pipelines.yml
  ci/install-dependencies-linux.sh
Labels: backport 6.1

#3896 Improve the plot man page for symbols
  doc/rst/source/explain_symbols.rst_
  doc/scripts/GMT_base_symbols1.ps
  doc/scripts/GMT_base_symbols1.sh
  doc/scripts/GMT_base_symbols2.ps
  doc/scripts/GMT_base_symbols2.sh
  doc/scripts/GMT_base_symbols3.ps
  doc/scripts/GMT_base_symbols3.sh
  doc/scripts/GMT_base_symbols4.ps
  doc/scripts/GMT_base_symbols4.sh
  doc/scripts/GMT_base_symbols5.ps
  doc/scripts/GMT_base_symbols5.sh
  doc/scripts/GMT_base_symbols6.ps
  doc/scripts/GMT_base_symbols6.sh
  doc/scripts/GMT_base_symbols7.ps
  doc/scripts/GMT_base_symbols7.sh
  doc/scripts/GMT_base_symbols8.ps
  doc/scripts/GMT_base_symbols8.sh
  doc/scripts/GMT_base_symbols9.ps
  doc/scripts/GMT_base_symbols9.sh
Labels: backport 6.1, documentation

#3899 Vector doc improvement
  doc/rst/source/explain_vectors.rst_
  doc/scripts/GMT_vector.ps
  doc/scripts/GMT_vector.sh
Labels: backport 6.1, documentation

#3903 Let -U and PostScript comments use modern names if modern mode
  src/gmt_plot.c
Labels: backport 6.1, bug

#3906 Fix growth.sh to be more like the one in master so it does not crash
  test/potential/growth.ps
  test/potential/growth.sh
Labels: bug

#3909 Clarify the difference between -Se and -SE
  doc/rst/source/explain_symbols.rst_
Labels: backport 6.1, documentation

#3911 Accept deprecated CN.## numbers and look up corresponding codes
  src/gmt_dcw.c
Labels: backport 6.1

#3913 Add the missing anchor to psconvert -Z option
  doc/rst/source/psconvert.rst
Labels: backport 6.1

#3917 Clarify -R for oblique -JO Mercator
  doc/rst/source/explain_-J_full.rst_
Labels: backport 6.1, documentation

#3931 Test select.sh passes now
  test/ogr/select.ps
  test/ogr/select.sh
Labels: backport 6.1, bug

#3932 antwrap.sh now only failed because gridlines are now behind the plot
  test/psxy/antwrap.ps
  test/psxy/antwrap.sh
Labels: backport 6.1, bug

#3934 The oneincshift.sh used to fail but now passes
  test/grdimage/oneincshift.ps
  test/grdimage/oneincshift.sh
Labels: backport 6.1, bug

#3937 Update buggy script with comments to clarify the problem
  test/psxy/nearpole.sh
Labels: backport 6.1, bug

#3941 Better recognition of pi-number
  src/gmt_io.c
Labels: backport 6.1, bug

#3944 doc: Fix the wrong description of -Bafg/afg
  doc/rst/source/cookbook/options.rst
Labels: backport 6.1

#3951 Improve parsing of -G in mapproject
  src/gmt_support.c
  src/mapproject.c
Labels: backport 6.1, bug

#3952 Ensure -qi only increments data record counters for data records
  src/gmt_io.c
  test/gmtconvert/asciirowselect.sh
Labels: backport 6.1, bug

#3956 Strengthen the -s option and fix a few issues
  doc/rst/source/explain_-s.rst_
  doc/rst/source/explain_-s_full.rst_
  src/gmt_init.c
  src/gmt_io.c
  src/gmt_io.h
  src/gmt_prototypes.h
  src/gmt_synopsis.h
  src/grd2xyz.c
  src/grdtrack.c
  test/gmtconvert/outputselect.sh
Labels: backport 6.1, bug

#3958 Update CI caches
  ci/azure-pipelines-linux.yml
  ci/azure-pipelines-mac.yml
  ci/azure-pipelines-windows.yml
Labels: backport 6.1

#3961 Fix the description of -Rcode syntax
  doc/rst/source/cookbook/options.rst
  doc/rst/source/explain_-R_full.rst_
Labels: backport 6.1

#3964 Ignore a check if the axis is not annotated
  src/gmt_plot.c
Labels: backport 6.1, bug

#3967 Specify x-axis in sript
  doc/scripts/GMT_-B_time1.sh
  doc/scripts/GMT_-B_time2.sh
  doc/scripts/GMT_-B_time3.sh
  doc/scripts/GMT_-B_time4.sh
  doc/scripts/GMT_-B_time5.sh
  doc/scripts/GMT_-B_time6.sh
  doc/scripts/GMT_-B_time7.sh
Labels: backport 6.1, bug

#3969 Update ex22.bat
  doc/examples/ex22/ex22.bat
Labels: backport 6.1

#3971 Remove .grd suffix from remote earth_mask file
  doc/scripts/GMT_earthmask.sh
Labels: backport 6.1

#3974 Update PS files due to changes of remote grids
  doc/examples/anim04/anim04.ps
  doc/examples/ex33/ex33.ps
  doc/examples/ex34/ex34.ps
  test/grdcontour/contours.ps
  test/grdcontour/varpens.ps
  test/grdview/texture.ps
  test/modern/imagepluscpt.ps
Labels: backport 6.1

#3977 Simplify anim07
  doc/examples/anim07/anim07.sh
Labels: backport 6.1, bug

#3984 Just ensure grdinfo of remote grid reports it as geographic
  src/gmt_remote.c
  src/grdinfo.c
Labels: backport 6.1, bug

#3985 Let z-axis annotations be normal to axis as an option
  doc/rst/source/explain_-B_full.rst_
  src/gmt_init.c
  src/gmt_plot.c
Labels: backport 6.1, bug

#3989 Revise 14 PS files after 3-D z-labels go horizontal by default
  doc/examples/ex04/ex04.ps
  doc/examples/ex04/ex04c.ps
  doc/examples/ex05/ex05.ps
  doc/examples/ex08/ex08.ps
  doc/examples/ex10/ex10.ps
  test/grdgradient/illum_classic.ps
  test/grdgradient/illum_lambert.ps
  test/grdgradient/illum_manip.ps
  test/grdview/cuerpo.ps
  test/grdview/icelandbox.ps
  test/greenspline/gspline_3.ps
  test/greenspline/gspline_4.ps
  test/psxyz/3dbars.ps
  test/segy/segy_03.ps
Labels: backport 6.1, bug

#3994 Fix a typo in coast documentation
  doc/rst/source/coast_common.rst_
Labels: backport 6.1

#3996 Be more careful cleaning up after failed curl
  src/gmt_remote.c
Labels: backport 6.1, bug

#3998 Simplify Curl operations
  src/gmt_remote.c
Labels: backport 6.1, bug

#4001 Improve the auto -B settings under modern mode
  src/gmt_init.c
Labels: backport 6.1, bug

#4004 Update GMT caches for testings
  ci/azure-pipelines-linux.yml
  ci/azure-pipelines-mac.yml
  ci/azure-pipelines-windows.yml
Labels: backport 6.1

#4037 Fix strtok_r
  cmake/modules/ConfigureChecks.cmake
Labels: backport 6.1

#4025 Make sure -Q is parsed before -T is parsed if logarithmic
  src/gmt_prototypes.h
  src/gmt_support.c
  src/makecpt.c
Labels: backport 6.1, bug

#4056 No proj
  src/gmt_init.c
  src/gmt_plot.c
Labels: backport 6.1

#4058 Add check to stop subplot if dimensions are not set
  src/subplot.c
Labels: backport 6.1, bug

#4060 Fixed strsignal(3) usage
  src/gmt_common_sighandler.c
  src/gmt_config.h.in
Labels: backport 6.1

#4062 Need to include string.h for strsignal
  src/gmt_common_sighandler.c
Labels: backport 6.1

#4064 Fix two resource leaks reported by cppcheck
  src/gmt_init.c
  src/gmt_remote.c
Labels: backport 6.1

#4067 Fix an error message
  src/gmt_init.c
Labels: backport 6.1

#4070 Fix bug in parsing grdview -T
  src/grdview.c
Labels: backport 6.1, bug

#4072 INitialize lon-lat nodes for non-GMT projections
  src/gmt_map.c
Labels: backport 6.1, bug

#4074 Check if any points were given in gmt_geo_to_xy_line
  src/gmt_map.c
Labels: backport 6.1, bug

#4079 Fix a few comments in C codes
  src/gmt_init.c
Labels: backport 6.1

#4076 Fix an unintvar compilation error
  src/gmt_api.c
Labels: backport 6.1

#4083 Better message when the Registry registerd ghostscript is not found.
  src/psconvert.c
Labels: backport 6.1

#4084 Use current pen with color is changing
  src/psxy.c
Labels: backport 6.1, bug

#4089 Subplot auto-height needs -R -J
  src/subplot.c
Labels: backport 6.1, bug

#4090 Fix shebang of a few bash scripts
  doc/examples/anim09/anim09.sh
  doc/scripts/GMT_fatline.sh
  doc/scripts/GMT_seamount_flux.sh
  doc/scripts/GMT_seamount_map.sh
  doc/scripts/GMT_seamount_types.sh
  test/pslegend/autolegend.sh
  test/pssac/pssac_stdin.sh
Labels: backport 6.1

#4087 ALso fix plot3d for variable pen and color via header and CPT
  src/psxy.c
  src/psxyz.c
  test/psxy/varpen.ps
  test/psxy/varpen.sh
  test/psxyz/varpen.ps
  test/psxyz/varpen.sh
Labels: backport 6.1, bug

#4088 pssac: Use Cartesian projection by default unless -S is used
  src/gmt_init.c
Labels: backport 6.1

#4095 Not let API call exit
  src/gmt_api.c
Labels: backport 6.1, bug

#4097 Disallow ---version and --show-datadir on module calls
  src/gmt_init.c
Labels: backport 6.1, bug

#4100 Fix the example in subplot manpage
  doc/rst/source/subplot.rst
Labels: backport 6.1

#4099 Fix description of various -F option
  doc/rst/source/basemap_common.rst_
  doc/rst/source/coast_common.rst_
  doc/rst/source/colorbar_common.rst_
  doc/rst/source/image_common.rst_
  doc/rst/source/legend_common.rst_
Labels: backport 6.1

#4104 Remove exit from gmtlogo
  src/gmtlogo.c
Labels: backport 6.1, bug

#4105 Eliminate exit calls in grdfft and psconvert
  src/grdfft.c
  src/psconvert.c
Labels: backport 6.1, bug

#4110 docs: Enable switching different versions
  .github/ISSUE_TEMPLATE/release_checklist.md
  doc/rst/_static/version_switch.js
  doc/rst/_templates/layout.html
  doc/rst/conf.py.in
Labels: backport 6.1

#4113 Add snake lines as new test
  test/psxy/snakes.ps
  test/psxy/snakes.sh
Labels: backport 6.1, bug

#4112 Allow composite character with two characters from different font/charsets
  doc/rst/source/text_notes.rst_
  src/postscriptlight.c
  test/pstext/composite.ps
  test/pstext/composite.sh
Labels: backport 6.1, bug

#4115 Adding test of relative Mercator region prior to change
  test/psbasemap/merc_origin.ps
  test/psbasemap/merc_origin.sh
Labels: backport 6.1, bug

#4118 Forgot -Du sets Standard+ in gmtest
  test/pstext/composite.sh
Labels: backport 6.1, bug

#4120 Fix issues in Mercator projection
  doc/rst/source/mapproject.rst
  src/gmt_init.c
  src/gmt_proj.c
  src/mapproject.c
  test/psbasemap/merc_origin.ps
Labels: backport 6.1, bug

#4125 Fix an unused-var warning
  src/gmt_init.c
Labels: backport 6.1

#4126 Update GMT_fatline.ps
  doc/scripts/GMT_fatline.ps
Labels: backport 6.1

#4130 Make sure intensity subset matches tiled region if given
  src/grdimage.c
Labels: backport 6.1, bug

#4134 Fix minor issue in sample1d doc file
  doc/rst/source/sample1d.rst
Labels: backport 6.1, bug, documentation
