Repository GenericMappingTools/gmt, pull requests merged in 2020-07, with the labels that each got.

#3616 Try to refresh only when remote files are requested
  src/gmt_init.c
  src/gmt_internals.h
  src/gmt_prototypes.h
  src/gmt_remote.c
  src/gmtget.c
Labels: bug

#3625 Fix bugs in duplication of CPTs
  doc/rst/source/grd2cpt.rst
  doc/rst/source/makecpt.rst
  src/gmt_constants.h
  src/gmt_io.c
  src/gmt_support.c
  src/grd2cpt.c
  src/psscale.c
  test/grdfft/cylundulation.sh
  test/spotter/spotter_03.sh
Labels: backport-to-stable

#3631 Only make tiny adjustments to dx and dy if both need it
  src/gmt_grdio.c
Labels: backport 6.1

#3630 Remote update frequency
  doc/fig/EarthByte_logo_small.png
  doc/fig/igpp.png
  doc/fig/nasa-logo-web-rgb.png
  doc/rst/source/datasets.rst
  doc/rst/source/datasets/earth-age.rst_
  doc/rst/source/datasets/earth-daynight.rst_
  doc/rst/source/datasets/earth-masks.rst_
  doc/rst/source/datasets/earth-relief.rst
  doc/rst/source/datasets/earth-relief.rst_
  doc/rst/source/datasets/remote-data.rst
  doc/rst/source/gmt.conf.rst
  src/gmt_defaults.h
  src/gmt_init.c
  src/gmt_keywords.txt
  src/gmt_prototypes.h
  src/gmt_remote.c
  src/gmtget.c
Labels: backport 6.1

#3647 Update example 47 and test regress_2
  doc/examples/ex47/ex47.ps
  doc/examples/ex47/ex47.sh
  test/gmtregress/regress_2.ps
Labels: backport 6.1

#3650 Confidence band on regression missed multipler of sigma
  doc/examples/ex43/ex43.ps
  doc/examples/ex43/ex43.sh
  doc/rst/source/gallery/ex43.rst
  src/gmtregress.c
  test/gmtregress/draper.ps
Labels: backport 6.1

#3652 Calculate confidence band for -Er and -Eo
  src/gmtregress.c
Labels: backport 6.1

#3659 Failure of Cartesian clipping in plot -L+d
  doc/examples/ex43/ex43.ps
  src/gmt_map.c
  src/gmt_prototypes.h
  src/psxy.c
Labels: backport 6.1

#3661 Fix regression on Windows when trying to find if name is a SUBDATASET.
  src/gmt_gdalread.c
Labels: backport 6.1

#3669 Wait with deleting font files until gmt end has completed
  doc/examples/ex31/ex31.bat
  doc/examples/ex31/ex31.sh
Labels: backport 6.1

#3672 Let psxy -T without -B skip the check for -R -J
  doc/rst/source/plot.rst
  doc/rst/source/plot_common.rst_
  src/gmt_init.c
  src/psxy.c
Labels: backport 6.1

#3675 if -R -J is given with -T then we must deal with them
  src/gmt_init.c
  src/psxy.c
Labels: backport 6.1

#3679 Turn outline on when a tile pen is found
  src/grdview.c
Labels: backport 6.1

#3681 More grdview fixes
  src/grdview.c
  test/grdview/grdview.ps
  test/grdview/grdview.sh
Labels: backport 6.1

#3683 Do not access font when not set
  src/gmt_plot.c
Labels: backport 6.1

#3685 Place movie indicator f without any shifts
  src/gmt_plot.c
Labels: backport 6.1, bug

#3687 Use --GMT_HISTORY=readonly when calling modules from other modules
  src/batch.c
  src/gmt_init.c
  src/gmt_io.c
  src/gmt_remote.c
  src/gmtlogo.c
  src/grd2kml.c
  src/grdblend.c
  src/grdfill.c
  src/grdfilter.c
  src/grdfilter_mt.c
  src/grdimage.c
  src/grdview.c
  src/img/img2grd.c
  src/movie.c
  src/psevents.c
  src/pslegend.c
  src/psxy.c
  src/subplot.c
  src/surface.c
  src/surface_experimental.c
Labels: documentation

#3688 Incomplete fix of grdsample required more work
  src/grdsample.c
Labels: backport 6.1, bug

#3690 Add -skipfailures to the ogr2ogr -f convert command
  src/gmt_io.c
Labels: backport 6.1

#3697 Add missing KEY for -N option
  src/grdcontour.c
Labels: backport 6.1

#3702 Let grdcontour -N support the oneliner syntax
  src/gmt_api.c
  src/grdcontour.c
Labels: backport 6.1

#3703 Let GMT examine if the DCW file has a minimum version requirement
  src/gmt_dcw.c
Labels: backport 6.1

#3709 Failed to requiest more memory in stair-step function
  src/gmt_vector.c
Labels: backport 6.1

#3712 Improve grdseamount documentation
  doc/rst/source/supplements/potential/grdseamount.rst
  doc/scripts/GMT_seamount_flux.ps
  doc/scripts/GMT_seamount_flux.sh
  doc/scripts/GMT_seamount_map.ps
  doc/scripts/GMT_seamount_map.sh
  doc/scripts/GMT_seamount_types.ps
  doc/scripts/GMT_seamount_types.sh
  src/potential/grdseamount.c
Labels: backport 6.1

#3715 grdseamount must write grids even if no change for a time-step
  doc/rst/source/supplements/potential/grdseamount.rst
  src/potential/grdseamount.c
Labels: backport 6.1, bug

#3720 Add instructions for "PATH too long" warning on Windows
  INSTALL.md
Labels: backport 6.1

#3738 gmt_make_enum_dicts.sh needed some TLC
  src/gmt_enum_dict.h
  src/gmt_make_enum_dicts.sh
Labels: backport 6.1, bug

#3740 More robust parsing to recognize -An or -A-
  src/grdcontour.c
Labels: backport 6.1

#3743 Only set geographic column formatting if in geographic mode
  src/project.c
Labels: backport 6.1

#3728 Let table-reading module us the same language regarding the input name
  doc/rst/source/supplements/potential/grdseamount.rst
  doc/rst/source/supplements/potential/talwani2d.rst
  doc/rst/source/supplements/potential/talwani3d.rst
  doc/rst/source/supplements/seis/coupe.rst
  doc/rst/source/supplements/seis/coupe_common.rst_
  doc/rst/source/supplements/seis/pscoupe.rst
  doc/rst/source/supplements/spotter/hotspotter.rst
  doc/rst/source/supplements/spotter/originater.rst
  doc/rst/source/supplements/spotter/rotsmoother.rst
Labels: documentation

#3745 Do not consider memory references remote files
  src/gmt_init.c
Labels: backport 6.1

#3748 Only check once if file is remote or not
  src/gmt_init.c
Labels: backport 6.1

#3751 Make sure -L pen does not replace frame pen
  src/pscontour.c
Labels: backport 6.1

#3753 Simplify contour arg parsing
  src/gmt_constants.h
  src/gmt_prototypes.h
  src/gmt_support.c
  src/gmt_types.h
  src/grdcontour.c
  src/pscontour.c
  test/trend2d/trend.sh
Labels: backport 6.1

#3742 Put quotes when writing DIR_DATA to scripts
  src/batch.c
  src/movie.c
Labels: backport 6.1

#3758 Make sure a path is not a dir before saying we found a file
  src/gmt_io.c
Labels: backport 6.1

#3762 Make sure all test scripts have a set GMT_SESSION_NAME
  doc/examples/gmtest.in
  doc/scripts/gmtest.in
  test/gmtest.in
Labels: backport 6.1

#3771 Do not let the API object for the assembled grid live on
  src/gmt_api.c
  src/gmt_internals.h
  src/gmt_remote.c
Labels: backport 6.1, bug

#3772 Highlight the problems with toggling the grid registration
  doc/rst/source/grdsample.rst
  doc/scripts/GMT_grid2pix.ps
  doc/scripts/GMT_grid2pix.sh
Labels: backport 6.1, documentation

#3773 Fix hinge for oleron CPT
  admin/build_scientific_colors_cpt.sh
  share/cpt/oleron.cpt
Labels: backport 6.1

#3718 Update GMT_IS_REFERENCE and GMT_IS_DUPLICATE to allow duplicating strings
  doc/rst/source/api.rst
  src/gmt_api.c
  src/gmt_enum_dict.h
  src/gmt_resources.h
  src/gmt_support.c
  src/testapi_vector_strings2.c
  test/modern/imagepluscpt.sh
Labels: backport 6.1

#3781 Let api_write_vector|matrix be aware of text
  src/gmt_api.c
Labels: backport 6.1, bug

#3783 Testing api io vectors
  src/gmt_api.c
  src/gmt_internals.h
  src/gmt_io.c
  src/testapi_vector_io.c
  test/api/apivec_io.ps
  test/api/apivec_io.sh
Labels: backport 6.1, bug

#3786 Implementing headers/trailing text for GMT_MATRIX i/o
  src/gmt_api.c
  src/testapi_matrix_io.c
  src/testapi_vector_io.c
  test/api/apimat_io.ps
  test/api/apimat_io.sh
Labels: backport 6.1, bug

#3791 Fix reST syntax for -l option
  doc/rst/source/cookbook/options.rst
Labels: backport 6.1

#3794 Deal with HAVE_GDAL
  src/gmt_api.c
  src/gmt_init.c
Labels: backport 6.1
