Repository GenericMappingTools/gmt, pull requests merged in 2021-11, with the labels that each got.

#5931 Set axis attribute in netCDF grid to pass GDALs new checks
  src/gmt_nc.c
Labels: enhancement

#5903 Let inset begin optionally take -R -J to determine inset size instead of via -D
  doc/rst/source/inset.rst
  doc/rst/source/subplot.rst
  src/inset.c
  test/modern/inset2.ps
  test/modern/inset2.sh
Labels: new core module feature

#5936 API: Switch to method from GMT_IS_REFERENCE to GMT_IS_DUPLICATE as needed
  doc/rst/source/devdocs/api.rst
  src/gmt_api.c
Labels: maintenance

#5939 Two modules missed a comma in list of args to GMT_usage
  src/grdvolume.c
  src/triangulate.c
Labels: bug

#5941 Correct gmtspatial snafu and add a test
  src/gmtspatial.c
  test/gmtspatial/andes_test.txt
  test/gmtspatial/duplicate.sh
Labels: bug

#5942 Fix freeing of pairs array
  src/x2sys/x2sys_cross.c
Labels: bug

#5943 Just give more info via messages
  src/gmt_support.c
Labels: maintenance

#5947 Fix wrap-around error in indexing for matrix-to-grid input
  src/gmt_api.c
Labels: bug

#5948 Update the z min/max inside readonly subsets
  src/gmt_api.c
  src/gmt_grdio.c
  src/gmt_internals.h
Labels: bug

#5949 Look for the spatial_ref attribute among all variables
  src/gmt_nc.c
Labels: bug

#5950 Use GMT_NOTSET instead of -1 when that is what is meant
  src/dimfilter.c
  src/gmt_api.c
  src/gmt_calclock.c
  src/gmt_dcw.c
  src/gmt_gdalread.c
  src/gmt_grdio.c
  src/gmt_init.c
  src/gmt_io.c
  src/gmt_map.c
  src/gmt_mgg_header2.c
  src/gmt_plot.c
  src/gmt_stat.c
  src/gmt_support.c
  src/grdfft.c
  src/grdimage.c
  src/mgd77/mgd77.c
  src/mgd77/mgd77track.c
  src/nearneighbor.c
  src/pscoast.c
  src/pscontour.c
  src/psconvert.c
  src/sphinterpolate.c
  src/spotter/backtracker.c
  src/spotter/grdspotter.c
  src/spotter/spotter.c
  src/x2sys/x2sys.c
  src/x2sys/x2sys_binlist.c
  src/x2sys/x2sys_datalist.c
Labels: maintenance

#5952 Detect srtm_relief in remote names
  src/gmt_remote.c
Labels: bug

#5955 Let grd2xyz option -T write STL output file
  doc/fig/GMT_STL.jpg
  doc/rst/source/grd2xyz.rst
  src/grd2xyz.c
Labels: new core module feature

#5956 Must distribute gmt_common_sighandler.h
  src/CMakeLists.txt
Labels: bug

#5958 Prevent warnings of w/e/s/n rounding if obtained via DCW
  src/gmt_grdio.c
  src/gmt_init.c
Labels: maintenance

#5961 Ensure we allocate enough space for sides in grdview
  src/grdview.c
Labels: bug

#5962 Apply loose -R fix inside gmtapi_grid_import
  src/gmt_api.c
  src/gmt_grdio.c
  src/gmt_internals.h
Labels: enhancement

#5953 Make sure create_table sets allocation mode
  src/gmt_api.c
  src/gmt_dcw.c
  src/gmt_hidden.h
  src/gmt_io.c
  src/gmt_map.c
  src/gmt_prototypes.h
  src/gmt_support.c
  src/gmtsplit.c
  src/grdview.c
  src/pslegend.c
  src/sphdistance.c
  src/spotter/grdrotater.c
  src/testapi_uservectors.c
Labels: bug, maintenance

#5964 Ensure external use of blockm can set many fields
  src/blockmean.c
  src/blockmedian.c
  src/blockmode.c
  src/gmt_api.c
Labels: bug

#5945 Remove animation cmake target
  .github/workflows/docs.yml
  MAINTENANCE.md
  admin/remote_data_use.sh
  ci/config-gmt-unix.sh
  ci/config-gmt-windows.sh
  cmake/ConfigUserAdvancedTemplate.cmake
  doc/examples/CMakeLists.txt
  doc/examples/animate.in
Labels: maintenance

#5966 Let -d set starting column via modifier
  doc/rst/source/common_SYN_OPTs.rst_
  doc/rst/source/explain_-d.rst_
  doc/rst/source/explain_-d_full.rst_
  doc/rst/source/explain_-di.rst_
  doc/rst/source/explain_-do.rst_
  doc/rst/source/std-opts-classic.rst
  doc/rst/source/std-opts.rst
  src/gmt_common.h
  src/gmt_init.c
  src/gmt_io.c
  src/gmt_prototypes.h
  src/gmt_synopsis.h
  src/grd2xyz.c
  src/xyz2grd.c
Labels: enhancement

#5968 Let psconvert -W+g switch to lossless PNG as intermediate format
  src/psconvert.c
Labels: enhancement, maintenance

#5971 Document the two histories of domains
  doc/rst/source/cookbook/features.rst
Labels: documentation

#5970 Let ex49 use mean for crustal ages
  doc/examples/CMakeLists.txt
  doc/examples/ex49/ex49.bat
  doc/examples/ex49/ex49.ps
  doc/examples/ex49/ex49.sh
  doc/rst/source/gallery/ex49.rst
Labels: documentation, maintenance

#5977 Let gmtget refresh server for -Dcache too
  src/gmtget.c
Labels: bug

#5980 Add -o to histogram and rose
  doc/rst/source/histogram.rst
  doc/rst/source/pshistogram.rst
  doc/rst/source/psrose.rst
  doc/rst/source/rose.rst
  src/pshistogram.c
  src/psrose.c
Labels: enhancement

#5978 Remember tile registration and increment
  src/gmt_init.c
  test/grdimage/autoresgrid.ps
  test/grdimage/autoresgrid.sh
Labels: bug

#5982 Avoid race condition when server table is refreshed by movie or batch
  src/gmt_remote.c
Labels: bug

#5983 Add inverted triangle to front symbol choices
  doc/rst/source/explain_symbols.rst_
  doc/scripts/GMT_base_symbols7.ps
  doc/scripts/GMT_base_symbols7.sh
  src/gmt_init.c
  src/gmt_plot.c
  src/gmt_plot.h
  src/psxy.c
  test/psxy/front.ps
  test/psxy/front.sh
Labels: new core module feature

#5984 Let project -G accept increment unit and +n modifier
  doc/rst/source/project.rst
  src/project.c
  test/project/ellipses.sh
Labels: enhancement

#5985 pstext -Dj cannot be used with -M
  doc/rst/source/text.rst
  src/pstext.c
Labels: documentation

#5991 Add more instructions to the contributing guide
  BUILDING.md
  MAINTENANCE.md
  doc/rst/source/devdocs/contributing.rst
  doc/rst/source/devdocs/maintenance.rst
  doc/rst/source/index.rst
Labels: documentation

#5992 Update gshhg documentation to be an external link
  doc/rst/source/coast.rst
  doc/rst/source/datasets.rst
  doc/rst/source/datasets/gshhg.rst
  doc/rst/source/explain_gshhg.rst_
  doc/rst/source/tutorial/session-1.rst
Labels: documentation

#5993 Ensure secondary pens always set their transparency
  src/postscriptlight.c
  src/psxy.c
Labels: bug

#5996 Fix incorrect selection of text color for paragraphs
  src/postscriptlight.c
Labels: bug

#5995 Implement smart justify -Dj for text -M
  doc/examples/ex17/ex17.bat
  doc/examples/ex17/ex17.sh
  src/pstext.c
  test/pstext/para_offset.ps
  test/pstext/para_offset.sh
Labels: enhancement

#5999 Enforce defaults in grdvector
  doc/rst/source/grdvector.rst
  src/grdvector.c
Labels: bug

#6001 Fix inaccuracy in -Gvalue+n in project
  src/project.c
Labels: bug

#6000 Fix remaining mem leak related to grdblend
  src/gmt_api.c
  src/gmt_internals.h
  src/gmt_remote.c
Labels: maintenance

#6002 Clean up vector documentation
  doc/rst/source/explain_vectors.rst_
  doc/rst/source/grdvector.rst
Labels: documentation

#6005 Fix or remove unused parameters and variables
  src/gmt_api.c
  src/gmt_common_sighandler.c
  src/gmt_init.c
  src/gmt_support.c
  src/grd2xyz.c
  src/grdtrend.c
  src/mapproject.c
  src/psconvert.c
  src/psevents.c
  src/pslegend.c
  src/testapi_spatial.c
  src/x2sys/x2sys_cross.c
Labels: maintenance

#6011 Ensure blockm* avoids unneeded work when -G is used
  doc/rst/source/blockmean.rst
  doc/rst/source/blockmedian.rst
  doc/rst/source/blockmode.rst
  src/blockmean.c
  src/blockmedian.c
  src/blockmode.c
Labels: maintenance

#6015 Add debug information about Xcode diagnostics
  doc/fig/xcode-4b.png
  doc/rst/source/devdocs/debug.rst
Labels: documentation

#6014 Ensure that correct domain and increment are used for -G in blockm*
  src/blockmean.c
  src/blockmedian.c
  src/blockmode.c
Labels: bug

#6017 Set filler status before checking number of tiles
  src/gmt_remote.c
Labels: bug

#5929 A new module: grdselect
  doc/rst/source/grdinfo.rst
  doc/rst/source/grdselect.rst
  doc/rst/source/module_core_purpose.rst_
  doc/rst/source/modules-classic.rst
  doc/rst/source/modules.rst
  src/CMakeLists.txt
  src/gmt_prototypes.h
  src/gmt_support.c
  src/grd2cpt.c
  src/grdselect.c
  src/makecpt.c
  test/grdselect/plot_CFL.ps
  test/grdselect/plot_CFL.sh
  test/grdselect/region_u_i.ps
  test/grdselect/region_u_i.sh
  test/grdselect/regions.sh
Labels: add-changelog, new module

#6020 Remove deprecated -Fnone from script
  doc/scripts/GMT_movie_progress.sh
Labels: maintenance

#6019 Add safety valve in grdsample on wesn wrapping
  src/grdsample.c
Labels: bug

#6021 Migrate remote dataset documentation to external site
  doc/rst/source/datasets/earth-age.rst_
  doc/rst/source/datasets/earth-daynight.rst_
  doc/rst/source/datasets/earth-masks.rst_
  doc/rst/source/datasets/earth-relief.rst_
  doc/rst/source/datasets/remote-data.rst
  doc/rst/source/grdlandmask.rst
Labels: documentation, add-changelog

#6023 Add @earth_age_10m to the CI cache
  .github/workflows/ci-caches.yml
Labels: maintenance

#6022 Update changelog and version_switch for 6.3 release
  doc/rst/_static/version_switch.js
  doc/rst/source/changes.rst
  doc/rst/source/index.rst
Labels: documentation, maintenance

#6024 Set GMT_movie_progress.sh as a known windows failure
  doc/scripts/GMT_movie_progress.sh
Labels: maintenance

#6031 Remove the experimental label for grdlandmask -E
  src/grdlandmask.c
Labels: documentation, maintenance

#6030 Use verbose code macro where the codes are needed
  src/gmt_init.c
  src/grdfilter.c
  src/surface.c
  src/surface_experimental.c
Labels: bug

#6029 Simplify bundle by avoiding ghostscript version number in paths
  admin/build-macos-external-list.sh
  admin/build-release.sh
  cmake/dist/startup_macosx.sh.in
Labels: maintenance

#6036 Check that font_no is not -1 before using it as index
  src/gmt_plot.c
Labels: bug

#6034 For items known to not exist, do not call gmt_M_free
  src/gmt_io.c
  src/gmt_memory.c
  src/gmt_plot.c
  src/gmt_support.c
Labels: maintenance

#6042 Add --show-gshhg and --show-dcw to gmt
  doc/rst/source/gmt.rst
  src/gmt.c
  src/gmt_dcw.c
  src/gmt_dcw.h
  src/gmt_prototypes.h
  src/gmt_shore.c
Labels: enhancement

#6033 Just quieting a few warnings after 6.3 merge
  src/gmt_api.c
  src/gmt_io.c
  src/gmt_remote.c
  src/grd2xyz.c
  src/grdselect.c
  src/greenspline.c
  src/potential/gmtgravmag3d.c
  src/pssolar.c
  src/testapi_spectrum1d.c
Labels: maintenance

#6044 Include gmt_common_byteswap.h for bswap32.
  src/grd2xyz.c
Labels: bug

#6039 Improve the argument for GMT_TRACK_MEMORY
  src/gmt_memory.c
Labels: maintenance

#6045 Internal index for custom gridinterval was wrong
  src/gmt_plot.c
Labels: bug

#6050 Improve stereographic projection checking
  doc/rst/source/cookbook/map-projections.rst
  src/gmt_init.c
  src/gmt_map.c
Labels: documentation, maintenance

#6051 Document gmt subplot -A for skipping a tag
  doc/rst/source/subplot.rst
  src/subplot.c
Labels: documentation

#6054 Fix a minor memory leak related to cube creation
  src/gmt_api.c
Labels: maintenance

#6056 Flip frame default for south pole aspect
  doc/examples/ex42/ex42.bat
  doc/examples/ex42/ex42.ps
  doc/examples/ex42/ex42.sh
  src/gmt_init.c
Labels: bug

#6057 Let @J in GMT/OGR files set -fg if implying degree coordinates
  src/gmt_io.c
Labels: enhancement

#6062 Let gmt usage message spell out standard input and output
  src/docs.c
  src/gmt_init.c
  src/grdcut.c
  src/mgd77/mgd77magref.c
  src/psternary.c
  src/seis/pssac.c
  src/spectrum1d.c
Labels: documentation

#6061 Spell out stdin and stdout in documentation
  doc/rst/source/changes.rst
  doc/rst/source/colorbar.rst
  doc/rst/source/contour.rst
  doc/rst/source/cookbook/features.rst
  doc/rst/source/explain_contdump.rst_
  doc/rst/source/gmt.rst
  doc/rst/source/gmtconnect.rst
  doc/rst/source/gmtconvert.rst
  doc/rst/source/gmtget.rst
  doc/rst/source/gmtmath.rst
  doc/rst/source/gmtregress.rst
  doc/rst/source/gmtspatial.rst
  doc/rst/source/gmtsplit.rst
  doc/rst/source/grdcontour.rst
  doc/rst/source/grdfft.rst
  doc/rst/source/grdhisteq.rst
  doc/rst/source/greenspline.rst
  doc/rst/source/legend.rst
  doc/rst/source/makecpt.rst
  doc/rst/source/mask.rst
  doc/rst/source/rose.rst
  doc/rst/source/spectrum1d.rst
  doc/rst/source/supplements/geodesy/earthtide.rst
  doc/rst/source/supplements/geodesy/gpsgridder.rst
  doc/rst/source/supplements/mgd77/mgd77convert.rst
  doc/rst/source/supplements/mgd77/mgd77magref.rst
  doc/rst/source/supplements/mgd77/mgd77manage.rst
  doc/rst/source/supplements/potential/gmtflexure.rst
  doc/rst/source/supplements/potential/gravfft.rst
  doc/rst/source/supplements/potential/grdseamount.rst
  doc/rst/source/supplements/potential/talwani3d.rst
  doc/rst/source/supplements/spotter/backtracker.rst
  doc/rst/source/supplements/spotter/grdrotater.rst
  doc/rst/source/supplements/spotter/grdspotter.rst
  doc/rst/source/supplements/spotter/polespotter.rst
  doc/rst/source/supplements/x2sys/x2sys_list.rst
  doc/rst/source/supplements/x2sys/x2sys_merge.rst
  doc/rst/source/supplements/x2sys/x2sys_put.rst
  doc/rst/source/supplements/x2sys/x2sys_report.rst
  doc/rst/source/supplements/x2sys/x2sys_solve.rst
  doc/rst/source/tutorial/session-4.rst
  doc/rst/source/xyz2grd.rst
Labels: documentation

#6060 gmtspatial -Q ignored user selection of unit
  doc/rst/source/gmtspatial.rst
  src/gmt_sph.c
  src/gmt_support.c
  src/gmtspatial.c
Labels: bug, documentation

#6067 Be more careful when considering jumps in x-direction
  src/gmt_map.c
  test/grdcontour/wrapping.ps
  test/grdcontour/wrapping.sh
Labels: bug

#6069 Increase string length for command
  src/grdinterpolate.c
Labels: bug

#6070 Fix array index and range bugs in grdinterpolate
  doc/rst/source/grdinterpolate.rst
  src/gmt_support.c
  src/grdinterpolate.c
Labels: bug
