Repository GenericMappingTools/gmt, pull requests merged in 2021-08, with the labels that each got.

#5574 JPEG quality and recognition of modifiers
  doc/rst/source/begin.rst
  doc/rst/source/figure.rst
  doc/rst/source/psconvert.rst
  src/begin.c
  src/figure.c
  src/gmt_constants.h
  src/gmt_init.c
  src/psconvert.c
Labels: add-changelog, enhancement, new core module feature

#5581 Remove extra newlines
  src/begin.c
  src/clear.c
  src/docs.c
  src/end.c
  src/figure.c
Labels: documentation

#5597 Let colorbar non-B-labels handle Latex as elsewhere
  src/psscale.c
Labels: bug

#5598 Clarify what grdhisteq -Nnorm does
  doc/rst/source/grdhisteq.rst
  src/grdhisteq.c
Labels: documentation

#5583 Let gmt end better handle -A args
  doc/rst/source/psconvert.rst
  src/figure.c
  src/gmt_constants.h
  src/gmt_init.c
  src/psconvert.c
Labels: add-changelog, deprecation

#5589 Add a GMT team page and update contributor recognition model
  THANKS.md
  doc/rst/_static/style.css
  doc/rst/source/changes.rst
  doc/rst/source/cookbook/features.rst
  doc/rst/source/devdocs/api.rst
  doc/rst/source/devdocs/debug.rst
  doc/rst/source/devdocs/devdocs.rst
  doc/rst/source/devdocs/postscriptlight.rst
  doc/rst/source/devdocs/rst-cheatsheet.rst
  doc/rst/source/devdocs/rst-cheatsheet.rst_
  doc/rst/source/devdocs/team.rst
  doc/rst/source/index.rst
Labels: documentation, add-changelog

#5610 Allow trailing comments in custom symbol files
  src/gmt_support.c
Labels: new feature

#5613 Consolidate -A into -F for a more unified option
  doc/rst/source/movie.rst
  src/movie.c
Labels: add-changelog, deprecation

#5607 Fix failure when using +sa for auto grid-range scaling
  src/gmt_support.c
  test/xyz2grd/gridrange.sh
Labels: bug

#5616 Binary documentation and usage update
  doc/rst/source/explain_-bi.rst_
  doc/rst/source/explain_-bi_full.rst_
  doc/rst/source/explain_-bo.rst_
  doc/rst/source/explain_-bo_full.rst_
  doc/rst/source/std-opts-classic.rst
  doc/rst/source/std-opts.rst
  src/gmt_init.c
  src/gmt_synopsis.h
  src/psxy.c
  src/psxyz.c
Labels: documentation

#5617 Update -g synopsis, syntax, usage and docs
  doc/rst/source/explain_-g.rst_
  doc/rst/source/explain_-g_full.rst_
  doc/rst/source/std-opts-classic.rst
  doc/rst/source/std-opts.rst
  src/gmt_init.c
  src/gmt_synopsis.h
Labels: documentation, add-changelog, deprecation

#5618 Update how -f is presented in usage and docs
  doc/rst/source/cookbook/options.rst
  doc/rst/source/explain_-f_full.rst_
  doc/rst/source/std-opts-classic.rst
  doc/rst/source/std-opts.rst
  src/gmt_init.c
  src/gmt_synopsis.h
Labels: documentation

#5640 Fix colorbar -Zwidths problems
  doc/rst/source/colorbar.rst
  doc/rst/source/colorbar_common.rst_
  doc/rst/source/psscale.rst
  src/psscale.c
  test/psscale/customwidths.ps
  test/psscale/customwidths.sh
Labels: bug

#5641 Maintenance: use gmt_get|set_column_type
  src/filter1d.c
  src/gmt_init.c
  src/gmt_support.c
  src/psrose.c
Labels: maintenance

#5623 Docs cleanup
  doc/rst/source/explain_-q.rst_
  doc/rst/source/explain_-q_full.rst_
  doc/rst/source/explain_-qi.rst_
  doc/rst/source/explain_-qo.rst_
  src/gmt_init.c
  src/gmt_synopsis.h
Labels: documentation

#5660 Fix errors in sample1d for monotonically decreasing time
  src/gmt_support.c
  src/sample1d.c
Labels: bug

#5657 Enable gridlines when colormap -B implies it
  src/gmt_init.c
  src/gmt_plot.c
  test/pslegend/legcpt.ps
Labels: bug

#5659 Better estimation of background frame for colormap -Q
  src/psscale.c
Labels: bug

#5658 Ensure colorbar uses -S+y when no -B given but -L is given
  src/psscale.c
Labels: bug

#5664 Complete gmt info -T for absolute time data column
  doc/rst/source/gmt.conf.rst
  doc/rst/source/gmtinfo.rst
  src/gmt_common_string.c
  src/gmt_common_string.h
  src/gmt_constants.h
  src/gmt_init.c
  src/gmtinfo.c
Labels: enhancement

#5666 Correct a parsing mistake in mapproject -G
  src/mapproject.c
Labels: bug

#5665 Improve check for zero or negative font size to turn of labelling in seis
  src/seis/pscoupe.c
  src/seis/psmeca.c
  src/seis/pspolar.c
Labels: bug

#5678 Strengthen parsing of events -Ardpi
  src/psevents.c
Labels: maintenance

#5679 Let sample1d sample equidistantly along arc, not cord
  src/gmt_types.h
  src/gmt_vector.c
  src/sample1d.c
  test/pswiggle/wiggles.ps
Labels: enhancement

#5649 Add linear moment scaling to coupe and meca
  doc/rst/source/supplements/seis/coupe.rst
  doc/rst/source/supplements/seis/coupe_common.rst_
  doc/rst/source/supplements/seis/explain_meca_-S.rst_
  doc/rst/source/supplements/seis/meca.rst
  doc/rst/source/supplements/seis/meca_common.rst_
  doc/rst/source/supplements/seis/pscoupe.rst
  doc/rst/source/supplements/seis/psmeca.rst
  src/seis/CMakeLists.txt
  src/seis/meca.h
  src/seis/meca_symbol.h
  src/seis/pscoupe.c
  src/seis/psmeca.c
  test/pspolar/pspolar_01.sh
  test/pspolar/pspolar_02.sh
  test/seis/meca_unusual_beachball.sh
  test/seis/seis_08.sh
  test/seis/seis_13.ps
  test/seis/seis_13.sh
Labels: supplement update

#5680 Fix psconvert options in begin and figure docs
  doc/rst/source/begin.rst
  doc/rst/source/figure.rst
Labels: documentation

#5685 Two small issues in movie and events
  src/movie.c
  src/psevents.c
Labels: bug

#5682 Ensure that valid formats jpeg and tiff result in those extensions
  src/gmt_gsformats.h
  src/gmt_init.c
Labels: bug

#5683 Improve animation of trajectories in events
  doc/rst/source/events_common.rst_
  src/psevents.c
  test/movie/trajectory1.ps
  test/movie/trajectory1.sh
Labels: enhancement

#5688 Let events use GMT_Read_Data instead of GMT_Get_Record
  src/psevents.c
Labels: maintenance

#5681 Point out that events -Ardpi may need to go into the main script
  doc/rst/source/events.rst
  doc/rst/source/events_common.rst_
  doc/rst/source/psevents.rst
Labels: documentation

#5687 Demonstrate events trajectory via resampling the line as points
  test/movie/trajectory2.ps
  test/movie/trajectory2.sh
Labels: documentation

#5691 Test animating lines with variable "pen" color
  test/movie/trajectory3.ps
  test/movie/trajectory3.sh
Labels: documentation

#5690 Ensure movie can accept either PostScript or EPS files
  doc/rst/source/movie.rst
  src/gmt_support.c
Labels: enhancement

#5606 Add v (vector) to custom symbol kit, plus handle azimuth vs angle
  doc/rst/source/cookbook/custom-symbols.rst
  doc/scripts/GMT_angle-azim.ps
  doc/scripts/GMT_angle-azim.sh
  src/gmt_plot.c
  src/gmt_support.c
  src/gmt_symbol.h
Labels: enhancement

#5695 Let events support temporal color changes
  doc/rst/source/events.rst
  doc/rst/source/events_common.rst_
  doc/rst/source/psevents.rst
  doc/scripts/psevents_dz.ps
  doc/scripts/psevents_dz.sh
  src/psevents.c
  test/movie/trajectory5.ps
  test/movie/trajectory5.sh
Labels: new core module feature

#5602 Consistently describe input grid name and modifiers
  doc/rst/source/cookbook/features.rst
  doc/rst/source/explain_grd_inout.rst_
  doc/rst/source/grdconvert.rst
  src/dimfilter.c
  src/gmt_constants.h
  src/gmt_grdio.c
  src/gmt_init.c
  src/gmt_prototypes.h
  src/gmt_synopsis.h
  src/grd2cpt.c
  src/grd2kml.c
  src/grd2xyz.c
  src/grdclip.c
  src/grdcontour.c
  src/grdconvert.c
  src/grdcut.c
  src/grdedit.c
  src/grdfft.c
  src/grdfill.c
  src/grdfilter.c
  src/grdgradient.c
  src/grdhisteq.c
  src/grdimage.c
  src/grdinfo.c
  src/grdproject.c
  src/grdsample.c
  src/grdtrack.c
  src/grdtrend.c
  src/grdvolume.c
  src/potential/gravfft.c
  src/potential/grdredpol.c
  src/potential/talwani3d.c
  src/spotter/grdpmodeler.c
  src/spotter/grdrotater.c
  src/spotter/grdspotter.c
  src/spotter/polespotter.c
Labels: documentation

#5710 Draw clip path before initiating clipping
  doc/rst/source/clip_common.rst_
  src/gmt_init.c
  src/gmt_prototypes.h
  src/psclip.c
  test/psclip/clip_draw.ps
  test/psclip/clip_draw.sh
Labels: bug

#5713 Let Latex text use the specified font color
  src/gmt_plot.c
  src/postscriptlight.c
  src/postscriptlight.h
  src/pstext.c
  test/latex/latexrgb.ps
  test/latex/latexrgb.sh
Labels: bug

#5717 Enable greenspline in modern mode to pick up session -R -I -r
  doc/rst/source/batch.rst
  doc/rst/source/movie.rst
  src/greenspline.c
Labels: bug

#5719 Allow for angled cross-tracks in grdtrack -C
  doc/rst/source/grdtrack.rst
  src/gmt_prototypes.h
  src/gmt_support.c
  src/grdtrack.c
  test/grdtrack/crosstrack_cart.ps
  test/grdtrack/crosstrack_cart.sh
  test/grdtrack/crosstrack_geo.ps
  test/grdtrack/crosstrack_geo.sh
Labels: bug, enhancement

#5714 Update greenspline -C for writing intermediate grids
  doc/rst/source/greenspline.rst
  src/gmt_vector.c
  src/greenspline.c
Labels: enhancement, deprecation
