Repository GenericMappingTools/gmt, pull requests merged in 2021-10, with the labels that each got.

#5827 Complete -D parsing update
  src/gmt_grdio.c
Labels: bug, deprecation

#5835 Correctly set region to read
  src/gmt_grdio.c
Labels: bug

#5842 Fix vertical colorbar with custom annotations
  src/psscale.c
  test/psscale/vertcustannot.ps
  test/psscale/vertcustannot.sh
Labels: bug

#5821 Clip boundaries to horizon for polar aspect azimuthal projections
  doc/examples/ex42/ex42.ps
  src/gmt_init.c
  src/gmt_map.c
  src/gmt_plot.c
  test/gmtspatial/poldecimate.ps
  test/gshhg/comb_ants.ps
  test/gshhg/two_ants.ps
  test/psbasemap/azim_polar.ps
  test/psscale/placebars.ps
  test/psxy/antwrap.ps
  test/psxy/windbarb.ps
  test/x2sys/x2sys_07.ps
Labels: enhancement, maintenance

#5819 Let multi-layer geotiff files be cut via gdal_translate
  doc/rst/source/grdcut.rst
  src/gmt_api.c
  src/gmt_gdalread.c
  src/gmt_grdio.c
  src/grdcut.c
Labels: enhancement

#5844 For error bars, allow asymmetrical bounds as well
  doc/rst/source/plot.rst
  doc/rst/source/psxy.rst
  src/psxy.c
  test/psxy/error_bars_asymm.ps
  test/psxy/error_bars_asymm.sh
Labels: new core module feature

#5843 Handle polar caps for TM maps as well
  doc/rst/source/gmt.conf.rst
  doc/scripts/GMT_TM.ps
  src/gmt_internals.h
  test/grdcontour/TMcontours.ps
  test/pscoast/placement.ps
  test/psxy/tissot_TM.ps
Labels: bug

#5848 Clarify reliance of colorbar -B on -R and -J
  doc/rst/source/colorbar.rst
Labels: documentation

#5847 Add deprecations section to ReST documentation
  doc/rst/source/gmt.rst
  doc/rst/source/greenspline.rst
  doc/rst/source/movie.rst
  doc/rst/source/psconvert.rst
  doc/rst/source/supplements/geodesy/gpsgridder.rst
Labels: documentation, add-changelog

#5926 Only call gmt_assemble_grid when want the data set
  src/gmt_api.c
  src/gmt_init.c
  src/gmt_private.h
  src/grdview.c
Labels: maintenance
