Repository GenericMappingTools/gmt, pull requests merged in 2021-07, with the labels that each got.

#5418 Update Blockmedian|mode usage messages
  doc/rst/source/blockmedian.rst
  doc/rst/source/blockmode.rst
  src/blockmean.c
  src/blockmedian.c
  src/blockmode.c
Labels: documentation

#5411 Fix greenspline usage and add -f
  doc/rst/source/common_SYN_OPTs.rst_
  doc/rst/source/grdedit.rst
  doc/rst/source/grdinterpolate.rst
  doc/rst/source/greenspline.rst
  doc/rst/source/supplements/segy/segy2grd.rst
  doc/rst/source/xyz2grd.rst
  src/gmt_grdio.c
  src/greenspline.c
Labels: documentation

#5424 Update usage messages of grd2xyz
  src/grd2xyz.c
Labels: documentation

#5422 Update usage message for gmtsplit
  src/gmtsplit.c
Labels: documentation

#5421 Update usage message for gmtselect
  src/gmt_init.c
  src/gmtselect.c
Labels: documentation

#5419 Improve gmt2kml usage
  doc/rst/source/gmt2kml.rst
  doc/rst/source/grdmath.rst
  src/gmt2kml.c
  src/gmt_init.c
Labels: documentation

#5420 Update grd2kml usage message layout
  doc/rst/source/grd2kml.rst
  src/grd2kml.c
Labels: documentation

#5423 Update usage for grd2cpt
  src/gmt_support.c
  src/grd2cpt.c
Labels: documentation

#5427 Skip NaN-records in seis and geodesy due to unrecognized header records
  src/geodesy/psvelo.c
  src/seis/pscoupe.c
  src/seis/psmeca.c
  src/seis/pspolar.c
Labels: bug

#5442 Let grdcut -S properly handle arc distances
  src/grdcut.c
Labels: bug

#5437 Update grdblend usage
  src/grdblend.c
Labels: documentation

#5434 Improve the gmtconvert usage message
  src/gmtconvert.c
Labels: documentation

#5436 Update gmtregress usage
  src/gmtregress.c
Labels: documentation

#5435 Improve the gmtlogo usage
  src/gmtlogo.c
Labels: documentation

#5433 Update usage message for gmtconnect
  src/gmtconnect.c
Labels: documentation

#5438 Update grdclip usage message
  src/grdclip.c
Labels: documentation

#5428 Let pslegend handle decorated lines too
  src/gmt_init.c
  src/pslegend.c
  src/psxy.c
Labels: enhancement

#5439 Update usage messages for sph triple modules
  doc/rst/source/sphdistance.rst
  doc/rst/source/sphinterpolate.rst
  src/sphdistance.c
  src/sphinterpolate.c
  src/sphtriangulate.c
Labels: documentation

#5445 Update grdcut usage message
  src/grdcut.c
Labels: documentation

#5446 Update usage message for grdedit
  doc/rst/source/grdedit.rst
  src/grdedit.c
Labels: documentation

#5415 Clean up gmtinfo usage
  src/gmtinfo.c
Labels: documentation

#5448 Update grdfft usage messages
  doc/rst/source/grdfft.rst
  src/gmt_api.c
  src/gmt_synopsis.h
  src/grdfft.c
Labels: documentation

#5449 Update grdfill usage message
  doc/rst/source/grdfill.rst
  src/gmt_api.c
  src/grdfill.c
Labels: documentation

#5443 Update the usage messages for gmt defaults, get, and set
  doc/rst/source/gmtset.rst
  src/gmtdefaults.c
  src/gmtget.c
  src/gmtset.c
Labels: documentation

#5440 Update the usage messages of geodesy modules
  src/geodesy/earthtide.c
  src/geodesy/gpsgridder.c
  src/geodesy/psvelo.c
  src/gmt_init.c
Labels: documentation

#5453 Address shortcomings in grdcut -J
  src/grdcut.c
Labels: bug

#5451 Update grdgradient usage messages
  src/gmt_init.c
  src/grdgradient.c
Labels: documentation

#5452 Update grdhisteq usage message
  src/grdhisteq.c
Labels: documentation

#5454 Update grdimage usage message
  src/grdimage.c
Labels: documentation

#5455 Update grdinfo usage messages
  src/grdinfo.c
Labels: documentation

#5469 Update kml2gmt usage messages
  src/gmt_init.c
  src/kml2gmt.c
Labels: documentation

#5468 Update grdvolume usage message
  src/grdvolume.c
Labels: documentation

#5467 Update grdview usage messages
  src/grdview.c
Labels: documentation

#5466 Update grdvector usage messages
  src/grdvector.c
Labels: documentation

#5465 Update usage message for grdtrend
  src/grdtrend.c
Labels: documentation

#5464 Update grdsample usage messages
  src/grdsample.c
Labels: documentation

#5463 Update grdproject usage messages
  src/gmt_init.c
  src/gmt_synopsis.h
  src/grdproject.c
Labels: documentation

#5462 Update grdpaste usage mssage
  doc/rst/source/grdpaste.rst
  src/grdpaste.c
Labels: documentation

#5461 Update the grdmix usage messages
  doc/rst/source/grdmix.rst
  src/grdmix.c
Labels: documentation

#5470 Update usage message in makecpt
  src/gmt_api.c
  src/gmt_support.c
  src/grd2cpt.c
  src/makecpt.c
Labels: documentation

#5479 Do not close frame path unless requested
  src/gmt_plot.c
Labels: bug

#5472 Update usage messages from spotter
  doc/rst/source/supplements/spotter/backtracker.rst
  doc/rst/source/supplements/spotter/explain_rots.rst_
  doc/rst/source/supplements/spotter/gmtpmodeler.rst
  doc/rst/source/supplements/spotter/grdpmodeler.rst
  doc/rst/source/supplements/spotter/grdrotater.rst
  doc/rst/source/supplements/spotter/grdspotter.rst
  doc/rst/source/supplements/spotter/hotspotter.rst
  doc/rst/source/supplements/spotter/originater.rst
  doc/rst/source/supplements/spotter/rotconverter.rst
  doc/rst/source/supplements/spotter/rotsmoother.rst
  src/spotter/backtracker.c
  src/spotter/gmtpmodeler.c
  src/spotter/grdpmodeler.c
  src/spotter/grdrotater.c
  src/spotter/grdspotter.c
  src/spotter/hotspotter.c
  src/spotter/originater.c
  src/spotter/polespotter.c
  src/spotter/rotconverter.c
  src/spotter/rotsmoother.c
  src/spotter/spotter.c
  src/spotter/spotter.h
Labels: documentation

#5485 The gmtlib_process_binary_input function broke -g
  src/gmt_io.c
Labels: bug

#5501 Improve the hyphenation breaks in terminal
  src/gmt_api.c
Labels: documentation

#5500 Update rose usage messages
  src/psrose.c
Labels: documentation

#5499 Update mask usage messages
  src/psmask.c
Labels: documentation

#5498 Update histogram usage messages
  src/pshistogram.c
Labels: documentation

#5505 Update usage message for sample1d
  src/gmt_support.c
  src/sample1d.c
Labels: documentation

#5503 Update text usage messages
  src/pstext.c
Labels: documentation

#5502 Update ternary usage messages
  src/psternary.c
Labels: documentation

#5504 Update wiggle usage messages
  src/pswiggle.c
Labels: documentation

#5471 Update usage messages from x2sys supplement
  doc/rst/source/supplements/x2sys/x2sys_cross.rst
  doc/rst/source/supplements/x2sys/x2sys_datalist.rst
  doc/rst/source/supplements/x2sys/x2sys_init.rst
  doc/rst/source/supplements/x2sys/x2sys_list.rst
  doc/rst/source/supplements/x2sys/x2sys_report.rst
  src/x2sys/x2sys_binlist.c
  src/x2sys/x2sys_cross.c
  src/x2sys/x2sys_datalist.c
  src/x2sys/x2sys_get.c
  src/x2sys/x2sys_init.c
  src/x2sys/x2sys_list.c
  src/x2sys/x2sys_merge.c
  src/x2sys/x2sys_put.c
  src/x2sys/x2sys_report.c
  src/x2sys/x2sys_solve.c
Labels: documentation

#5487 Update seis supplement usage messages
  doc/rst/source/supplements/seis/coupe.rst
  doc/rst/source/supplements/seis/coupe_common.rst_
  doc/rst/source/supplements/seis/pscoupe.rst
  src/seis/pscoupe.c
  src/seis/psmeca.c
  src/seis/pspolar.c
  src/seis/pssac.c
Labels: documentation

#5488 Update segy usage messages
  src/segy/pssegy.c
  src/segy/pssegyz.c
  src/segy/segy2grd.c
Labels: documentation

#5514 Let gmt end show only display the first graphics-format listed
  doc/rst/source/end.rst
  src/gmt_init.c
Labels: bug

#5489 Update gshhg usage and fix -G bug
  src/gshhg/gshhg.c
Labels: bug, documentation

#5509 Turn off implicit output in externals if spectrum1d -T is given
  doc/rst/source/sph2grd.rst
  src/gmt_api.c
  src/sph2grd.c
Labels: bug

#5511 Update surface usage messages
  doc/rst/source/surface.rst
  src/surface.c
Labels: documentation

#5508 Improve Spectrum1d usage messages
  doc/rst/source/spectrum1d.rst
  src/spectrum1d.c
Labels: documentation

#5497 Update usage messages of image and legend
  src/psimage.c
  src/pslegend.c
Labels: documentation

#5494 Update the psconvert usage messages
  src/psconvert.c
Labels: documentation

#5492 Update project usage messages
  src/project.c
Labels: documentation

#5510 Revised subplot usage messages
  doc/examples/ex03/ex03.sh
  doc/examples/ex12/ex12.sh
  doc/examples/ex16/ex16.sh
  doc/examples/ex34/ex34.sh
  doc/examples/ex47/ex47.sh
  doc/rst/source/subplot.rst
  doc/scripts/GMT_seamount_cum_inc.sh
  src/subplot.c
  test/filter1d/varfilt.sh
  test/geodesy/geodesy_07.sh
  test/gmtbinstats/nonweighted.sh
  test/gmtbinstats/nonweightedrect.sh
  test/gmtbinstats/weighted.sh
  test/grdcut/polycut.sh
  test/grdfilter/varfilter.sh
  test/grdimage/rounding.sh
  test/grdinterpolate/fake_geot_cube.sh
  test/grdinterpolate/fake_geoz_cube.sh
  test/grdinterpolate/fake_xyz_cube.sh
  test/grdvector/vec_scales.sh
  test/latex/subplotlatex.sh
  test/modern/box.sh
  test/modern/panels.sh
  test/modern/panels_history.sh
  test/modern/powlog.sh
  test/modern/somepanels.sh
  test/modern/vardims.sh
  test/modern/varfracs.sh
  test/potential/transfer.sh
  test/psbasemap/fancyannot.sh
  test/pshistogram/altwidth.sh
  test/pslegend/autolegendcolor.sh
  test/pslegend/autolegendcolorL.sh
  test/pslegend/panel_legend.sh
  test/psxy/autocolorlines.sh
  test/psxy/autocolorpols.sh
  test/psxy/scalesymb.sh
  test/psxy/snakes.sh
  test/psxyz/scalesymb.sh
  test/sample1d/smooth.sh
  test/subplot/4legends.sh
  test/subplot/panelsinside.sh
  test/subplot/subplot_3.0.ps
  test/subplot/subplot_3.0.sh
  test/subplot/subplot_3.1.ps
  test/subplot/subplot_3.1.sh
  test/subplot/subplot_3.2.ps
  test/subplot/subplot_3.2.sh
  test/subplot/subplot_3.3.ps
  test/subplot/subplot_3.3.sh
  test/subplot/subplot_4.0.ps
  test/subplot/subplot_4.0.sh
  test/subplot/subplot_4.1.ps
  test/subplot/subplot_4.1.sh
  test/subplot/subplot_4.2.ps
  test/subplot/subplot_4.2.sh
  test/subplot/subplot_4.3.ps
  test/subplot/subplot_4.3.sh
  test/subplot/subplotoverlay.sh
Labels: documentation

#5491 Update nearneighbor usage messages
  doc/rst/source/nearneighbor.rst
  src/nearneighbor.c
Labels: documentation

#5490 Update usage message for img2grd
  src/img/img2grd.c
Labels: documentation

#5526 Update solar usage messages
  doc/rst/source/solar_common.rst_
  src/pssolar.c
Labels: documentation

#5521 Update trend2d usage messages
  doc/rst/source/trend2d.rst
  src/trend2d.c
Labels: documentation

#5519 Update trend1d usage
  doc/rst/source/trend1d.rst
  src/trend1d.c
Labels: documentation

#5524 Update usage messages from potential supplement modules
  doc/rst/source/supplements/potential/gmtflexure.rst
  doc/rst/source/supplements/potential/gmtgravmag3d.rst
  doc/rst/source/supplements/potential/gravfft.rst
  doc/rst/source/supplements/potential/grdflexure.rst
  doc/rst/source/supplements/potential/grdgravmag3d.rst
  doc/rst/source/supplements/potential/grdredpol.rst
  doc/rst/source/supplements/potential/grdseamount.rst
  doc/rst/source/supplements/potential/talwani2d.rst
  doc/rst/source/supplements/potential/talwani3d.rst
  src/potential/gmtflexure.c
  src/potential/gmtgravmag3d.c
  src/potential/gravfft.c
  src/potential/grdflexure.c
  src/potential/grdgravmag3d.c
  src/potential/grdredpol.c
  src/potential/grdseamount.c
  src/potential/talwani2d.c
  src/potential/talwani3d.c
Labels: documentation

#5493 Update usage message for pscoast
  src/geodesy/psvelo.c
  src/gmt2kml.c
  src/gmt_dcw.c
  src/gmt_init.c
  src/gmt_prototypes.h
  src/gmt_support.c
  src/grdcontour.c
  src/grdvector.c
  src/grdview.c
  src/mgd77/mgd77track.c
  src/movie.c
  src/psclip.c
  src/pscoast.c
  src/pscontour.c
  src/psconvert.c
  src/psevents.c
  src/pshistogram.c
  src/pslegend.c
  src/psrose.c
  src/pssolar.c
  src/psternary.c
  src/pstext.c
  src/pswiggle.c
  src/psxy.c
  src/psxyz.c
  src/seis/pscoupe.c
  src/seis/psmeca.c
  src/seis/pspolar.c
  src/seis/pssac.c
Labels: documentation

#5530 Update mgd77 supplement usage messages
  doc/rst/source/supplements/mgd77/mgd77header.rst
  doc/rst/source/supplements/mgd77/mgd77info.rst
  doc/rst/source/supplements/mgd77/mgd77list.rst
  doc/rst/source/supplements/mgd77/mgd77path.rst
  doc/rst/source/supplements/mgd77/mgd77sniffer.rst
  doc/rst/source/supplements/mgd77/mgd77track-classic.rst
  doc/rst/source/supplements/mgd77/mgd77track.rst
  doc/rst/source/supplements/mgd77/mgd77track_common.rst_
  src/gmt_api.c
  src/gmt_init.c
  src/gmt_prototypes.h
  src/grdtrack.c
  src/mgd77/mgd77.c
  src/mgd77/mgd77.h
  src/mgd77/mgd77convert.c
  src/mgd77/mgd77header.c
  src/mgd77/mgd77info.c
  src/mgd77/mgd77list.c
  src/mgd77/mgd77magref.c
  src/mgd77/mgd77manage.c
  src/mgd77/mgd77path.c
  src/mgd77/mgd77sniffer.c
  src/mgd77/mgd77track.c
Labels: documentation

#5537 Update psclip usage messages
  src/psclip.c
Labels: documentation

#5540 Add documentation to movie on how to add an audio track
  doc/rst/source/movie.rst
Labels: documentation

#5547 Document -Re and -Ra for modern mode
  doc/rst/source/explain_-R.rst_
  doc/rst/source/explain_-Rgeo.rst_
Labels: documentation

#5539 Update usage messages from plot3d
  src/gmt_init.c
  src/psxy.c
  src/psxyz.c
Labels: documentation

#5559 Fix tiny issues in -U, -l, -h, -i synopses
  doc/rst/source/explain_-U.rst_
  src/gmt_init.c
  src/gmt_support.c
  src/gmt_synopsis.h
Labels: documentation

#5552 Complement the few gmt options without --show with a --show-* version
  src/gmt.c
Labels: documentation

#5549 Add sorting of --PAR=value as well
  src/gmt_parse.c
Labels: bug

#5565 Use same -W[+s|w] in several modules
  doc/rst/source/blockmean.rst
  doc/rst/source/blockmedian.rst
  doc/rst/source/blockmode.rst
  doc/rst/source/supplements/geodesy/gpsgridder.rst
  doc/rst/source/trend2d.rst
  src/blockmean.c
  src/blockmedian.c
  src/blockmode.c
  src/geodesy/gpsgridder.c
  src/gmtbinstats.c
  src/trend1d.c
  src/trend2d.c
Labels: documentation

#5569 Replace -N<nodata> with -di
  doc/rst/source/grdblend.rst
  doc/rst/source/supplements/segy/segy2grd.rst
  src/grdblend.c
  src/segy/segy2grd.c
  src/xyz2grd.c
Labels: documentation

#5570 Better project documentation
  doc/rst/source/project.rst
  doc/scripts/project_setup.ps
  doc/scripts/project_setup.sh
Labels: documentation
