Repository GenericMappingTools/gmt, pull requests merged in 2021-06, with the labels that each got.

#5198 Let movie master frame accept a different dpu than the movie frames
  doc/rst/source/movie.rst
  src/movie.c
Labels: new feature

#5201 Add suitable shorthands for creating month and day labels
  doc/rst/source/grd2cpt.rst
  doc/rst/source/makecpt.rst
  src/gmt_support.c
  src/grd2cpt.c
  src/makecpt.c
Labels: new feature

#5230 Add modifier +r to reverse direction of scalebar
  doc/rst/source/colorbar_common.rst_
  src/psscale.c
Labels: new feature

#5239 Add CUMSUM operator to grdmath
  doc/rst/source/grdmath.rst
  src/grdmath.c
  test/grdmath/sums_12m.ps
  test/grdmath/sums_12m.sh
  test/grdmath/sums_12p.ps
  test/grdmath/sums_12p.sh
  test/grdmath/sums_34m.ps
  test/grdmath/sums_34m.sh
  test/grdmath/sums_34p.ps
  test/grdmath/sums_34p.sh
Labels: new feature

#5263 Add polar resampling via -Ar|t in plot, plot3d, and clip
  doc/rst/source/clip.rst
  doc/rst/source/clip_common.rst_
  doc/rst/source/plot.rst
  doc/rst/source/plot3d.rst
  doc/rst/source/plot3d_common.rst_
  doc/rst/source/plot_common.rst_
  doc/rst/source/psclip.rst
  doc/rst/source/psxy.rst
  doc/rst/source/psxyz.rst
  src/gmt_vector.c
  src/psclip.c
  src/psxy.c
  src/psxyz.c
  test/psxy/polarcurves.ps
  test/psxy/polarcurves.sh
Labels: new feature

#5264 Let grdclip handle polar resampling via -Ar|t
  doc/rst/source/grdmask.rst
  src/grdmask.c
Labels: new feature

#5315 grdblend could leak memory for pixel grids just outside range
  src/grdblend.c
Labels: bug

#5316 Wrong count variable used when assigning tile weight in grdblend
  src/grdblend.c
  test/grdblend/blend_weights.ps
  test/grdblend/blend_weights.sh
Labels: bug

#5317 Let grd2cpt -L have ability to only set one limit
  doc/rst/source/grd2cpt.rst
  src/grd2cpt.c
Labels: new core module feature

#5322 Let project -Z accept units for ellipse major axis
  doc/rst/source/project.rst
  src/gmt_constants.h
  src/gmt_support.c
  src/project.c
Labels: maintenance

#5325 Fix wrong end index for filenames without extension in psconvert
  src/psconvert.c
Labels: bug

#5328 Let colorbar handle CPTs with transparency
  doc/rst/source/colorbar_notes.rst_
  src/psscale.c
  test/psscale/transp_scale.ps
  test/psscale/transp_scale.sh
Labels: add-changelog, new core module feature, new feature

#5333 Allow drop-down shade modifier in subplot tag option
  doc/rst/source/subplot.rst
  src/gmt_init.c
  src/gmt_plot.c
  src/gmt_symbol.h
  src/gmt_types.h
  src/subplot.c
Labels: add-changelog, new core module feature, new feature

#5334 Enable country-based clipping in coast -E
  doc/rst/source/coast.rst
  doc/rst/source/coast_common.rst_
  doc/rst/source/pscoast.rst
  src/gmt_dcw.c
  src/gmt_dcw.h
  src/gmt_init.c
  src/pscoast.c
  test/pscoast/coastclip.ps
  test/pscoast/coastclip.sh
Labels: add-changelog, new core module feature, new feature

#5337 velo -E wrongly turned on -L
  src/geodesy/psvelo.c
Labels: bug

#5320 Allow for a fixed label offset
  doc/rst/source/cookbook/features.rst
  doc/rst/source/gmt.conf.rst
  src/gmt_constants.h
  src/gmt_defaults.h
  src/gmt_init.c
  src/gmt_keywords.txt
  src/gmt_plot.c
  src/gmt_support.c
  src/pslegend.c
  src/psscale.c
  src/psternary.c
  src/subplot.c
  test/psbasemap/fixed_labeldist.ps
  test/psbasemap/fixed_labeldist.sh
Labels: add-changelog, new core module feature, new feature

#5269 INSTALL.md: add gentoo
  INSTALL.md
  doc/rst/source/cookbook/non-unix-platforms.rst
Labels: documentation

#5346 Fix problems in gmt_parse_array exposed by makecpt
  src/gmt_support.c
  test/makecpt/timecpt_noinc.sh
Labels: bug

#5357 Improve code readability using named PSL vector, wedge, and matharc dim indices
  src/geodesy/psvelo.c
  src/gmt_plot.c
  src/grdvector.c
  src/postscriptlight.c
  src/postscriptlight.h
  src/psrose.c
  src/psscale.c
  src/psxy.c
  src/psxyz.c
  src/seis/pspolar.c
Labels: maintenance

#5360 Multiple pen and docs fixes for psvelo
  doc/rst/source/supplements/geodesy/psvelo.rst
  doc/rst/source/supplements/geodesy/velo.rst
  doc/rst/source/supplements/geodesy/velo_common.rst_
  src/geodesy/psvelo.c
  test/geodesy/geodesy_01.sh
  test/geodesy/geodesy_03.sh
  test/geodesy/geodesy_04.sh
  test/geodesy/geodesy_06.sh
  test/geodesy/geodesy_07.ps
  test/geodesy/geodesy_07.sh
  test/geodesy/geodesy_09.ps
  test/geodesy/geodesy_09.sh
Labels: bug

#5361 Ensure ternary gridlines do not plot on top of frame
  src/psternary.c
  test/psternary/ternary_pol.ps
Labels: bug

#5370 Let -f<col>s explicity set start of input trailing text
  doc/rst/source/explain_-f_full.rst_
  src/gmt_init.c
  src/gmt_io.c
Labels: add-changelog, bug, new core module feature

#5363 Let grdimage resample 2nd grid used for intensities
  src/grdimage.c
  test/grdimage/twogrids.ps
  test/grdimage/twogrids.sh
Labels: add-changelog, new feature

#5372 Documentation improvements for -i and -o
  doc/rst/source/explain_-icols_full.rst_
  doc/rst/source/explain_-ocols_full.rst_
Labels: documentation

#5371 Improve velo docs with figure of the four symbols
  doc/rst/source/supplements/geodesy/velo_common.rst_
  doc/scripts/GMT_velo.ps
  doc/scripts/GMT_velo.sh
  src/geodesy/psvelo.c
Labels: documentation

#5373 Cannot trust GDAL metadata without reading the file
  src/gmt_gdalread.c
Labels: bug

#5362 Improve gmtmath -Q behavior
  doc/rst/source/gmtmath.rst
  src/gmt_init.c
  src/gmt_prototypes.h
  src/gmtmath.c
Labels: add-changelog, new core module feature

#5336 New gallery example 53 showing subplots and shading
  doc/examples/ex53/ex53.sh
  doc/rst/source/gallery.rst
  doc/rst/source/gallery/ex53.rst
  doc/scripts/GMT_App_N_1.ps
  share/custom/astroid.def
  share/custom/city.def
  share/custom/cross.def
  share/custom/crosshair.def
  share/custom/gmt_custom_symbols.conf
  share/custom/hneedle.def
  share/custom/hurricane.def
  share/custom/lcrescent.def
  share/custom/lflag.def
  share/custom/ltriangle.def
  share/custom/rcrescent.def
  share/custom/rflag.def
  share/custom/rtriangle.def
  share/custom/squaroid.def
  share/custom/star4.def
  share/custom/vneedle.def
  test/gmtest.in
Labels: add-changelog, documentation

#5387 Update gmtspatial usage messages
  doc/rst/source/gmtspatial.rst
  src/gmtspatial.c
Labels: documentation

#5386 Clean up events usage
  doc/rst/source/events.rst
  doc/rst/source/events_common.rst_
  doc/rst/source/psevents.rst
  src/psevents.c
Labels: documentation

#5383 Improve usage message from colorbar
  src/psscale.c
Labels: documentation

#5392 Rewrite how -i works internally for external sources
  src/gmt_api.c
  src/gmt_enum_dict.h
  src/gmt_internals.h
  src/gmt_io.c
  src/gmt_resources.h
  src/testapi_columns.c
  test/api/apicolumns_icol.sh
Labels: bug

#5402 Minor typo corrected.
  src/blockmean.c
Labels: documentation

#5405 Clean up end usage
  src/end.c
Labels: documentation

#5401 Minor fix for -o syntax in usage message
  src/gmt_synopsis.h
Labels: documentation

#5407 Clean up figure usage
  src/figure.c
Labels: documentation

#5400 Improve gmtvector usage
  doc/rst/source/gmtvector.rst
  src/gmtvector.c
Labels: documentation

#5398 Update usage message for grdtrack
  src/grdtrack.c
Labels: documentation

#5406 Clean up docs usage
  src/docs.c
Labels: documentation

#5391 Clean up blockmean usage message
  src/blockmean.c
  src/gmt_api.c
Labels: documentation

#5396 Clean up gmt math usage
  src/gmt_api.c
  src/gmtmath.c
Labels: documentation

#5399 Update mapproject usage
  doc/rst/source/mapproject.rst
  src/mapproject.c
Labels: documentation

#5390 Update movie usage and clean up syntax
  doc/rst/source/movie.rst
  src/batch.c
  src/gmt_init.c
  src/movie.c
Labels: documentation

#5404 Clean up clear usage
  src/clear.c
Labels: documentation

#5397 Clean up grdmath usage
  doc/rst/source/grdmath.rst
  src/gmt_init.c
  src/gmtmath.c
  src/grdmath.c
Labels: documentation

#5414 Improve filter1d usage messages
  doc/rst/source/filter1d.rst
  src/filter1d.c
Labels: documentation

#5413 Update grdfilter usage
  src/grdfilter.c
Labels: documentation

#5409 Improve grdcontour usage
  doc/rst/source/grdcontour.rst
  doc/rst/source/grdcontour_common.rst_
  src/gmt_init.c
  src/gmt_synopsis.h
  src/grdcontour.c
Labels: documentation

#5410 Update pscontour usage messages
  doc/rst/source/contour.rst
  doc/rst/source/contour_common.rst_
  doc/rst/source/pscontour.rst
  src/gmt_constants.h
  src/gmt_init.c
  src/gmt_prototypes.h
  src/pscontour.c
Labels: documentation
