Repository GenericMappingTools/gmt, pull requests merged in 2021-02, with the labels that each got.

#4761 Cleaning up -J usage message
  src/gmt_init.c
Labels: documentation

#4794 Reset record status when reading plain text record
  src/gmt_io.c
Labels: bug

#4793 Add the polynomial seamount shape to grdseamount arsenal
  doc/rst/source/supplements/module_supplements_purpose.rst_
  doc/rst/source/supplements/potential/grdseamount.rst
  doc/scripts/GMT_seamount_types.ps
  doc/scripts/GMT_seamount_types.sh
  src/potential/grdseamount.c
  test/potential/smt_poly.ps
  test/potential/smt_poly.sh
Labels: new feature

#4802 Distinguish between geographic and separate lon or lat wrapping
  src/gmt_grdio.c
  src/gmt_init.c
  src/gmt_map.c
  src/gmt_plot.c
  src/gmt_support.c
  src/gmtbinstats.c
  src/gmtinfo.c
  src/gmtselect.c
  src/gmtsplit.c
  src/grdblend.c
  src/grdcontour.c
  src/grdcut.c
  src/grdinfo.c
  src/grdmask.c
  src/grdpaste.c
  src/grdsample.c
  src/greenspline.c
  src/nearneighbor.c
  src/psxy.c
  src/psxyz.c
  src/surface.c
Labels: bug

#4803 Check how close to pole we are with -JOa
  src/gmt_init.c
  src/gmt_map.c
  test/psbasemap/JOb_pole.ps
  test/psbasemap/JOb_pole.sh
Labels: bug

#4801 Enable GMT_Put_Strings to also apply to Palettes
  doc/rst/source/api.rst
  src/gmt_api.c
  src/gmt_constants.h
  src/gmt_enum_dict.h
  src/gmt_hidden.h
  src/gmt_resources.h
  src/gmt_support.c
Labels: new feature

#4855 Fix wrong case for a label in doc figure
  doc/scripts/GMT_seamount_types.ps
  doc/scripts/GMT_seamount_types.sh
Labels: documentation

#4861 Fix typos in greenspline doc and add equations
  doc/rst/source/greenspline.rst
Labels: documentation

#4841 Add links to common options subsections in the cookbook
  doc/rst/source/cookbook/options.rst
Labels: documentation
