Repository GenericMappingTools/gmt, pull requests merged in 2022-01, with the labels that each got.

#6177 Add operators DEG2KM and KM2DEG to gmtmath
  doc/rst/source/gmtmath.rst
  src/gmtmath.c
Labels: enhancement

#6175 Eliminate the outward padding in gmt_grd_setregion
  src/gmt_grdio.c
Labels: bug

#6180 Developer enhancements and simplifications related to PSL
  cmake/ConfigUserAdvancedTemplate.cmake
  src/postscriptlight.c
  src/pscoast.c
Labels: maintenance

#6181 Check if plotting degenerate symbols for legend
  src/gmt_init.c
  src/gmt_plot.h
Labels: bug

#6178 Save any default CPT for remote datasets in hidden grid header
  src/gmt_api.c
  src/gmt_dev.h
  src/gmt_grdio.c
  src/gmt_hidden.h
  src/gmt_init.c
  src/gmt_io.c
  src/gmt_nc.c
  src/gmt_private.h
  src/gmt_prototypes.h
  src/gmt_remote.c
  src/gmt_support.c
  src/grd2kml.c
  src/grdcut.c
  src/grdimage.c
  src/grdview.c
  test/grdcut/polycut.sh
  test/grdfilter/highpass.sh
  test/grdimage/defcpt.ps
  test/grdimage/defcpt.sh
Labels: enhancement

#6182 Allow -l for auto-legends in events
  doc/rst/source/events.rst
  src/psevents.c
Labels: new feature

#6185 Close grid opened for row-by-row access before deleting
  src/grdblend.c
Labels: bug

#6193 Add further checks to ensure subset w/e/s/n is correct
  src/gmt_grdio.c
Labels: bug

#6194 Address items 3, 4, 7 in vector proposal
  doc/rst/source/explain_vectors.rst_
  src/gmt_init.c
  src/gmt_map.c
  src/gmt_prototypes.h
  src/grdvector.c
  src/psxy.c
  src/psxyz.c
Labels: enhancement

#6196 Switch to using q instead of u for user unit
  doc/examples/ex43/ex43.bat
  doc/examples/ex43/ex43.sh
  doc/examples/ex50/ex50.bat
  doc/examples/ex50/ex50.sh
  doc/rst/source/explain_3D_symbols.rst_
  doc/rst/source/explain_symbols.rst_
  src/gmt_init.c
  src/psxy.c
  src/psxyz.c
  test/gmtmath/cdfs1.sh
  test/gmtmath/pdfs1.sh
  test/psxy/error_bars.sh
Labels: maintenance, deprecation

#6197 Further vector scale improvements and enhancements
  doc/rst/source/explain_vectors.rst_
  src/gmt_init.c
  src/gmt_map.c
  src/gmt_plot.c
  src/gmt_plot.h
  src/gmt_prototypes.h
  src/gmt_support.c
  src/postscriptlight.h
  src/psxy.c
  src/psxyz.c
  test/psxy/vector2d_mods.ps
  test/psxy/vector2d_mods.sh
  test/psxyz/vector3d_mods.ps
  test/psxyz/vector3d_mods.sh
Labels: documentation, enhancement

#6202 Fix overflow in gpsgridder
  src/geodesy/gpsgridder.c
Labels: bug

#6203 use more space for an internal movie string
  src/movie.c
Labels: maintenance

#6205 Use prepend instead of add in instructions
  cmake/dist/startup_macosx.sh.in
Labels: documentation

#5888 Initialize data version control for managing test images
  .dvc/.gitignore
  .dvc/config
  .dvcignore
  .github/workflows/tests.yml
  BUILDING.md
  ci/install-dependencies-linux.sh
  ci/install-dependencies-macos.sh
  ci/install-dependencies-windows.sh
  doc/rst/source/devdocs/contributing.rst
  test/api/api_matrix_as_grid.ps
  test/api/apicubeplot.ps
  test/api/apicubeplot.sh
  test/api/apigrdpix.sh
  test/api/apimat.ps
  test/api/apimat2grd.ps
  test/api/apimat2grd.sh
  test/api/apimat_360.ps
  test/api/apimat_360.sh
  test/api/apimat_360_ref.ps
  test/api/apimat_360_ref.sh
  test/api/apimat_io.ps
  test/api/apimat_io.sh
  test/api/apimatgrd.ps
  test/api/apimatgrd.sh
  test/api/apimatimageplain.ps
  test/api/apimatimageplain.sh
  test/api/apimatimageshading.ps
  test/api/apimatimageshading.sh
  test/api/apiuserstrings.ps
  test/api/apiuserstrings.sh
  test/api/apivec.ps
  test/api/apivec_io.ps
  test/api/apivec_io.sh
  test/api/apivectorplot.ps
  test/api/apivectorplot.sh
  test/baseline/.gitignore
  test/baseline/api.dvc
  test/baseline/blockmean.dvc
  test/blockmean/xy2ij.ps
  test/blockmean/xy2ij.sh
  test/gmtest.in
Labels: maintenance

#6199 Add -l to grdvector for legend entry
  doc/rst/source/grdvector.rst
  src/gmt_init.c
  src/gmt_plot.c
  src/gmt_plot.h
  src/gmt_prototypes.h
  src/grdvector.c
  src/pslegend.c
  src/psxy.c
  src/psxyz.c
  test/grdvector/plate.ps
  test/grdvector/veclegendc.sh
  test/grdvector/veclegendg.sh
Labels: new feature, add-changelog

#6212 Let map roses have a default size of 10% of map width
  doc/rst/source/explain_-T_rose.rst_
  src/gmt_init.c
  src/gmt_plot.c
  src/gmt_support.c
  src/gmt_symbol.h
  src/gmt_synopsis.h
Labels: enhancement

#6219 Fix new bug due to wrong number of args
  src/gmt_nc.c
Labels: bug

#6220 Let grdinfo report default CPT for a grid
  src/grdinfo.c
Labels: enhancement, add-changelog

#6223 Let grdedit -D+c allow setting/removing default CPT for grid
  doc/rst/source/explain_-D_cap.rst_
  src/gmt_grdio.c
  src/gmt_nc.c
  src/gmt_synopsis.h
  src/grdedit.c
Labels: enhancement, maintenance

#6064 Implement DCW collections and allow full continent, country, and state names in -R -E
  doc/rst/source/coast.rst
  doc/rst/source/explain_-R.rst_
  doc/rst/source/explain_-Rgeo.rst_
  src/gmt_dcw.c
  src/gmt_dcw.h
  src/gmt_init.c
  src/pscoast.c
Labels: enhancement, add-changelog

#6226 Silence a few warnings
  src/gmt_error.c
  src/greenspline.c
  src/psxyz.c
Labels: maintenance

#6225 Fix regression in parsing MON-dd-yyyy strings
  src/gmt_api.c
  src/gmt_init.c
  src/gmt_internals.h
  src/gmt_io.c
Labels: bug

#6231 Improved handling when remote data are unavailble
  src/gmt_remote.c
Labels: bug

#6232 Let grdimage -Q+zvalue set the transparent pixel indirectly
  doc/rst/source/grdimage.rst
  src/grdimage.c
Labels: enhancement

#6234 Fix incorrect check in line shortening
  src/postscriptlight.c
  test/psxy/line_shortening.sh
Labels: bug

#6237 Ensure consistent use of table, t, +t when discussing tables
  doc/rst/source/explain_-q.rst_
  doc/rst/source/explain_-q_full.rst_
  doc/rst/source/explain_-qi.rst_
  doc/rst/source/explain_-qo.rst_
  doc/rst/source/gmtconvert.rst
  src/gmt_common.h
  src/gmt_init.c
  src/gmt_io.c
  src/gmt_support.c
  src/gmt_synopsis.h
  src/gmtinfo.c
Labels: maintenance, deprecation

#6242 Set default -di column to 0 in xyz2grd -Z
  src/xyz2grd.c
Labels: bug

#6245 Make sure both grd2xyz and xyz2grd handles -Z and -d
  src/grd2xyz.c
  src/xyz2grd.c
Labels: enhancement

#6246 Let coupe parse old format without error
  src/seis/pscoupe.c
Labels: enhancement

#6247 Turn on ~1m margin for auto-size plots
  src/gmt_constants.h
Labels: maintenance

#6249 DCW collection documentation
  doc/rst/source/coast.rst
  doc/rst/source/explain_-R.rst_
  doc/rst/source/explain_-Rgeo.rst_
Labels: documentation

#6252 Avoid race conditions when we can
  src/gmt_plot.c
  src/gmt_prototypes.h
  src/gmt_support.c
Labels: maintenance

#6255 Let gmtspatial -W extend segments from one of both ends
  doc/rst/source/gmtspatial.rst
  src/gmt_init.c
  src/gmt_map.c
  src/gmt_prototypes.h
  src/gmt_support.c
  src/gmtspatial.c
  src/gmtvector.c
  test/gmtspatial/extend.sh
Labels: new core module feature

#6253 Speed up grdmask -S
  src/grdmask.c
Labels: enhancement

#6254 Speed up psmask -S
  src/psmask.c
Labels: enhancement

#6259 Ensure azimuth is computed at the end points
  src/gmtspatial.c
Labels: bug

#6230 Improve openMP variables and macros to avoid unnecessary warnings
  src/blockmean.c
  src/blockmedian.c
  src/blockmode.c
  src/geodesy/gpsgridder.c
  src/gmt_api.c
  src/gmt_grd.h
  src/gmt_grdio.c
  src/gmt_map.c
  src/gmt_plot.c
  src/gmt_prototypes.h
  src/gmt_stat.c
  src/gmt_support.c
  src/gmtbinstats.c
  src/gmtselect.c
  src/grd2cpt.c
  src/grd2xyz.c
  src/grdclip.c
  src/grdcut.c
  src/grdedit.c
  src/grdfill.c
  src/grdfilter.c
  src/grdgradient.c
  src/grdhisteq.c
  src/grdimage.c
  src/grdinfo.c
  src/grdlandmask.c
  src/grdmask.c
  src/grdmath.c
  src/grdmix.c
  src/grdsample.c
  src/grdtrend.c
  src/grdvector.c
  src/grdview.c
  src/greenspline.c
  src/nearneighbor.c
  src/potential/gravfft.c
  src/potential/grdredpol.c
  src/potential/grdseamount.c
  src/potential/talwani2d.c
  src/potential/talwani3d.c
  src/psmask.c
  src/sph2grd.c
  src/sphinterpolate.c
  src/spotter/grdpmodeler.c
  src/spotter/grdrotater.c
  src/spotter/grdspotter.c
  src/spotter/hotspotter.c
  src/spotter/polespotter.c
  src/surface.c
  src/testapi_matrix_pad.c
  src/triangulate.c
Labels: maintenance

#6258 It is time to make GDAL a required prerequisite
  BUILDING.md
  cmake/ConfigUserAdvancedTemplate.cmake
  doc/examples/ex32/ex32.bat
  doc/examples/ex32/ex32.sh
  doc/rst/source/cookbook/features.rst
  doc/rst/source/cookbook/file-formats.rst
  doc/rst/source/cookbook/introduction.rst
  doc/rst/source/datasets/remote-data.rst
  doc/rst/source/explain_-Jproj_full.rst_
  doc/rst/source/gallery/ex32.rst
  doc/rst/source/gallery/ex51.rst
  doc/rst/source/gmt-config.rst
  doc/rst/source/grdimage-classic.rst
  doc/rst/source/grdimage.rst
  doc/rst/source/image.rst
  doc/rst/source/psconvert.rst
  doc/rst/source/surface.rst
  src/CMakeLists.txt
  src/gmt-config.in
  src/gmt.c
  src/gmt_api.c
  src/gmt_config.h.in
  src/gmt_customio.c
  src/gmt_dev.h
  src/gmt_esri_io.c
  src/gmt_gdalcall.c
  src/gmt_grdio.c
  src/gmt_init.c
  src/gmt_internals.h
  src/gmt_io.c
  src/gmt_io.h
  src/gmt_map.c
  src/gmt_nc.c
  src/gmt_plot.c
  src/gmt_prototypes.h
  src/gmt_types.h
  src/grd2kml.c
  src/grdblend.c
  src/grdconvert.c
  src/grdgdal.c
  src/grdimage.c
  src/nearneighbor.c
  src/psconvert.c
  src/psimage.c
  src/surface.c
  src/xyz2grd.c
  test/grdimage/readwrite_withgdal.sh
  test/psimage/transparent_gif.sh
  test/psimage/transparent_png.sh
  test/psimage/withgdal.sh
Labels: maintenance

#6272 Exclude grdimage padding when setting CPT limits
  doc/rst/source/explain_grdresample.rst_
  src/gmt_grdio.c
  src/grdimage.c
Labels: bug

#6276 The standard -Rw/e/s/n in degrees had +u in docs
  doc/rst/source/explain_-Rgeo.rst_
Labels: documentation

#6277 Minor typos and clarifications
  doc/rst/source/gmtbinstats.rst
  doc/rst/source/gmtmath.rst
  doc/rst/source/gmtsplit.rst
  doc/rst/source/grdmath.rst
  doc/rst/source/project.rst
  doc/rst/source/sample1d.rst
  doc/rst/source/spectrum1d.rst
  doc/rst/source/sphtriangulate.rst
  doc/rst/source/supplements/mgd77/mgd77list.rst
  doc/rst/source/supplements/mgd77/mgd77track.rst
  doc/rst/source/supplements/potential/gravfft.rst
Labels: documentation

#6279 Allow -I0/dy and -Idx/0 in gmt info
  doc/rst/source/gmtinfo.rst
  src/gmtinfo.c
Labels: enhancement

#6281 Do not use -R for image subset if oblique projection
  src/gmt_api.c
Labels: bug

#6287 CI: Temporarily remove test coverage upload
  .github/workflows/tests.yml
Labels: maintenance
