Repository GenericMappingTools/gmt, pull requests merged in 2022-05, with the labels that each got.

#6648 Fix dumb surface bug
  src/surface.c
Labels: bug

#6651 Check as early as possible if a grid has NaNs when FFTs will be used
  doc/rst/source/supplements/potential/gravfft.rst
  src/potential/gravfft.c
  src/potential/grdflexure.c
Labels: documentation, maintenance

#6652 Let movie set an environmental hint we are building frames
  src/gmt_plot.c
  src/movie.c
Labels: bug

#6657 Fix gravprism issues related to vertical scaling and NaNs
  src/potential/gravprisms.c
Labels: bug

#6646 Fix some issues related to geo vs cart
  src/gmt_api.c
  src/gmt_common.h
  src/gmt_init.c
  src/grd2kml.c
Labels: bug, maintenance

#6658 Tolerate Windows paths when looking for colon separator
  src/gmt_init.c
Labels: bug

#6659 Also handle a colon-search in GMT_Encode_Options
  src/gmt_api.c
  src/gmt_init.c
  src/gmt_internals.h
Labels: bug

#6661 Simplify colonoscopy on Windows
  src/gmt_init.c
Labels: bug

#6666 WIth -Z, movie should remove any existing workdir
  src/movie.c
Labels: enhancement

#6669 Let mapproject also find encompassing rectangular regions for non-oblique projections
  doc/rst/source/mapproject.rst
  src/mapproject.c
Labels: enhancement

#6673 Enhance mapproject to give closed domain polygons
  doc/rst/source/mapproject.rst
  doc/scripts/GMT_obl_regions.sh
  doc/scripts/images.dvc
  src/gmt_api.c
  src/mapproject.c
Labels: documentation, enhancement

#6674 Treat tile reading the same for data and intensity in grd2kml
  src/grd2kml.c
Labels: bug

#6664 Demux output grid from grdfft before returning in memory
  doc/rst/source/devdocs/api.rst
  src/gmt.h
  src/gmt_api.c
  src/gmt_enum_dict.h
  src/gmt_grdio.c
  src/gmt_resources.h
  src/grdfft.c
  src/potential/gravfft.c
  src/potential/grdflexure.c
Labels: bug

#6680 Forgot to add binstats to the gmt_modern.c translator
  src/gmt_modern.c
Labels: bug

#6681 Fix wrong counter used with status array in movie and batch
  src/batch.c
  src/movie.c
Labels: bug

#6683 Improve documentation and usage for movie
  doc/rst/source/movie.rst
  src/movie.c
Labels: documentation

#6684 Improve events documentation
  doc/rst/source/events.rst
  src/psevents.c
Labels: documentation

#6685 Use superscripts in math mode for km/m3
  doc/rst/source/supplements/potential/gravprisms.rst
  doc/rst/source/supplements/potential/grdseamount.rst
  doc/rst/source/supplements/potential/talwani2d.rst
  doc/rst/source/supplements/potential/talwani3d.rst
Labels: documentation

#6678 Add grid sampling as new algorithm to grdfill
  doc/rst/source/grdfill.rst
  src/grdfill.c
  test/baseline/grdfill.dvc
  test/grdfill/gridfill.sh
Labels: add-changelog, new core module feature

#6686 Make option flags clickable for module documentation of supplements
  doc/rst/source/supplements/geodesy/earthtide.rst
  doc/rst/source/supplements/geodesy/gpsgridder.rst
  doc/rst/source/supplements/geodesy/velo.rst
  doc/rst/source/supplements/gshhg/gshhg.rst
  doc/rst/source/supplements/img/img2grd.rst
  doc/rst/source/supplements/mgd77/mgd77convert.rst
  doc/rst/source/supplements/mgd77/mgd77list.rst
  doc/rst/source/supplements/mgd77/mgd77magref.rst
  doc/rst/source/supplements/mgd77/mgd77manage.rst
  doc/rst/source/supplements/mgd77/mgd77sniffer.rst
  doc/rst/source/supplements/mgd77/mgd77track.rst
  doc/rst/source/supplements/potential/gmtflexure.rst
  doc/rst/source/supplements/potential/gmtgravmag3d.rst
  doc/rst/source/supplements/potential/gravfft.rst
  doc/rst/source/supplements/potential/gravprisms.rst
  doc/rst/source/supplements/potential/grdflexure.rst
  doc/rst/source/supplements/potential/grdgravmag3d.rst
  doc/rst/source/supplements/potential/grdseamount.rst
  doc/rst/source/supplements/potential/talwani2d.rst
  doc/rst/source/supplements/potential/talwani3d.rst
  doc/rst/source/supplements/segy/pssegyz.rst
  doc/rst/source/supplements/segy/segy.rst
  doc/rst/source/supplements/segy/segy2grd.rst
  doc/rst/source/supplements/segy/segyz.rst
  doc/rst/source/supplements/seis/coupe.rst
  doc/rst/source/supplements/seis/meca.rst
  doc/rst/source/supplements/seis/polar.rst
  doc/rst/source/supplements/seis/sac.rst
  doc/rst/source/supplements/spotter/backtracker.rst
  doc/rst/source/supplements/spotter/grdpmodeler.rst
  doc/rst/source/supplements/spotter/grdrotater.rst
  doc/rst/source/supplements/spotter/grdspotter.rst
  doc/rst/source/supplements/spotter/hotspotter.rst
  doc/rst/source/supplements/spotter/originater.rst
  doc/rst/source/supplements/spotter/polespotter.rst
  doc/rst/source/supplements/spotter/rotconverter.rst
  doc/rst/source/supplements/spotter/rotsmoother.rst
  doc/rst/source/supplements/x2sys/x2sys_binlist.rst
  doc/rst/source/supplements/x2sys/x2sys_cross.rst
  doc/rst/source/supplements/x2sys/x2sys_datalist.rst
  doc/rst/source/supplements/x2sys/x2sys_get.rst
  doc/rst/source/supplements/x2sys/x2sys_init.rst
  doc/rst/source/supplements/x2sys/x2sys_list.rst
Labels: documentation

#6688 Fix wrong pen for contour legends
  src/grdcontour.c
  src/pscontour.c
Labels: bug

#6692 Fix regression in triangulate and clean up memory management
  src/triangulate.c
Labels: bug, maintenance

#6691 Let triangulate report triangle areas in -S with new -A
  doc/rst/source/triangulate.rst
  src/triangulate.c
Labels: enhancement, add-changelog

#6696 Using basemap -D in modern mode shall yield an error
  src/psbasemap.c
Labels: maintenance

#6699 ALso protect gm calls from paths with spaces
  src/movie.c
Labels: bug

#6698 Add a function for reading triangle indices
  src/gmt_prototypes.h
  src/gmt_support.c
  src/pscontour.c
Labels: maintenance

#6700 Handle undelimited hhmmss strings
  src/gmt_io.c
Labels: bug

#6702 Some chores related to triangulate
  src/triangulate.c
Labels: maintenance

#6703 Fix KEYS for grdflexure and a typo
  doc/rst/source/supplements/potential/grdflexure.rst
  src/potential/grdflexure.c
Labels: bug

#6705 Clean up grdseamount a bit
  doc/rst/source/supplements/potential/grdseamount.rst
  src/potential/grdseamount.c
Labels: documentation, maintenance

#6708 Improve consistency between grdseamount and grdflexure file names
  doc/rst/source/supplements/potential/grdflexure.rst
  doc/rst/source/supplements/potential/grdseamount.rst
  src/potential/CMakeLists.txt
  src/potential/grdflexure.c
  src/potential/grdseamount.c
  src/potential/modeltime.h
Labels: documentation, enhancement

#6709 Improve memory cleanup in grdflexure
  src/gmt_fft.c
  src/potential/grdflexure.c
Labels: maintenance

#6712 grdview -T with no -C requires auto cpt
  src/grdview.c
Labels: bug

#6537 Let surface use optimal region under the hood
  doc/examples/images.dvc
  doc/rst/source/surface.rst
  src/surface.c
  test/baseline/grdcontour.dvc
  test/baseline/surface.dvc
Labels: enhancement, add-changelog

#6710 Let data processors default to gridline reg for unspecified remote grids
  doc/examples/ex52/ex52.sh
  doc/examples/images.dvc
  doc/rst/source/datasets/remote-data.rst
  doc/rst/source/tutorial/session-4.rst
  doc/scripts/GMT_atan.sh
  doc/scripts/GMT_tut_16.sh
  doc/scripts/GMT_tut_19.sh
  src/gmt_init.c
  src/gmt_remote.c
  src/grdfill.c
  test/baseline/gmtmex.dvc
  test/baseline/grdfill.dvc
  test/genper/east_map_8.sh
  test/genper/pacific_map_2.sh
  test/grd2cpt/equalarea.sh
  test/grdcontour/contours.sh
  test/grdcut/polycut.sh
  test/grdfft/gfilter.sh
  test/grdfill/constfill.sh
  test/grdfill/gridfill.sh
  test/grdfill/nnfill.sh
  test/grdfill/showregions.sh
  test/grdfill/splinefill.sh
  test/grdfilter/filtertest.sh
  test/grdfilter/highpass.sh
  test/grdfilter/openmp.sh
  test/grdfilter/threads.sh
  test/grdimage/grdcyclic.sh
  test/grdimage/imgshade.sh
  test/grdimage/twogrids.sh
  test/grdsample/straddle.sh
  test/grdview/denver.sh
  test/grdview/rgb.sh
  test/grdview/texture.sh
  test/potential/grdokb_grav.sh
Labels: maintenance

#6734 Clean up the math module documentation
  doc/rst/source/explain_sto_rcl_clr.rst_
  doc/rst/source/gmtmath.rst
  doc/rst/source/grdmath.rst
Labels: documentation

#6744 Better doc on prohibited CPT output names
  doc/rst/source/grd2cpt.rst
  doc/rst/source/makecpt.rst
Labels: documentation

#6745 Add alloc return checks in xyz2grd
  src/xyz2grd.c
Labels: maintenance

#6746 Check that files in the share-path are nonzero if in current directory
  doc/rst/source/grd2cpt.rst
  doc/rst/source/makecpt.rst
  doc/rst/source/tutorial/session-4.rst
  src/gmt_io.c
Labels: documentation, enhancement

#6753 Clarify that -i will convert anything
  doc/rst/source/explain_-icols_full.rst_
Labels: documentation

#6754 Add -R in x2sys_cross
  doc/rst/source/supplements/x2sys/x2sys_cross.rst
Labels: documentation

#6751 Let modules called by modules in inset know of shrinking
  src/gmt_init.c
  src/gmt_map.c
  src/gmt_private.h
  src/inset.c
  src/pslegend.c
Labels: bug

#6758 Reset time to current TIME_UNIT
  src/gmt_support.c
Labels: bug

#6761 Prevent round-off from giving negative index
  src/gmt_map.c
Labels: bug
