Repository GenericMappingTools/gmt, pull requests merged in 2022-06, with the labels that each got.

#6767 Introduce directives -Mc and -Mf in grdinfo
  doc/rst/source/grdinfo.rst
  src/grdinfo.c
Labels: enhancement

#6768 Ensure column-wrap does not exceed periodicity
  src/gmt_support.c
Labels: bug

#6759 Check memory return
  src/gmt_api.c
  src/gmt_cdf.c
  src/gmt_customio.c
  src/gmt_dcw.c
  src/gmt_esri_io.c
  src/gmt_fft.c
  src/gmt_gdalcall.c
  src/gmt_gdalread.c
  src/gmt_gdalwrite.c
  src/gmt_grdio.c
  src/gmt_init.c
  src/gmt_io.c
  src/gmt_map.c
  src/gmt_mgg_header2.c
  src/gmt_nc.c
  src/gmt_parse.c
  src/gmt_remote.c
  src/gmt_shore.c
  src/gmt_sph.c
  src/gmt_stat.c
  src/gmt_support.c
  src/gmt_vector.c
Labels: maintenance

#6438 Document default Delaunay Triangulation algorithm as Shewchuk
  doc/rst/source/contour.rst
  doc/rst/source/gmt.conf.rst
  doc/rst/source/triangulate.rst
  src/TRIANGLE.HOWTO
Labels: documentation

#6776 Finalize TRIANGLE text
  src/TRIANGLE.HOWTO
Labels: documentation, maintenance

#6784 Move useless warnings to information
  src/gmt_plot.c
Labels: maintenance

#6783 Update App M figures on DVC
  doc/scripts/GMT_App_M_1c.sh
  doc/scripts/images.dvc
Labels: documentation

#6785 Fix CMYK issue
  src/gmt_init.c
  src/gmt_support.c
Labels: bug

#6782 Add workflow for uploading baseline images as a release asset
  .github/release-drafter.yml
  .github/workflows/release-baseline-images.yml
Labels: maintenance

#6787 The +v modifier for -JO was not parse for -JOC
  src/gmt_init.c
Labels: bug

#6795 Fix wrong column selections in rotsmoother
  doc/rst/source/supplements/spotter/rotsmoother.rst
  src/spotter/rotsmoother.c
Labels: bug

#6798 Let surface -Vi report unusable points
  src/surface.c
Labels: maintenance

#6809 Address a few grdflexure issues
  doc/rst/source/supplements/potential/grdflexure.rst
  src/gmt_grdio.c
  src/gmt_prototypes.h
  src/grdfft.c
  src/grdvector.c
  src/potential/gravfft.c
  src/potential/grdflexure.c
  src/potential/grdgravmag3d.c
Labels: bug, documentation, enhancement

#6813 Fix harmless issues in movie
  doc/rst/source/movie.rst
  src/movie.c
Labels: documentation, maintenance

#6822 Add missing docs for options in gmtgravmag3d
  doc/rst/source/supplements/potential/gmtgravmag3d.rst
  src/potential/gmtgravmag3d.c
Labels: documentation

#6823 Update gshhg man page
  doc/rst/source/supplements/gshhg/gshhg.rst
Labels: documentation

#6826 Fix sign error in FAA slab correction
  doc/rst/source/explain_fft.rst_
  doc/rst/source/grdfft.rst
  doc/rst/source/supplements/potential/gravfft.rst
  doc/rst/source/supplements/potential/grdflexure.rst
  src/gmt_api.c
  src/gmt_private.h
  src/potential/gravfft.c
Labels: bug

#6829 Let gravprisms handle interfaces
  doc/rst/source/supplements/potential/gravprisms.rst
  src/potential/gravprisms.c
Labels: documentation, enhancement

#6830 Reset -B machinery when colorbar is called in one-liners
  src/gmt_init.c
Labels: bug

#6837 Allow gravprisms -Drho to be used with -H for density contrasts
  doc/rst/source/supplements/potential/gravprisms.rst
  src/potential/gravprisms.c
Labels: enhancement
