Repository GenericMappingTools/gmt, pull requests merged in 2022-04, with the labels that each got.

#6510 Update GMT install instructions via conda-forge
  INSTALL.md
Labels: documentation

#6512 Add links from -T to cookbook section
  doc/rst/source/explain_-T_rose.rst_
Labels: documentation

#6515 Add revised 2014 x2sys paper via ResearchGate URL
  doc/rst/source/supplements/x2sys/x2sys_binlist.rst
  doc/rst/source/supplements/x2sys/x2sys_cross.rst
  doc/rst/source/supplements/x2sys/x2sys_datalist.rst
  doc/rst/source/supplements/x2sys/x2sys_get.rst
  doc/rst/source/supplements/x2sys/x2sys_init.rst
  doc/rst/source/supplements/x2sys/x2sys_list.rst
  doc/rst/source/supplements/x2sys/x2sys_merge.rst
  doc/rst/source/supplements/x2sys/x2sys_put.rst
  doc/rst/source/supplements/x2sys/x2sys_refs.rst_
  doc/rst/source/supplements/x2sys/x2sys_report.rst
  doc/rst/source/supplements/x2sys/x2sys_solve.rst
Labels: documentation

#6519 Fix failing tests
  doc/examples/images.dvc
  test/psxy/clip_ellipse.sh
Labels: maintenance

#6520 Allow use of GMT_GRAPHICS_FORMAT for one-liners
  doc/rst/source/begin.rst
  doc/scripts/GMT_-B_slanted.sh
  doc/scripts/GMT_-U.sh
  doc/scripts/GMT_TM.sh
  doc/scripts/GMT_az_equidistant.sh
  doc/scripts/GMT_cassini.sh
  doc/scripts/GMT_coverlogo.sh
  doc/scripts/GMT_eckert4.sh
  doc/scripts/GMT_equi_cyl.sh
  doc/scripts/GMT_general_cyl.sh
  doc/scripts/GMT_gnomonic.sh
  doc/scripts/GMT_grinten.sh
  doc/scripts/GMT_hammer.sh
  doc/scripts/GMT_lambert_az_hemi.sh
  doc/scripts/GMT_miller.sh
  doc/scripts/GMT_mollweide.sh
  doc/scripts/GMT_orthographic.sh
  doc/scripts/GMT_perspective.sh
  doc/scripts/GMT_polyconic.sh
  doc/scripts/GMT_robinson.sh
  doc/scripts/GMT_sinusoidal.sh
  doc/scripts/GMT_stereographic_polar.sh
  doc/scripts/GMT_transverse_merc.sh
  doc/scripts/GMT_winkel.sh
  src/gmt_api.c
  src/gmt_init.c
Labels: enhancement, add-changelog

#6514 Address mixup related to time in x2sys_datalist
  src/gmt_memory.c
  src/gmt_support.c
  src/x2sys/x2sys.c
Labels: bug

#6522 Allow contour files to only list contour level
  doc/rst/source/contour.rst
  doc/rst/source/grdcontour.rst
  src/gmt_support.c
  src/grdcontour.c
  src/pscontour.c
Labels: enhancement

#6523 Improve clip path for images in -Qi
  src/grdview.c
Labels: bug

#6526 Support using GMT_GRAPHICS_FORMAT through view format in movie -M
  doc/scripts/GMT_movie_progress.sh
  doc/scripts/psevents_action.sh
  src/movie.c
Labels: enhancement

#6524 Remove Vercel continuous deployment
  CMakeLists.txt
  ci/vercel-docs.sh
  package.json
  vercel.json
Labels: maintenance

#6527 Simplify GMT_RGBchart.sh by only producing tabloid size in modern mode
  doc/rst/source/gmtcolors.rst
  doc/scripts/CMakeLists.txt
  doc/scripts/GMT_RGBchart.sh
  doc/scripts/images.dvc
Labels: documentation

#6532 Separate calculations from verbosity in pshistogram
  src/pshistogram.c
Labels: bug

#6535 Address bug in NORM operators
  doc/rst/gmtmath.rst
  doc/rst/grdmath.rst
  src/gmtmath.c
  src/grdmath.c
Labels: bug

#6536 Fix -R parsing check for geographic data
  src/gmt_init.c
Labels: bug

#6540 Attempt to improve error catching for junk input
  src/gmt_io.c
Labels: bug

#6539 Fix regression in parsing of -W in block[mean|median|mode]
  src/block_subs.h
  src/blockmean.c
  src/blockmedian.c
  src/blockmode.c
Labels: bug

#6542 Fix documentation and parsing of -W (again) for block modules
  doc/rst/source/blockmean.rst
  doc/rst/source/blockmedian.rst
  doc/rst/source/blockmode.rst
  src/block_subs.h
  src/blockmean.c
  src/blockmedian.c
  src/blockmode.c
Labels: bug, documentation

#6547 Fix error in setting max half-width in node search
  src/gmt_support.c
Labels: bug

#6548 Add landslide option -S for grdseamount
  doc/rst/source/supplements/potential/gmtgravmag3d.rst
  doc/rst/source/supplements/potential/grdgravmag3d.rst
  doc/rst/source/supplements/potential/grdseamount.rst
  doc/scripts/GMT_seamount_azim.sh
  doc/scripts/GMT_seamount_cum_inc.sh
  doc/scripts/GMT_seamount_flux.sh
  doc/scripts/GMT_seamount_psi.sh
  doc/scripts/GMT_seamount_slide.sh
  doc/scripts/GMT_seamount_specs.sh
  doc/scripts/GMT_seamount_types.sh
  doc/scripts/GMT_seamount_u0.sh
  doc/scripts/images.dvc
  src/potential/grdseamount.c
  test/baseline/potential.dvc
Labels: bug, documentation, new feature, enhancement

#6533 Include PS images for docs in releases
  doc/examples/CMakeLists.txt
  doc/scripts/CMakeLists.txt
Labels: maintenance

#6552 Check that decorated line symbol is valid
  doc/rst/source/explain_symbols.rst_
  src/gmt_constants.h
  src/gmt_support.c
Labels: bug, documentation

#6553 Three things on a lazy Thursday
  src/gmt_api.c
  src/gmt_init.c
  src/gmt_plot.c
  src/gmt_support.c
  src/grdcontour.c
Labels: bug

#6555 Just keep all testapi*.c with same prefix
  src/testapi_conv.c
  test/api/apiconv.sh
Labels: maintenance

#6554 Document the slop for fixed points in quoted or decorated lines
  doc/rst/source/explain_symbols.rst_
Labels: documentation

#6556 Strenghten parsing and error reporting for block modules
  src/blockmean.c
  src/blockmedian.c
  src/blockmode.c
Labels: maintenance

#6560 Pass -N to grdtrack from within grdinterpolate
  src/grdinterpolate.c
Labels: bug

#6559 Update App O text
  doc/rst/source/cookbook/contour-annotations.rst
Labels: documentation

#6558 Streamline parsing of required arguments
  src/batch.c
  src/blockmean.c
  src/blockmedian.c
  src/blockmode.c
  src/dimfilter.c
  src/filter1d.c
  src/gmt_prototypes.h
  src/gmt_support.c
Labels: maintenance

#6561 Fix incorrect auto-offset for centered roses
  src/gmt_plot.c
  test/baseline/psbasemap.dvc
Labels: bug

#6563 Improve macro checking if option given more than once
  src/gmt_error.h
  src/gmtmath.c
  src/grdcontour.c
  src/greenspline.c
  src/movie.c
  src/potential/gmtflexure.c
  src/pscontour.c
  src/psconvert.c
  src/pshistogram.c
  src/psrose.c
  src/pstext.c
  src/segy/pssegyz.c
  src/segy/segy2grd.c
  src/seis/psmeca.c
Labels: maintenance

#6565 More parse hardening
  src/blockmean.c
  src/blockmedian.c
  src/blockmode.c
  src/gmt2kml.c
  src/gmtconvert.c
  src/gmtget.c
  src/gmtinfo.c
  src/gmtlogo.c
  src/gmtmath.c
  src/gmtregress.c
  src/gmtset.c
  src/gmtspatial.c
  src/gmtsplit.c
  src/gmtvector.c
  src/gmtwhich.c
  src/pscoast.c
  src/pscontour.c
  src/psevents.c
  src/psscale.c
Labels: maintenance

#6575 Improve parsers in seis supplement
  src/seis/pscoupe.c
  src/seis/psmeca.c
  src/seis/pspolar.c
  src/seis/pssac.c
Labels: maintenance

#6569 IMprove parsing for geodesy supplement
  src/geodesy/gpsgridder.c
  src/geodesy/psvelo.c
Labels: maintenance

#6578 Improve parsing in x2sys supplement
  src/gmt_prototypes.h
  src/gmt_support.c
  src/x2sys/x2sys_binlist.c
  src/x2sys/x2sys_cross.c
  src/x2sys/x2sys_datalist.c
  src/x2sys/x2sys_get.c
  src/x2sys/x2sys_init.c
  src/x2sys/x2sys_list.c
  src/x2sys/x2sys_merge.c
  src/x2sys/x2sys_put.c
  src/x2sys/x2sys_report.c
  src/x2sys/x2sys_solve.c
Labels: maintenance

#6579 Improved parsing checks for single-char arguments
  src/filter1d.c
  src/gmt_prototypes.h
  src/gmt_support.c
  src/gmtdefaults.c
  src/gmtselect.c
  src/gmtset.c
  src/grd2kml.c
  src/grdfilter.c
  src/grdlandmask.c
  src/grdmath.c
  src/grdproject.c
  src/grdvolume.c
  src/mapproject.c
  src/mgd77/mgd77manage.c
  src/potential/grdseamount.c
  src/seis/pscoupe.c
  src/sph2grd.c
  src/spotter/backtracker.c
Labels: maintenance

#6566 Parse improvement for grd modules
  src/grd2cpt.c
  src/grd2kml.c
  src/grdblend.c
  src/grdclip.c
  src/grdconvert.c
  src/grdcut.c
  src/grdedit.c
  src/grdfft.c
  src/grdfill.c
  src/grdfilter.c
  src/grdgdal.c
  src/grdgradient.c
  src/grdhisteq.c
  src/grdimage.c
  src/grdinfo.c
  src/grdinterpolate.c
  src/grdlandmask.c
  src/grdmask.c
  src/grdmath.c
  src/grdmix.c
  src/grdpaste.c
  src/grdproject.c
  src/grdsample.c
  src/grdtrack.c
  src/grdtrend.c
  src/grdvector.c
  src/grdview.c
  src/grdvolume.c
Labels: maintenance

#6568 Improve parsing for gshhg supplement
  src/gshhg/gshhg.c
Labels: maintenance

#6571 Improve parsing in img supplement
  src/img/img2grd.c
Labels: maintenance

#6572 Improve mgd77 supplement parsing
  src/mgd77/mgd77convert.c
  src/mgd77/mgd77header.c
  src/mgd77/mgd77list.c
  src/mgd77/mgd77manage.c
  src/mgd77/mgd77path.c
  src/mgd77/mgd77track.c
Labels: maintenance

#6573 Improve parsing for potential supplement
  src/potential/gmtflexure.c
  src/potential/gmtgravmag3d.c
  src/potential/gravfft.c
  src/potential/gravprisms.c
  src/potential/grdflexure.c
  src/potential/grdgravmag3d.c
  src/potential/grdredpol.c
  src/potential/grdseamount.c
  src/potential/talwani2d.c
  src/potential/talwani3d.c
Labels: maintenance

#6574 Improve parsing for segy supplement
  src/segy/pssegy.c
  src/segy/pssegyz.c
  src/segy/segy2grd.c
Labels: maintenance

#6576 Improve parsing in the spotter supplement
  src/spotter/backtracker.c
  src/spotter/gmtpmodeler.c
  src/spotter/grdpmodeler.c
  src/spotter/grdrotater.c
  src/spotter/grdspotter.c
  src/spotter/hotspotter.c
  src/spotter/originater.c
  src/spotter/polespotter.c
  src/spotter/rotconverter.c
  src/spotter/rotsmoother.c
Labels: maintenance

#6580 Address minor lapses due to parser updates
  doc/rst/source/supplements/x2sys/x2sys_init.rst
  src/grdproject.c
  src/mapproject.c
  src/seis/pssac.c
  src/x2sys/x2sys_init.c
Labels: documentation, maintenance

#6581 More cleanup
  src/movie.c
  src/potential/grdflexure.c
Labels: bug

#6582 Parsing improvements for modules I left behind
  src/gmtbinstats.c
  src/gmtconnect.c
  src/gmtconvert.c
  src/gmtinfo.c
  src/gmtsimplify.c
  src/gmtspatial.c
  src/gmtsplit.c
  src/grd2cpt.c
  src/grdcontour.c
  src/grdedit.c
  src/grdhisteq.c
  src/grdselect.c
  src/grdview.c
  src/greenspline.c
  src/img/img2grd.c
  src/makecpt.c
  src/potential/gravprisms.c
  src/potential/grdseamount.c
  src/potential/talwani3d.c
  src/psclip.c
  src/psconvert.c
  src/psevents.c
  src/pshistogram.c
  src/psimage.c
  src/pslegend.c
  src/psmask.c
  src/psrose.c
  src/pssolar.c
  src/psternary.c
  src/pstext.c
  src/pswiggle.c
  src/psxy.c
  src/psxyz.c
  src/sphinterpolate.c
  src/sphtriangulate.c
  src/spotter/grdspotter.c
  src/spotter/hotspotter.c
  src/spotter/polespotter.c
  src/triangulate.c
  src/xyz2grd.c
Labels: maintenance

#6586 Many modules did not use new function for parsing input
  src/gmt2kml.c
  src/grd2kml.c
  src/grdblend.c
  src/grdclip.c
  src/grdconvert.c
  src/grdinterpolate.c
  src/potential/grdflexure.c
  src/potential/grdredpol.c
  src/xyz2grd.c
Labels: maintenance

#6593 Allow grdinterpolate to default to all layers if -T is not given
  doc/rst/source/grdinterpolate.rst
  src/grdinfo.c
  src/grdinterpolate.c
Labels: enhancement

#6596 Make sure we check for netCDF before testing for cube
  src/grdinfo.c
Labels: bug

#6600 Add kustom symbol name check
  src/gmt_internals.h
  src/gmt_support.c
Labels: bug, maintenance

#6603 Passed wrong family in testapi_matrix.c
  src/testapi_matrix.c
Labels: bug

#6604 Fix KEYS for rose -I
  src/psrose.c
Labels: bug

#6607 Add more debug output in gmt_access
  src/gmt_io.c
  src/gmt_remote.c
  src/gmtmath.c
Labels: maintenance

#6608 Use static instead of GMT_LOCAL
  src/block_subs.h
  src/psevents.c
Labels: bug

#6613 Clarify what "oblique" means
  doc/rst/source/gmt.conf.rst
Labels: documentation

#6615 set correct dimension when finding 3- or 4-D array
  src/gmt_nc.c
Labels: bug

#6619 Fix new bug in dimfilter -N parsin
  src/dimfilter.c
Labels: bug

#6620 Improve detection of cubes
  src/gmt_private.h
  src/grdinfo.c
Labels: bug

#6616 Better check when a column is used for both coordinates and dimension
  src/gmt_io.c
  src/gmt_prototypes.h
  src/psxy.c
  src/psxyz.c
  test/baseline/psxy.dvc
  test/psxy/use_x_and_symbol_col.sh
Labels: bug

#6625 gmt --show-library gave NULL in Xcode
  src/gmt_api.c
Labels: maintenance

#6627 Handle the combination -E -Sn in blockmean
  src/blockmean.c
Labels: bug

#6628 Fix regression in gmtsplit
  doc/rst/source/gmtsplit.rst
  src/gmtsplit.c
Labels: bug, documentation

#6626 Must check for label content before offsetting
  src/gmt_plot.c
  src/gmt_symbol.h
Labels: bug

#6629 Prevent both -D and -> at the same time in gmtconvert
  src/gmtconvert.c
Labels: maintenance

#6630 Better handling of output file in gmt math
  src/gmtmath.c
Labels: maintenance

#6631 Update mag_roses.ps baseline
  test/baseline/psbasemap.dvc
Labels: maintenance

#6634 Cleaning up some docs
  doc/rst/source/cookbook/non-unix-platforms.rst
  doc/rst/source/cookbook/preface.rst
  doc/rst/source/gmt.conf.rst
  src/shit.grd
Labels: documentation

#6635 Simplify check for cubes
  src/grdinfo.c
Labels: bug

#6636 Like grdinfo, let grdselect work without -Q option
  doc/rst/source/grdselect.rst
  src/grdselect.c
Labels: enhancement

#6638 Check that spectrum1d -Ssize does not exceed data length
  src/spectrum1d.c
Labels: documentation, maintenance

#6642 Do not call psbasemap from ternary if no -B settings
  src/psternary.c
Labels: bug

#6644 Enhance legend -M scenarios
  doc/rst/source/legend.rst
  src/pslegend.c
  test/baseline/pslegend.dvc
  test/pslegend/mixlegend.sh
Labels: documentation, enhancement

#6645 Fix surface -L bug
  src/surface.c
  test/baseline/surface.dvc
  test/surface/limits.sh
Labels: bug
