Repository GenericMappingTools/gmt, pull requests merged in 2022-07, with the labels that each got.

#6844 Improve subplot setting of -X -Y
  src/subplot.c
Labels: bug

#6824 Allow MAP_FRAME_TYPE=graph-origin
  doc/rst/source/gmt.conf.rst
  doc/scripts/GMT_map_frame_type.sh
  src/gmt_defaults.h
  src/gmt_init.c
  src/gmt_plot.c
Labels: documentation, enhancement

#6843 test -Z min/max for min < max
  src/grdcut.c
Labels: maintenance

#6848 Better documentation of long-option translation
  src/gmt_common_longoptions.h
  src/gmt_init.c
Labels: documentation

#6854 Adding missing 'title' long option modifier.
  src/gmt_common_longoptions.h
Labels: bug

#6856 meca -A+ssize passed wrong pointer to gmt_M_to_inch
  src/seis/psmeca.c
Labels: bug

#6875 Add +b modifier to gravprism -H
  doc/rst/source/supplements/potential/gravprisms.rst
  src/potential/gravprisms.c
Labels: enhancement

#6877 Update 4 PS files following subtle gs 9.56 change
  doc/scripts/images.dvc
  test/baseline/grdcontour.dvc
  test/baseline/pscoast.dvc
  test/baseline/pstext.dvc
Labels: maintenance

#6886 Retain same output with -V in surface
  src/surface.c
Labels: maintenance

#6888 Fix glitches in synopsis
  doc/rst/source/dimfilter.rst
  src/begin.c
  src/dimfilter.c
  src/geodesy/gpsgridder.c
  src/gmt2kml.c
  src/gmt_api.c
  src/gmt_synopsis.h
  src/grdgdal.c
  src/grdimage.c
  src/grdinterpolate.c
  src/grdmask.c
  src/grdmath.c
  src/grdtrack.c
  src/greenspline.c
  src/mapproject.c
  src/mgd77/mgd77magref.c
  src/potential/gmtgravmag3d.c
  src/potential/grdflexure.c
  src/potential/grdseamount.c
  src/potential/talwani2d.c
  src/pscontour.c
  src/psconvert.c
  src/psevents.c
  src/psmask.c
  src/psternary.c
  src/segy/segy2grd.c
  src/spotter/grdpmodeler.c
  src/spotter/hotspotter.c
  src/spotter/polespotter.c
  src/surface.c
  src/x2sys/x2sys_init.c
Labels: documentation, maintenance

#6890 Add legend symbol for confidence lines
  src/gmt_init.c
  src/gmt_prototypes.h
  src/grdcontour.c
  src/grdvector.c
  src/pscontour.c
  src/pshistogram.c
  src/pslegend.c
  src/psxy.c
  src/psxyz.c
Labels: enhancement

#6893 Add missing +d case to exceptions
  src/gmt_support.c
Labels: bug, maintenance

#6878 Remove one deprecated example in grdimage manpage
  doc/rst/source/grdimage.rst
Labels: documentation

#6891 Let grd2cpt and grd2kml not care about remote registration
  src/gmt_init.c
Labels: maintenance

#6900 Fix #6891 to just not fuss but stick with gridline registration
  src/gmt_init.c
  src/gmt_private.h
  src/gmt_remote.c
Labels: bug

#6903 Tolerate round-off in z-array
  src/grdinterpolate.c
Labels: maintenance

#6904 Fix autoscaling -JX for double negatives
  src/gmt_map.c
  test/baseline/psbasemap.dvc
  test/psbasemap/autoscale.sh
Labels: bug

#6907 Use the org-wide code of conduct
  .github/config.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  doc/rst/source/devdocs/contributing.rst
  doc/rst/source/index.rst
Labels: maintenance

#6914 Must erase any input grid CPT in grdmath
  src/gmt_nc.c
  src/gmt_private.h
  src/grdmath.c
Labels: bug

#6916 Let grdmath control what happens to grid CPT settings
  doc/rst/source/grdmath.rst
  src/grdmath.c
Labels: enhancement

#6921 Update images to show GDAL is required
  doc/fig/GMT5_external.png
  doc/fig/GMT5_mode.png
Labels: documentation

#6922 Incorrect comparison in gmt_grd_domains_match function
  src/gmt_grdio.c
Labels: bug

#6923 Set mask to true when -A is set in grdseamounts
  src/potential/grdseamount.c
Labels: bug
