Repository GenericMappingTools/gmt, pull requests merged in 2022-09, with the labels that each got.

#7013 Update gmtsimplify.rst
  doc/rst/source/gmtsimplify.rst
Labels: documentation

#7014 Replace SPLITXYZ text with GMTSPLIT
  src/gmtsplit.c
Labels: maintenance

#7019 Let -Fx write hex CPT tables
  doc/rst/source/grd2cpt.rst
  doc/rst/source/makecpt.rst
  src/gmt_enum_dict.h
  src/gmt_init.c
  src/gmt_prototypes.h
  src/gmt_resources.h
  src/gmt_support.c
  src/grd2cpt.c
  src/makecpt.c
Labels: enhancement

#7024 Update modules-classic.rst
  doc/rst/source/modules-classic.rst
Labels: documentation

#7026 See if we can trick the CI Win compiler
  src/gmt_support.c
Labels: maintenance

#7029 Ensure input has enough columns for psxy -L
  src/psxy.c
Labels: maintenance

#7030 Same -L fix for psxyz plus message fix
  src/psxy.c
  src/psxyz.c
Labels: maintenance

#7035 Allow setting both pen and fill separately
  src/seis/pspolar.c
Labels: bug

#7025 Clarify items for bars should be sorted
  doc/rst/source/explain_symbols.rst_
Labels: documentation

#7037 Ensure we understand the mode shift in gmt.c
  src/gmt.c
  src/gmt_api.c
  src/gmt_enum_dict.h
  src/gmt_resources.h
Labels: maintenance

#7040 Further utilize gmt_M_repeated_module_option in module parsers
  src/batch.c
  src/gmt2kml.c
  src/gmtselect.c
  src/grd2xyz.c
  src/grdlandmask.c
  src/mgd77/mgd77convert.c
  src/mgd77/mgd77path.c
  src/movie.c
  src/potential/gravfft.c
  src/psmask.c
  src/psrose.c
  src/psscale.c
  src/pstext.c
  src/pswiggle.c
  src/seis/pscoupe.c
  src/seis/psmeca.c
  src/seis/pspolar.c
  src/spotter/grdrotater.c
  src/xyz2grd.c
Labels: maintenance

#7041 Modify spectrum1d -L parsing to allow better checks
  src/spectrum1d.c
Labels: maintenance
