Repository GenericMappingTools/gmt, pull requests merged in 2022-03, with the labels that each got.

#6405 Allow repeated -L option for grdinfo
  src/grdinfo.c
Labels: bug

#6404 Disallow grdhisteq -C -N
  doc/rst/source/grdhisteq.rst
  src/grdhisteq.c
Labels: bug

#6407 Only deny -O -K in modern mode if a PS-producing module
  src/gmt_init.c
Labels: maintenance

#6410 Allow grdfill to output unchanged grid if no holes
  doc/rst/source/grdfill.rst
  src/grdfill.c
Labels: maintenance

#6425 Fix grdfilter -Ff|o
  src/grdfilter.c
Labels: bug

#6427 Let one-liners with CPTs add colorbar
  doc/rst/source/cookbook/one-liner.rst
  src/gmt_api.c
  src/gmt_init.c
Labels: enhancement

#6428 Complement inverse radian trig functions with degrees
  doc/rst/source/gmtmath.rst
  doc/rst/source/grdmath.rst
  src/gmtmath.c
  src/grdmath.c
Labels: enhancement

#6429 Check that altitude is not inside Earth
  src/gmt_init.c
  src/gmt_proj.c
Labels: bug

#6431 Fix how variable rho abd rho = NaN is handled in gravfft
  doc/rst/source/supplements/potential/gravfft.rst
  src/potential/gravfft.c
Labels: enhancement

#6437 Minor cleaning up in talwani modules
  src/potential/talwani2d.c
  src/potential/talwani3d.c
Labels: maintenance

#6441 More fixing and improvements in talwani?d
  doc/rst/source/supplements/potential/talwani2d.rst
  doc/rst/source/supplements/potential/talwani3d.rst
  src/potential/talwani2d.c
  src/potential/talwani3d.c
  test/potential/cyltest.sh
  test/potential/sphtest.sh
Labels: maintenance

#6451 Remove strict check for repeatable seis options
  src/seis/pscoupe.c
  src/seis/psmeca.c
  src/seis/pspolar.c
Labels: bug

#6452 Update gravprisms.rst
  doc/rst/source/supplements/potential/gravprisms.rst
Labels: documentation

#6454 Retire old -W -K and let -D handle inputs and -W output
  doc/rst/source/supplements/potential/gravprisms.rst
  doc/scripts/GMT_seamount_prisms.sh
  src/potential/gravprisms.c
Labels: documentation

#6455 Ensure plot and plot3d uses rect in legend for -L
  src/psxy.c
  src/psxyz.c
Labels: bug

#6459 Increase GRAPHICSMAGICK limit for GMT_grinten.sh
  doc/scripts/GMT_grinten.sh
Labels: maintenance

#6460 Introduce newton.h in potential to define big G
  src/potential/CMakeLists.txt
  src/potential/gravfft.c
  src/potential/gravprisms.c
  src/potential/grdgravmag3d.c
  src/potential/newton.h
  src/potential/talwani.h
  src/potential/talwani2d.c
  src/potential/talwani3d.c
Labels: maintenance

#6458 Download remote files for test scripts to the cache dir
  doc/examples/ex43/ex43.sh
  test/geodesy/case_largeR_noW.sh
  test/geodesy/case_largeR_withW.sh
  test/geodesy/case_smallR_noW.sh
  test/geodesy/case_smallR_withW.sh
  test/gmtregress/regress_1.sh
  test/gmtregress/regress_2.sh
  test/gmtspatial/nn.sh
  test/gmtspatial/poldecimate.sh
  test/grdmask/maskmode.sh
  test/greenspline/gspline_5.sh
  test/mapproject/waypoints.sh
  test/mgd77/cm4.sh
  test/potential/cyltest.sh
  test/pshistogram/mmm.sh
  test/psrose/vectors.sh
  test/psxy/categorical.sh
  test/psxy/gallo.sh
  test/sph/sph_5.sh
  test/spotter/spotter_03.sh
Labels: maintenance

#6466 Fix the lack of precision in -Ib
  src/gmt_grdio.c
  src/gmt_prototypes.h
  src/grdinfo.c
  test/grdinfo/perimeters.sh
Labels: bug

#6471 Let oneliner plot colorbar used default justification
  src/gmt_init.c
Labels: maintenance

#6475 Update baseline images for SRTM15+ v2.4
  doc/examples/images.dvc
  doc/scripts/images.dvc
  test/baseline/api.dvc
  test/baseline/genper.dvc
  test/baseline/grd2cpt.dvc
  test/baseline/grdcontour.dvc
  test/baseline/grdfill.dvc
  test/baseline/grdfilter.dvc
  test/baseline/grdimage.dvc
  test/baseline/grdview.dvc
  test/baseline/modern.dvc
  test/baseline/potential.dvc
Labels: maintenance

#6476 Let grdseamount -Co handle u = -1
  src/potential/grdseamount.c
Labels: maintenance

#6474 Add -Wo to mapproject for oblique domain in degrees
  doc/rst/source/mapproject.rst
  src/mapproject.c
Labels: enhancement, add-changelog

#6418 Pass GMT_GRID_NEEDS_PAD1 flag to GMT_Read_Data in grdfill
  src/grdfill.c
Labels: bug

#6479 Return with error if libcurl fails
  src/gmt_remote.c
Labels: bug

#6480 Ensure -fg is internally set for output if geo grids are read
  src/grdselect.c
Labels: maintenance

#6481 Add link to -T array generation in movie docs
  doc/rst/source/events.rst
  doc/rst/source/movie.rst
  doc/rst/source/psevents.rst
Labels: documentation

#6482 grdsample aliasing message failed to account for numerical noise
  src/grdsample.c
Labels: maintenance

#6484 Add http urls for refs
  doc/rst/source/dimfilter.rst
  doc/rst/source/grdvolume.rst
  doc/rst/source/greenspline.rst
  doc/rst/source/sph2grd.rst
  doc/rst/source/supplements/gshhg/gshhg.rst
  doc/rst/source/supplements/mgd77/mgd77convert.rst
  doc/rst/source/supplements/mgd77/mgd77header.rst
  doc/rst/source/supplements/mgd77/mgd77info.rst
  doc/rst/source/supplements/mgd77/mgd77list.rst
  doc/rst/source/supplements/mgd77/mgd77manage.rst
  doc/rst/source/supplements/mgd77/mgd77path.rst
  doc/rst/source/supplements/mgd77/mgd77sniffer.rst
  doc/rst/source/supplements/mgd77/mgd77track.rst
  doc/rst/source/supplements/spotter/backtracker.rst
  doc/rst/source/supplements/spotter/grdspotter.rst
  doc/rst/source/supplements/spotter/hotspotter.rst
  doc/rst/source/supplements/x2sys/x2sys_cross.rst
  doc/rst/source/surface.rst
Labels: documentation

#6485 Consider grid dimension names when selecting default map dimension
  src/gmt_common.h
  src/gmt_init.c
Labels: enhancement

#6486 Check if mode is suitable for grid in grdfilter
  src/grdfilter.c
Labels: maintenance

#6488 Fix use of data offset when grdpaste reads grids
  src/gmt_grdio.c
  src/gmt_nc.c
Labels: bug

#6489 Only fixed one of two lines in previous movie PR
  src/movie.c
Labels: bug

#6490 Remove the restriction in grdpaste on same scale/offset
  src/grdpaste.c
Labels: maintenance

#6493 Add option to get Git commit information through C API
  src/gmt_api.c
Labels: enhancement

#6496 Let grdview -N level default to minimum value
  doc/rst/source/grdview.rst
  src/grdview.c
Labels: enhancement

#6503 Let GMT timestamp via -U be placed at the end of the plot
  src/gmt_plot.c
Labels: maintenance

#6502 Include "gmt" when reporting command-line in histories
  src/gmt_api.c
  src/gmt_grdio.c
  src/shit.grd
Labels: maintenance

#6504 Let psimage use the GMT default dpi if not specified
  doc/rst/source/image.rst
  src/psimage.c
Labels: enhancement

#6492 Fix event -E parsing and add animation to documentation
  doc/rst/source/events.rst
  doc/scripts/images.dvc
  doc/scripts/psevents_action.sh
  src/psevents.c
Labels: bug, documentation

#6506 Ensure one-liner reverts to 2-D before colorbar
  src/gmt_init.c
Labels: bug

#6509 Improve histogram handling of time units via -T
  doc/rst/source/histogram.rst
  src/gmt_prototypes.h
  src/gmt_support.c
  src/pshistogram.c
Labels: bug
