Repository GenericMappingTools/gmt, pull requests merged in 2022-11, with the labels that each got.

#7072 Let box-and-whisker symbols take separate width and cap
  doc/rst/source/plot.rst
  doc/rst/source/psxy.rst
  src/psxy.c
Labels: enhancement

#7073 Update expected columns in greenspline when reading gradient file
  src/greenspline.c
Labels: bug

#7076 Bug in SCM-to-gmt script left gap between 1 and 3
  admin/build-scientific-colors-cpt.sh
  share/cpt/SCM/actonS.cpt
  share/cpt/SCM/bamakoS.cpt
  share/cpt/SCM/batlowS.cpt
  share/cpt/SCM/bilbaoS.cpt
  share/cpt/SCM/budaS.cpt
  share/cpt/SCM/davosS.cpt
  share/cpt/SCM/devonS.cpt
  share/cpt/SCM/grayCS.cpt
  share/cpt/SCM/hawaiiS.cpt
  share/cpt/SCM/imolaS.cpt
  share/cpt/SCM/lajollaS.cpt
  share/cpt/SCM/lapazS.cpt
  share/cpt/SCM/nuukS.cpt
  share/cpt/SCM/osloS.cpt
  share/cpt/SCM/tokyoS.cpt
  share/cpt/SCM/turkuS.cpt
Labels: bug

#7083 Clarify that -E and -N work on different subsets
  doc/rst/source/gmtconvert.rst
Labels: documentation

#7082 Need periodic check on x for periodic geo custom labels
  src/gmt_support.c
Labels: bug

#7084 Flawed V4 check needed a restructuring
  src/gmt_init.c
Labels: bug

#7093 Enclose filenames given to gdal_translate with quotes
  src/grdcut.c
Labels: bug

#7089 Check that a custom shared library given has extension
  src/gmt_api.c
Labels: enhancement

#7095 Use signed integers when measuring pad offsets
  src/surface.c
Labels: maintenance

#7096 Update psconvert to handle gs version 10
  src/psconvert.c
Labels: bug

#7100 Accessed freed memory in grdselect
  src/grdselect.c
Labels: bug

#7099 Improve modern onliner graphic check
  src/gmt_api.c
  src/gmt_gsformats.h
Labels: enhancement, maintenance

#7105 Add more careful checks for malformed oneliner use
  src/gmt_api.c
Labels: enhancement

#7108 Allow single offset in -U
  src/gmt_init.c
Labels: bug

#7110 Fix minor issues for memory debug
  cmake/ConfigUserAdvancedTemplate.cmake
  src/gmt_memory.c
Labels: maintenance

#7111 Check if argument follows possible one-liner format
  src/gmt_api.c
Labels: bug

#7114 Ensure modern mode does not create compatibiltiy level 4
  src/gmt_init.c
Labels: bug

#7113 Update gmtmath.rst
  doc/rst/source/gmtmath.rst
Labels: documentation

#7117 Do not turn on polygon flag when -L args are given
  src/psxy.c
  src/psxyz.c
Labels: bug

#7118 Ensure grdrotator uses -F to select grid region
  doc/rst/source/supplements/spotter/grdrotater.rst
  src/spotter/grdrotater.c
Labels: bug

#7119 Check if rotated nodes are outside rotated polygon
  src/spotter/grdrotater.c
Labels: bug

#7121 Attempt to fix coast holes in Canada for some -A settings
  src/gmt_shore.c
Labels: bug
