Repository GenericMappingTools/gmt, pull requests merged in 2022-02, with the labels that each got.

#6289 Enhanced node determination in grdmask for polygon input
  doc/rst/source/grdmask.rst
  src/grdmask.c
  test/grdmask/maskmode.sh
Labels: add-changelog, new core module feature

#6290 Allow plot and plot3d -Sl to plot angled text symbol
  doc/rst/source/explain_symbols.rst_
  src/gmt_init.c
  src/gmt_plot.h
  src/psxy.c
  src/psxyz.c
  test/psxy/angled_text.sh
  test/psxyz/angled_text.sh
Labels: bug, enhancement, add-changelog

#6282 Allow plot/plot3d -SE, -SJ, -SW options to parse appended map units
  doc/rst/source/explain_symbols.rst_
  src/gmt_init.c
  src/gmt_plot.h
  src/psxy.c
  src/psxyz.c
  test/psxy/map_units.sh
  test/psxyz/map_units.sh
Labels: documentation, enhancement, add-changelog

#6215 Proper positional adjustment of directional rose due to labels
  doc/examples/ex04/ex04.bat
  doc/examples/ex04/ex04.sh
  doc/rst/source/cookbook/features.rst
  doc/rst/source/explain_-T_rose.rst_
  doc/rst/source/gmt.conf.rst
  doc/rst/source/theme-settings.rst
  doc/scripts/GMT_App_K_3.sh
  doc/scripts/GMT_dir_rose.sh
  doc/scripts/GMT_mag_rose.sh
  doc/scripts/GMT_obl_baja.sh
  doc/scripts/GMT_obl_merc.sh
  doc/scripts/GMT_obl_nz.sh
  src/gmt_defaults.h
  src/gmt_init.c
  src/gmt_keywords.txt
  src/gmt_plot.c
  src/gmt_support.c
  src/gmt_symbol.h
  src/gmt_synopsis.h
  test/gmtmex/WL_example_3.sh
  test/psbasemap/JOb_pole.sh
  test/psbasemap/dir_roses.sh
  test/psbasemap/mag_roses.sh
Labels: bug, enhancement

#6296 Let the debug message finding -R -J history report the information
  src/gmt_init.c
Labels: maintenance

#6297 Let inset take -C instead of -M
  doc/examples/anim14/anim14.sh
  doc/rst/source/inset.rst
  doc/scripts/GMT_inset.sh
  src/inset.c
  test/modern/inset.sh
  test/modern/insetlegend.sh
Labels: documentation, enhancement, add-changelog, deprecation

#6298 gmt inset shall not accept -X -Y
  src/inset.c
Labels: bug

#6300 Fix limitation in -J parsing in inset and subplot
  src/gmt_init.c
Labels: bug

#6302 Improve sample1d docs for spatial resampling
  doc/rst/source/sample1d.rst
Labels: documentation

#6305 Let -X -Y also handle multipliers and not just divisors
  doc/rst/source/explain_-XY.rst_
  src/gmt_init.c
Labels: enhancement, add-changelog

#6310 Increase the memory allocation for voronoi polygon coordinates
  src/gmt_support.c
Labels: bug

#6311 Clarify when legend width must be specified
  doc/rst/source/legend.rst
Labels: documentation

#6317 CI: Update GraphicsMagick version
  ci/install-dependencies-windows.sh
Labels: maintenance

#6319 Let default remote grid registration be gridline for grdtrack
  doc/rst/source/grdtrack.rst
  src/gmt_bcr.c
  src/gmt_init.c
  src/gmt_private.h
  src/gmt_remote.c
Labels: bug

#6313 Let GMT verify counters in external datasets
  src/gmt_api.c
  src/gmt_io.c
  src/gmt_prototypes.h
  src/pslegend.c
Labels: maintenance

#6321 Did not set z_to_set if -N
  src/grdmask.c
Labels: bug

#6323 Allow deprecated -Q in grdsample
  src/grdsample.c
Labels: maintenance

#6325 Update technical info about images and the mask
  doc/rst/source/datasets/remote-data.rst
Labels: documentation

#6329 Turn off checking for file arguments for old -Sv vector
  src/gmt_init.c
Labels: bug

#6332 Let grdblend accept inner blend region with or without leading -R
  src/grdblend.c
Labels: bug, enhancement

#6333 Add script for documentation figure for grdblend
  doc/rst/source/grdblend.rst
  doc/scripts/GMT_blend.sh
  doc/scripts/images.dvc
Labels: documentation

#6334 Addressing Voronoi polygons in triangulate -Qn
  src/gmt_support.c
  src/triangulate.c
Labels: bug

#6346 Add option to exclude crossings from acutely intersection lines
  doc/rst/source/supplements/x2sys/x2sys_cross.rst
  src/mgd77/mgd77.c
  src/x2sys/x2sys_cross.c
Labels: new feature, add-changelog

#6361 Use same bold rst format for Notes
  doc/rst/source/explain_help.rst_
  doc/rst/source/explain_help_nopar.rst_
Labels: documentation

#6362 Allow for tiny slop when computing pads in grdimage
  src/grdimage.c
Labels: bug

#6260 No longer document the =AF code for continents
  doc/rst/source/explain_-R.rst_
  doc/rst/source/explain_-Rgeo.rst_
  src/gmt_dcw.c
  src/gmt_init.c
Labels: documentation

#6369 Fix error in determining min/max stack values in grdtrack -S
  src/grdtrack.c
Labels: bug

#6370 Refresh ex33 and clarify bounds
  doc/examples/ex33/ex33.sh
  doc/rst/source/gallery/ex33.rst
Labels: documentation

#6374 Update list of datasets in README.md
  README.md
Labels: documentation

#6363 Ensure that the raster has x and y increasing normally
  src/gmt_gdalread.c
Labels: enhancement

#6371 Check for angles that are either 0, -180 or 180 in gmtplot_get_outside_point_extension
  src/gmt_plot.c
Labels: bug

#6360 Let colorbar plot rectangles if possible
  doc/rst/source/colorbar.rst
  doc/rst/source/grdimage.rst
  doc/rst/source/grdview.rst
  doc/rst/source/macos_preview_issue.rst_
  doc/rst/source/psscale.rst
  doc/scripts/images.dvc
  src/psscale.c
  test/baseline/psscale.dvc
Labels: documentation, enhancement

#6381 Fix minor issues with gmt --new-glue
  src/gmt_support.c
Labels: maintenance

#6383 Make legend properly set meta data in structures
  src/pslegend.c
Labels: maintenance

#6389 Forgot to update PAR count
  src/pslegend.c
Labels: bug

#6390 Need to consult RG if no RP for grdimage with tiled remote grid
  src/gmt_init.c
Labels: bug

#6395 Potential cleanup
  doc/rst/source/supplements/potential/grdflexure.rst
  doc/rst/source/supplements/potential/grdseamount.rst
  doc/scripts/GMT_seamount_cum_inc.sh
Labels: documentation

#6391 Allow gmtconvert -S +e modifier for exact search
  doc/rst/source/gmtconvert.rst
  src/gmt_prototypes.h
  src/gmt_support.c
  src/gmtconvert.c
Labels: bug, documentation, enhancement
