Repository GenericMappingTools/gmt, pull requests merged in 2023-03, with the labels that each got.

#7289 More Van der Grinten fixes
  src/gmt_internals.h
  src/gmt_map.c
  src/gmt_plot.c
  test/baseline/pscoast.dvc
  test/pscoast/pscoast_JV_auto.sh
Labels: bug

#7290 Fix minor issues regarding central meridian
  src/gmt_map.c
Labels: maintenance

#7291 Let -JV take optional meridian without failure
  src/pscoast.c
  test/baseline/pscoast.dvc
  test/pscoast/pscoast_JV_set.sh
Labels: bug

#7222 Add more detail on how to build the documentation
  doc/rst/source/devdocs/contributing.rst
Labels: documentation

#7295 Make stricter checks on central longitude
  src/gmt_init.c
  src/gmt_map.c
Labels: bug

#7297 Let greenspline testing not require -DDEBUG
  src/greenspline.c
Labels: bug, maintenance

#7298 Fix typo on description of OR
  doc/rst/source/gmtmath.rst
Labels: documentation

#7304 Do not allow -Xc|f in modern mode
  doc/rst/source/explain_-XY.rst_
  doc/scripts/GMT_API_use.sh
  doc/scripts/GMT_blend.sh
  doc/scripts/GMT_inset.sh
  doc/scripts/GMT_tut_14.sh
  src/gmt_init.c
  test/grdfill/splinefill.sh
  test/modern/insetlegend.sh
  test/psbasemap/absrelaxis.sh
  test/psbasemap/sub1saxis.sh
Labels: documentation, maintenance

#7309 Add modifier +h[k|s] to gmt select -Z
  doc/rst/source/gmtselect.rst
  src/gmtselect.c
  test/gmtselect/segzcheck.sh
Labels: new core module feature

#7312 Replace mktemp with secure versions
  src/gmt_support.c
Labels: maintenance

#7315 Let grdimage share -T with grdview
  doc/rst/source/grdimage.rst
  src/gmt_plot.c
  src/gmt_prototypes.h
  src/grdimage.c
  src/grdview.c
Labels: new feature

#7317 Add GMT_Set_AllocMode to API docs
  doc/rst/source/devdocs/api.rst
  src/gmt_api.c
Labels: documentation

#7322 Let the PSL structure remember layer transparencies
  doc/rst/source/explain_transparency.rst_
  src/gmt_plot.c
  src/postscriptlight.c
  src/postscriptlight.h
Labels: bug

#7324 A few updates for building the release on macOS
  admin/PS_orig_for_gs.png
  admin/PS_orig_for_gs.ps
  admin/build-macos-cmake-cache.sh
  admin/build-macos-external-list.sh
  admin/build-release.sh
Labels: maintenance

#7320 Redo how alloc_mode is set in objects
  src/gmt_api.c
  src/gmt_grdio.c
  src/gmt_internals.h
  src/gmt_io.c
  src/gmt_plot.c
  src/grdmath.c
  src/testapi_gmtgrid.c
Labels: maintenance

#7333 Fix intneral memory leak in gmt_duplicate_grid
  src/gmt_grdio.c
Labels: bug, maintenance

#7345 Let grdfill state what is required
  src/grdfill.c
Labels: documentation
