Repository GenericMappingTools/gmt, pull requests merged in 2023-11, with the labels that each got.

#8007 Ensure the point symbol is filled with -Gcolor when in a legend
  src/gmt_init.c
  src/psxy.c
  src/psxyz.c
Labels: bug

#7960 doc: Add the interactive GMT color picker tool to the GMT docs
  doc/rst/source/color-picker.rst
  doc/rst/source/gmtcolors.rst
  doc/rst/source/index.rst
Labels: documentation

#8008 Fix issues with line symbol and legends
  src/psxy.c
  src/psxyz.c
Labels: bug

#7967 Convert test script for segmentizing to doc plot
  doc/rst/source/plot.rst
  doc/scripts/GMT_segmentize.sh
  test/psxy/geosegmentize.sh
Labels: documentation

#8011 Convert test to doc figure for grdmix
  doc/rst/source/grdmix.rst
  doc/scripts/GMT_mixing.sh
  doc/scripts/images/GMT_mixing.ps.dvc
  test/baseline/grdmix.dvc
Labels: documentation

#8014 Add named constants to gmt_api,c
  src/gmt_api.c
Labels: maintenance

#8016 Warn that Latex cannot be used in panel tags
  doc/rst/source/subplot.rst
Labels: documentation

#8018 Until solved, disallow subplot tags with Latex
  src/gmt_plot.c
Labels: maintenance

#8020 Update nearneighbor.rst -N
  doc/rst/source/nearneighbor.rst
Labels: documentation

#8025 Improbe batch documentation
  doc/rst/source/batch.rst
Labels: documentation

#8026 Improve layout of -D in colorbar man page and fix typo in usage message
  doc/rst/source/colorbar.rst
  src/psscale.c
Labels: documentation

#8027 Improve documentation layout for *contour.rst docs
  doc/rst/source/contour.rst
  doc/rst/source/explain_contdump.rst_
  doc/rst/source/explain_contlabel.rst_
  doc/rst/source/explain_contticks.rst_
  doc/rst/source/grdcontour.rst
Labels: documentation

#8028 Consistently use *.txt extension for ASCII files in examples and docs
  doc/rst/source/explain_contlabel.rst_
  doc/rst/source/gmt2kml.rst
  doc/rst/source/gmtconvert.rst
  doc/rst/source/grdtrack.rst
  doc/rst/source/grdvolume.rst
  doc/rst/source/supplements/geodesy/earthtide.rst
  doc/rst/source/supplements/spotter/rotconverter.rst
  doc/rst/source/supplements/x2sys/x2sys_put.rst
Labels: documentation

#8024 Fix incorrect parsing error message in basemap
  src/psbasemap.c
Labels: bug, documentation

#7567 Let -F work for -T as well
  src/potential/gravfft.c
Labels: bug

#8035 Catch lack of increment before calling next step in filter1d
  doc/rst/source/filter1d.rst
  src/gmt_support.c
Labels: bug

#8039 Allow +p as per docs
  doc/rst/source/gmtspatial.rst
  src/gmtspatial.c
Labels: bug, documentation

#8041 Only give annoying -p message if elevation is not 90
  src/gmt_init.c
Labels: maintenance

#8044 Be more careful to detect absolute time strings
  src/gmt_io.c
Labels: bug

#8045 Relax column content check for pstext
  src/gmt_api.c
  src/gmt_io.c
  src/gmt_private.h
  src/gmt_support.c
  src/pstext.c
Labels: bug

#8048 If no input to greenspline then properly quit
  src/greenspline.c
  src/surface.c
Labels: bug

#8050 New code for detecting what an ASCII column contains
  src/gmt_internals.h
  src/gmt_io.c
  src/gmtconvert.c
  src/pscoast.c
  test/gmtconvert/strings.txt
  test/gmtconvert/testparser.sh
Labels: maintenance

#8051 Enable the new abstime scanner
  src/gmt_io.c
Labels: maintenance

#8055 Oops, grdfft's -D -I are repeatable options
  doc/rst/source/grdfft.rst
  src/grdfft.c
Labels: bug

#8054 Fix anim09 to first build global grid
  doc/examples/anim09/anim09.sh
  doc/rst/source/animations/anim09.rst
Labels: maintenance

#8056 Clarify -T option in usage and docs
  doc/rst/source/supplements/seis/meca.rst
  src/seis/psmeca.c
Labels: documentation, maintenance

#8059 New pen meca and coupe -T syntax
  doc/rst/source/supplements/seis/coupe.rst
  doc/rst/source/supplements/seis/meca.rst
  doc/rst/source/supplements/seis/pscoupe.rst
  doc/rst/source/supplements/seis/psmeca.rst
  src/seis/pscoupe.c
  src/seis/psmeca.c
Labels: documentation, maintenance

#7483 More grdfloat introductions
  src/geodesy/earthtide.c
  src/gmt_customio.c
  src/gmt_gdalcall.c
  src/gmt_grdio.c
  src/gmt_io.c
  src/gmt_map.c
  src/grdinterpolate.c
  src/testapi_gmtgrid.c
Labels: maintenance

#8072 Fix lack of xyz->xy conversion for graticules in grdview -T
  src/gmt_plot.c
  src/gmt_prototypes.h
  src/grdimage.c
  src/grdview.c
Labels: bug

#8073 Fix DOI for citation in mgd77info docs
  doc/rst/source/supplements/mgd77/mgd77convert.rst
  doc/rst/source/supplements/mgd77/mgd77header.rst
  doc/rst/source/supplements/mgd77/mgd77info.rst
  doc/rst/source/supplements/mgd77/mgd77list.rst
  doc/rst/source/supplements/mgd77/mgd77manage.rst
  doc/rst/source/supplements/mgd77/mgd77path.rst
  doc/rst/source/supplements/mgd77/mgd77sniffer.rst
  doc/rst/source/supplements/mgd77/mgd77track.rst
Labels: documentation

#8074 Use named constants rater than 0-2
  src/gmt_contour.h
  src/gmt_decorate.h
  src/gmt_support.c
  src/grdcontour.c
  src/pscontour.c
Labels: maintenance

#8078 Better layout of docs for colorbar -S
  doc/rst/source/colorbar.rst
Labels: documentation

#8075 Make batch -T doc use the same format as for movie -T
  doc/rst/source/batch.rst
Labels: documentation

#8082 Fix typos, minor bugs and clean up -F for plot and gmtconnect
  doc/rst/source/gmtconvert.rst
  doc/rst/source/plot.rst
  src/gmt_init.c
  src/gmt_synopsis.h
  src/gmtconvert.c
  src/psxy.c
Labels: bug, documentation

#8080 Improve layout of -C option in gmtbinstats
  doc/rst/source/gmtbinstats.rst
Labels: documentation

#8076 Improve documentation of -E and -D in blockm*
  doc/rst/source/blockmean.rst
  doc/rst/source/blockmedian.rst
  doc/rst/source/blockmode.rst
  src/blockmode.c
Labels: documentation

#8077 Improve the layout of coast -A
  doc/rst/source/explain_-A.rst_
Labels: documentation

#8084 Improve man page for gmt logo
  doc/rst/source/gmtlogo.rst
  src/gmt_init.c
  src/gmtlogo.c
Labels: documentation

#8083 Improve the layout of gmtinfo's -I option in usage and docs
  doc/rst/source/gmtinfo.rst
  src/gmtinfo.c
Labels: documentation

#8085 Improve gmtmath documentation
  doc/rst/source/gmtmath.rst
Labels: documentation

#8090 Improve the presentation of how to enter CPT or colors via -C
  doc/rst/source/create_cpt.rst_
  doc/rst/source/use_cpt_grd.rst_
Labels: documentation

#8087 Remove unimplemented options
  doc/rst/source/gmtspatial.rst
  src/gmtspatial.c
Labels: documentation

#8095 Fix incomplete -Q in docs and usage messages
  doc/rst/source/contour.rst
  doc/rst/source/grdcontour.rst
  doc/rst/source/pscontour.rst
  src/grdcontour.c
  src/pscontour.c
Labels: documentation

#8093 Update grdblend doc layout
  doc/rst/source/grdblend.rst
Labels: documentation

#8094 Use math for special symbols
  doc/rst/source/grdclip.rst
Labels: documentation

#8101 Update grdfft -E option
  doc/rst/source/grdfft.rst
  src/grdfft.c
Labels: documentation

#8099 Enable updated Accelerate headers for Darin kernel >= 22.4
  CMakeLists.txt
  cmake/ConfigUserAdvancedTemplate.cmake
  src/CMakeLists.txt
  src/gmt_vector.c
Labels: maintenance

#8107 Use named enums in grdinfo and improve -L layout
  doc/rst/source/grdinfo.rst
  src/grdinfo.c
Labels: documentation, maintenance

#8104 Improve grdfill docs
  doc/rst/source/grdfill.rst
Labels: documentation

#8105 Improve grdfilter -N docs
  doc/rst/source/grdfilter.rst
Labels: documentation

#8109 Fix bug in greenspline for -E -C
  src/greenspline.c
Labels: bug

#8108 Strengthen -Elines documentation for grdtrack and grdinterpolate
  doc/rst/source/explain_interpolant.rst_
  doc/rst/source/explain_lines.rst_
  doc/rst/source/grdinterpolate.rst
  doc/rst/source/grdtrack.rst
  doc/rst/source/sample1d.rst
  src/gmt_constants.h
  src/gmt_prototypes.h
  src/gmt_support.c
  src/grdinterpolate.c
  src/grdtrack.c
  src/sample1d.c
Labels: documentation, maintenance

#8111 Reestablish CPT hinge for master tables
  src/gmt_support.c
  test/baseline/grdimage.dvc
  test/grdimage/cpt_hinge.sh
Labels: bug

#8103 Update anim05.sh. Fix typos
  doc/examples/anim05/anim05.sh
Labels: documentation
