Repository GenericMappingTools/gmt, pull requests merged in 2023-05, with the labels that each got.

#7440 VE Fix
  src/gmt_map.c
Labels: bug

#7441 Fix scale info
  src/gmt_map.c
Labels: bug

#7444 Make clear which arguments are optional in plot -S
  doc/rst/source/explain_symbols.rst_
Labels: documentation

#7442 List all modifiers for plot -Sw and -SW
  doc/rst/source/explain_symbols.rst_
Labels: documentation

#7447 Allow image -D+w to specify just height
  doc/rst/source/image.rst
  src/psimage.c
Labels: documentation, enhancement

#7449 Set DIR_DATA for movie title script
  src/movie.c
Labels: bug

#7450 Clean up -Z error message
  src/project.c
Labels: documentation, maintenance

#7458 Add modifier +hheight to set logo height instead of width
  doc/rst/source/gmtlogo-classic.rst
  doc/rst/source/gmtlogo.rst
  src/gmtlogo.c
Labels: enhancement, add-changelog

#7456 Let movie open and play movie if gmt end show is used
  doc/rst/source/movie.rst
  src/movie.c
Labels: enhancement

#7461 Let movie -A handle addition of audio track
  doc/rst/source/movie.rst
  src/gmt_prototypes.h
  src/gmt_support.c
  src/movie.c
Labels: documentation, new core module feature

#7465 Polish script and doc for gallery example 01
  doc/examples/ex01/ex01.bat
  doc/examples/ex01/ex01.sh
  doc/rst/source/gallery/ex01.rst
Labels: documentation

#7466 Forgot to update ex19
  doc/examples/ex19/ex19.bat
  doc/examples/ex19/ex19.sh
  doc/examples/images.dvc
  doc/rst/source/gallery/ex19.rst
Labels: documentation

#7470 Improve readability of gmt select -Z
  doc/rst/source/gmtselect.rst
Labels: documentation

#7469 Fix wrong noise direction in grdsample wesn checking
  src/grdsample.c
Labels: bug

#7481 Use gmt_grdfloat for grid values in grdmath
  src/gmt_macros.h
  src/grdmath.c
Labels: maintenance

#7478 Add option to transpose a dataset in gmt convert
  doc/rst/source/gmtconvert.rst
  src/gmt_io.c
  src/gmt_prototypes.h
  src/gmtconvert.c
  test/gmtconvert/transpose.sh
Labels: new core module feature
