Repository GenericMappingTools/gmt, pull requests merged in 2023-12, with the labels that each got.

#133 Add shake map modules
  admin/add_windows_cpack.txt
  doc/rst/source/modules-classic.rst
  doc/rst/source/modules.rst
  doc/rst/source/reference/supplemental-packages.rst
  doc/rst/source/supplements/module_supplements_purpose.rst_
  src/seis/CMakeLists.txt
  src/seis/longopt/shake_inc.h
  src/seis/longopt/vs30_inc.h
  src/seis/shake.c
  src/seis/vs30.c
Labels: longterm

#8117 Detect pole in inverse ECEF in mapproject
  src/gmt_map.c
Labels: bug

#8128 PostScript original updates for wrong plots
  doc/examples/images/ex02.ps.dvc
  doc/examples/images/ex18.ps.dvc
  doc/examples/images/ex29.ps.dvc
  doc/examples/images/ex33.ps.dvc
  doc/examples/images/ex34.ps.dvc
  doc/examples/images/ex38.ps.dvc
  doc/examples/images/ex39.ps.dvc
  doc/rst/source/supplements/module_supplements_purpose.rst_
  doc/scripts/images/GMT_App_O_9.ps.dvc
  doc/scripts/images/GMT_gsfml_components.ps.dvc
  doc/scripts/images/GMT_tut_11.ps.dvc
  doc/scripts/images/GMT_tut_16.ps.dvc
  doc/scripts/images/GMT_tut_18.ps.dvc
  doc/scripts/images/GMT_tut_19.ps.dvc
  test/baseline/api.dvc
  test/baseline/gmtmex.dvc
  test/baseline/grdcontour.dvc
  test/baseline/grdfill.dvc
  test/baseline/grdfilter.dvc
  test/baseline/grdimage.dvc
  test/baseline/grdview.dvc
  test/baseline/psevents.dvc
Labels: documentation, maintenance

#8129 Fix the greenspline -A documentation
  doc/rst/source/greenspline.rst
Labels: documentation

#8134 Update doc layout
  doc/rst/source/histogram.rst
  doc/rst/source/pshistogram.rst
Labels: documentation

#8136 Update legend docs for -M
  doc/rst/source/legend.rst
Labels: documentation

#8138 Upgrade grd2cpt like makecpt and improve docs
  doc/rst/source/explain_cpt_output.rst_
  doc/rst/source/grd2cpt.rst
  doc/rst/source/makecpt.rst
  src/gmt_constants.h
  src/gmt_init.c
  src/gmt_prototypes.h
  src/gmt_resources.h
  src/gmt_support.c
  src/grd2cpt.c
  src/makecpt.c
Labels: documentation, enhancement

#8141 Mapproject docs
  doc/rst/source/mapproject.rst
Labels: documentation

#8142 Improve the plot doc layout
  doc/rst/source/plot.rst
Labels: documentation

#8152 Update subplot docs
  doc/rst/source/subplot.rst
Labels: documentation

#8151 Update sphtriangle docs
  doc/rst/source/sphtriangulate.rst
Labels: documentation

#8150 Update sphinterpolate docs
  doc/rst/source/sphinterpolate.rst
Labels: documentation

#8147 Update spectrum1d- docs for -C
  doc/rst/source/spectrum1d.rst
Labels: documentation

#8146 Update solar docs for -I and -T
  doc/rst/source/solar.rst
Labels: documentation

#8145 Update doc layout for sample1d -A
  doc/rst/source/sample1d.rst
Labels: documentation

#8143 Improve plot3d docs
  doc/rst/source/explain_line_draw.rst_
  doc/rst/source/plot.rst
  doc/rst/source/plot3d.rst
Labels: documentation

#8149 Update sphdistance docs for -E
  doc/rst/source/sphdistance.rst
Labels: documentation

#8154 Trend1d improve
  doc/rst/source/trend1d.rst
Labels: documentation

#8144 Improve layout of psconvert options
  doc/rst/source/psconvert.rst
Labels: documentation

#8156 Update xyz2grd -A option
  doc/rst/source/xyz2grd.rst
Labels: documentation

#8133 Clean up grdview rst
  doc/rst/source/grdview.rst
Labels: documentation

#8140 mgd77sniffer.rst clarify DC
  doc/rst/source/supplements/mgd77/mgd77sniffer.rst
Labels: documentation

#8130 Update DVC instructions to be per file and not per directory
  doc/rst/source/devdocs/contributing.rst
Labels: documentation

#8160 Check for error if CPT has non-zero hinge
  doc/rst/source/reference/features.rst
  src/gmt_prototypes.h
  src/gmt_support.c
  src/grd2cpt.c
  src/makecpt.c
  src/psscale.c
Labels: bug

#8163 Improve greenspline -A and -S docs
  doc/rst/source/greenspline.rst
Labels: documentation

#8165 Improved synopsis and usage of -Ccpt for grid plot modules
  doc/rst/source/grd2kml.rst
  doc/rst/source/grdimage.rst
  doc/rst/source/grdvector.rst
  doc/rst/source/grdview.rst
  doc/rst/source/use_cpt_grd.rst_
  src/gmt_constants.h
  src/gmt_prototypes.h
  src/gmt_support.c
  src/grd2kml.c
  src/grdimage.c
  src/grdvector.c
  src/grdview.c
Labels: documentation

#8168 Rot docs
  doc/rst/source/supplements/spotter/explain_rots.rst_
  share/spotter/Muller2019-Young2019-Cao2020_CombinedRotations.rot
  src/spotter/spotter.h
Labels: documentation

#8169 Minor formatting cleaning
  doc/rst/source/explain_intense.rst_
  doc/rst/source/grd2kml.rst
  doc/rst/source/grdimage.rst
  doc/rst/source/grdview.rst
  doc/rst/source/plot.rst
  doc/rst/source/plot3d.rst
  doc/rst/source/surface.rst
  doc/rst/source/trend1d.rst
Labels: documentation

#8170 Replace colons with hyphens in rst lists
  doc/rst/source/create_cpt.rst_
  doc/rst/source/explain_-A.rst_
  doc/rst/source/explain_-D_cap.rst_
  doc/rst/source/explain_-F_box.rst_
  doc/rst/source/explain_-U.rst_
  doc/rst/source/explain_-XY.rst_
  doc/rst/source/explain_-h_full.rst_
  doc/rst/source/explain_-icols_full.rst_
  doc/rst/source/explain_-l_full.rst_
  doc/rst/source/explain_-n_full.rst_
  doc/rst/source/explain_-ocols_full.rst_
  doc/rst/source/explain_-q_full.rst_
  doc/rst/source/explain_contticks.rst_
  doc/rst/source/explain_cpt_output.rst_
  doc/rst/source/explain_fft.rst_
  doc/rst/source/explain_gshhg.rst_
  doc/rst/source/explain_interpolant.rst_
  doc/rst/source/explain_line_draw.rst_
  doc/rst/source/explain_lines.rst_
  doc/rst/source/explain_perspective_full.rst_
  doc/rst/source/gmtinfo.rst
  doc/rst/source/gmtlogo.rst
  doc/rst/source/gmtmath.rst
  doc/rst/source/gmtspatial.rst
  doc/rst/source/grdblend.rst
  doc/rst/source/grdfft.rst
  doc/rst/source/greenspline.rst
  doc/rst/source/histogram.rst
  doc/rst/source/image.rst
  doc/rst/source/mapproject.rst
  doc/rst/source/plot.rst
  doc/rst/source/plot3d.rst
  doc/rst/source/psconvert.rst
  doc/rst/source/sample1d.rst
  doc/rst/source/solar.rst
  doc/rst/source/subplot.rst
  doc/rst/source/supplements/geodesy/gpsgridder.rst
  doc/rst/source/supplements/potential/gravprisms.rst
  doc/rst/source/text.rst
  doc/rst/source/trend1d.rst
  doc/rst/source/triangulate.rst
  doc/rst/source/use_cpt_grd.rst_
Labels: documentation

#8171 Add missing transproc_mask and GMT_TP_STANDARD in 54 include files
  src/geodesy/longopt/earthtide_inc.h
  src/geodesy/longopt/gpsgridder_inc.h
  src/geodesy/longopt/psvelo_inc.h
  src/gshhg/longopt/gshhg_inc.h
  src/img/longopt/img2grd_inc.h
  src/longopt/gmtselect_inc.h
  src/mgd77/longopt/mgd77convert_inc.h
  src/mgd77/longopt/mgd77header_inc.h
  src/mgd77/longopt/mgd77info_inc.h
  src/mgd77/longopt/mgd77list_inc.h
  src/mgd77/longopt/mgd77magref_inc.h
  src/mgd77/longopt/mgd77manage_inc.h
  src/mgd77/longopt/mgd77path_inc.h
  src/mgd77/longopt/mgd77sniffer_inc.h
  src/mgd77/longopt/mgd77track_inc.h
  src/potential/longopt/gmtflexure_inc.h
  src/potential/longopt/gmtgravmag3d_inc.h
  src/potential/longopt/gravfft_inc.h
  src/potential/longopt/gravprisms_inc.h
  src/potential/longopt/grdflexure_inc.h
  src/potential/longopt/grdgravmag3d_inc.h
  src/potential/longopt/grdredpol_inc.h
  src/potential/longopt/grdseamount_inc.h
  src/potential/longopt/talwani2d_inc.h
  src/potential/longopt/talwani3d_inc.h
  src/segy/longopt/pssegy_inc.h
  src/segy/longopt/pssegyz_inc.h
  src/segy/longopt/segy2grd_inc.h
  src/seis/longopt/pscoupe_inc.h
  src/seis/longopt/psmeca_inc.h
  src/seis/longopt/pspolar_inc.h
  src/seis/longopt/pssac_inc.h
  src/seis/longopt/shake_inc.h
  src/seis/longopt/vs30_inc.h
  src/spotter/longopt/backtracker_inc.h
  src/spotter/longopt/gmtpmodeler_inc.h
  src/spotter/longopt/grdpmodeler_inc.h
  src/spotter/longopt/grdrotater_inc.h
  src/spotter/longopt/grdspotter_inc.h
  src/spotter/longopt/hotspotter_inc.h
  src/spotter/longopt/originater_inc.h
  src/spotter/longopt/polespotter_inc.h
  src/spotter/longopt/rotconverter_inc.h
  src/spotter/longopt/rotsmoother_inc.h
  src/x2sys/longopt/x2sys_binlist_inc.h
  src/x2sys/longopt/x2sys_cross_inc.h
  src/x2sys/longopt/x2sys_datalist_inc.h
  src/x2sys/longopt/x2sys_get_inc.h
  src/x2sys/longopt/x2sys_init_inc.h
  src/x2sys/longopt/x2sys_list_inc.h
  src/x2sys/longopt/x2sys_merge_inc.h
  src/x2sys/longopt/x2sys_put_inc.h
  src/x2sys/longopt/x2sys_report_inc.h
  src/x2sys/longopt/x2sys_solve_inc.h
Labels: maintenance

#8173 Fix a bunch of clang compiler warnings
  src/batch.c
  src/gmt_init.c
  src/gmt_io.c
  src/gmt_memory.c
  src/gmt_plot.c
  src/gmt_private.h
  src/gmt_proj.c
  src/gmt_support.c
  src/gmtconnect.c
  src/gmtinfo.c
  src/gmtsplit.c
  src/grdimage.c
  src/grdtrack.c
  src/gsfml/fzblender.c
  src/gsfml/mlconverter.c
  src/mgd77/mgd77header.c
  src/mgd77/mgd77manage.c
  src/movie.c
  src/postscriptlight.c
  src/potential/gmtgravmag3d.c
  src/potential/grdseamount.c
  src/psevents.c
  src/seis/grdvs30.c
  src/spotter/originater.c
  src/surface.c
  src/surface_experimental.c
  src/surface_old.c
  src/windbarbs/psbarb.c
Labels: maintenance

#8174 RST upgrades
  doc/rst/source/explain_-I.rst_
  doc/rst/source/explain_-bi_full.rst_
  doc/rst/source/explain_-g_full.rst_
  doc/rst/source/explain_-s_full.rst_
  doc/rst/source/explain_color.rst_
  doc/rst/source/explain_distcalc_full.rst_
  doc/rst/source/explain_nodereg_full.rst_
  doc/rst/source/explain_refpoint.rst_
  doc/rst/source/explain_vectors.rst_
Labels: documentation

#8188 Long-lasting bug with seniority finally killed in gmt_crossover function
  src/gmt_support.c
  test/baseline/greenspline.dvc
Labels: bug

#8189 Better handling of deprecated strings
  doc/rst/source/image.rst
  doc/rst/source/supplements/seis/sac.rst
  src/psimage.c
Labels: maintenance

#8192 Allow grdmix to read single RGB image in conjunction with -A -C
  doc/rst/source/grdmix.rst
  src/grdmix.c
Labels: bug

#8193 Add -C[cpt] arg to grdmix
  doc/rst/source/grdmix.rst
  src/grdmix.c
  test/baseline/grdmix.dvc
  test/grdmix/grid2img.sh
Labels: documentation, enhancement

#8195 Add -Ccpt option to sample colors from sample1d and grdxyz
  doc/rst/source/dump_rgb.rst_
  doc/rst/source/grd2xyz.rst
  doc/rst/source/sample1d.rst
  src/grd2xyz.c
  src/longopt/grd2xyz_inc.h
  src/longopt/sample1d_inc.h
  src/sample1d.c
Labels: add-changelog, new core module feature

#8207 Fix gmt_f77_writegrd_ and gmt_f77_readgrdinfo_ in order to avoid segmentation fault
  src/gmt_api.c
Labels: bug

#8211 Careful sincosd when time is not of the essence
  src/gmt_support.c
Labels: bug

#8212 Homogenize animations
  doc/examples/anim05/anim05.sh
  doc/examples/anim06/anim06.sh
  doc/examples/anim09/anim09.sh
  doc/examples/anim10/anim10.sh
  doc/examples/anim14/anim14.sh
  doc/examples/anim15/anim15.sh
Labels: documentation

#8218 Fix decades-long issue with patterns in coast
  doc/rst/source/coast.rst
  src/pscoast.c
Labels: enhancement

#8231 Fix bad check for when using -T in mapproject
  src/mapproject.c
Labels: bug

#8233 Forgot to handle Euro dates dd.mm.yyyy in the first-record exam
  src/gmt_internals.h
  src/gmt_io.c
  src/gmtconvert.c
Labels: bug

#8238 Fix bad effect of roundoff at boarder
  src/gmt_constants.h
  src/gmt_proj.c
Labels: bug

#8239 More careful with Mollweide
  src/gmt_proj.c
Labels: bug

#8240 Fix lack of 360 periodicity in central longitude and -R check
  src/gmt_map.c
Labels: bug

#8243 Fix wrong calculation of median and q95 in gmtbinstats
  src/gmtbinstats.c
Labels: bug

#8244 Update two PS file following bug fix
  test/baseline/gmtbinstats.dvc
Labels: documentation

#8245 Be more careful on memory layout for iimages
  src/gmt_api.c
Labels: maintenance

#8246 Allow colorbar -LI as well as -Li
  doc/rst/source/colorbar.rst
  doc/rst/source/psscale.rst
  src/psscale.c
Labels: enhancement

#8230 Add polar and cartesian to -A description for grdbarg
  doc/rst/source/supplements/windbarbs/grdbarb.rst
  src/windbarbs/grdbarb.c
Labels: documentation
