Repository GenericMappingTools/gmt, pull requests merged in 2023-04, with the labels that each got.

#7357 Reset Nan font in case modern mode
  src/mgd77/mgd77track.c
Labels: bug

#7356 allow slop in wesn
  src/grdsample.c
Labels: bug

#7362 Add safety valve in iteration loop
  src/potential/grdseamount.c
Labels: maintenance

#7366 Catch silly things like -R@earth_relief_05
  src/gmt_init.c
Labels: bug

#7367 Update comments for gmt_remote.c
  src/gmt_remote.c
Labels: documentation, maintenance

#7371 Add updated func list to gmt_calclock.c
  src/gmt_calclock.c
Labels: documentation

#7368 Add option to grdpaste to only report the "pasting" side.
  doc/rst/source/grdpaste.rst
  src/grdpaste.c
Labels: new feature

#7372 List of functions in gmt_common_math
  src/gmt_common_math.c
Labels: documentation

#7369 Add function list to gmt_api.c comments
  src/gmt_api.c
Labels: documentation, maintenance

#7376 Fix places where declaration come after statements
  src/blockmedian.c
  src/blockmode.c
  src/gmt_support.c
  src/gmt_vector.c
  src/potential/grdflexure.c
  src/psscale.c
Labels: maintenance

#7375 Fix signal function list
  src/gmt.c
  src/gmt_common_sighandler.c
  src/gmt_common_sighandler.h
Labels: documentation, maintenance

#7377 Update gmt_dcw.c
  src/gmt_dcw.c
Labels: documentation

#7378 Update gmt_fft.c with function list
  src/gmt_fft.c
Labels: documentation

#7363 WIP Update admin/build-release.sh for 6.5
  admin/build-release.sh
Labels: maintenance

#7381 Reset V.active before parsing again
  src/grdblend.c
Labels: bug

#7382 Honor -T+a modifier in sample1d
  src/sample1d.c
Labels: bug

#7384 Silence triangulate warning
  src/gmt_support.c
  src/seis/pscoupe.c
Labels: maintenance

#7385 List gmt function exported by gdalcall.c
  src/gmt_gdalcall.c
Labels: documentation, maintenance

#7386 Add gdalread func list
  src/gmt_gdalread.c
Labels: documentation, maintenance

#7389 Add function list for gmt_io.c
  src/gmt_io.c
Labels: documentation

#7391 Add function list to gmt_memory.c
  src/gmt_memory.c
Labels: documentation

#7392 Add function list to gmt_modern.c
  src/gmt_modern.c
Labels: documentation

#7393 Add function list to gmt_nc.c
  src/gmt_nc.c
Labels: documentation

#7395 Add function list to gmt_proj.c
  src/gmt_proj.c
Labels: documentation

#7394 Add function list to gmt_plot.c
  src/gmt_plot.c
  src/gmt_prototypes.h
  src/psscale.c
Labels: documentation, maintenance

#7390 Add function list to gmt_map.c
  src/gmt_map.c
  src/gmt_project.h
  src/gmt_prototypes.h
  src/pscoast.c
Labels: documentation, maintenance

#7398 Start at 1 when counting completed frames
  src/movie.c
Labels: bug

#7399 Set sharepath func list
  src/gmt_common_runpath.c
  src/gmt_common_runpath.h
  src/gmt_init.c
Labels: documentation, maintenance

#7401 Ensure trend1d -Fm output is sorted
  doc/rst/source/trend1d.rst
  src/trend1d.c
Labels: documentation, maintenance

#7402 Reset character set if given via --PS_CHAR_ENCODING
  src/gmt_init.c
  src/gmt_plot.c
Labels: bug

#7403 Ensure column names header is set to be writen
  src/gmt_api.c
Labels: bug

#7388 Ad gmt_init.c func list
  src/gmt_init.c
  src/gmt_prototypes.h
  src/gmtdefaults.c
  src/gmtset.c
  src/grdimage.c
  src/grdsample.c
Labels: documentation, maintenance

#7387 Add gmt_grdio function list
  src/gmt_grdio.c
Labels: documentation, maintenance

#7409 Fix issues with gmt which -G
  src/gmt_remote.c
  src/gmtwhich.c
Labels: bug

#7413 Add -Io to grdinfo for oblique format
  doc/rst/source/grdinfo.rst
  src/grdinfo.c
Labels: enhancement

#7414 Fix a few minor issues in gmtinfo.rst
  doc/rst/source/gmtinfo.rst
Labels: documentation

#7417 Fix example discussion
  doc/rst/source/batch.rst
Labels: documentation

#7379 Option to use build-release no gdal on the macports
  admin/build-macos-external-list.sh
  admin/build-release.sh
Labels: maintenance

#7419 Fix formatting n a few places
  doc/rst/source/explain_clabelinfo.rst_
  doc/rst/source/explain_contlabel.rst_
  doc/rst/source/grdconvert.rst
Labels: documentation

#7421 Ensure --FONT_ANNOT_PRIMARY=+ sets proper dimensions
  src/gmt_init.c
Labels: bug

#7423 More robust checking for single L|U|B flags in CPTs
  src/gmt_support.c
Labels: bug

#7424 Avoid crash if empty file given to makecpt -E
  src/makecpt.c
Labels: maintenance

#7429 gmt_remote adds -V so we must set it to inactive
  src/gmt_remote.c
Labels: maintenance

#7430 Also accept FHD for 1920x1080
  doc/rst/source/movie.rst
  src/movie.c
Labels: documentation, maintenance
