Repository GenericMappingTools/gmt, pull requests merged in 2023-10, with the labels that each got.

#7855 Prevent pstext crash is given stoopid things on command line
  src/gmt_init.c
Labels: maintenance

#7857 Increment in -T seen as zero if < 1e08
  src/gmt_init.c
  src/gmt_support.c
Labels: bug

#7858 Enhance grdclip -Sa -Sb with modifier +e for equality
  doc/rst/source/grdclip.rst
  src/grdclip.c
Labels: enhancement, add-changelog

#7812 Ghost server use for maintainers
  src/gmt.c
  src/gmt_init.c
  src/gmt_internals.h
  src/gmt_remote.c
Labels: maintenance

#7863 Handle -R@earth_relief_20m without registration
  src/gmt_api.c
  src/gmt_init.c
  src/gmt_prototypes.h
  src/gmt_remote.c
Labels: bug

#7864 Handle remote tiled grids in option arguments
  src/gmt_init.c
  src/gmt_remote.c
Labels: bug

#7866 Dont let multiple @ pass as file name
  src/gmt_init.c
Labels: bug

#7865 psconvert should ignore writing world file if geotiff output is requested
  src/psconvert.c
Labels: bug

#7867 Subplot did not process axis modifiers +p and +u
  src/subplot.c
Labels: bug

#7871 The byte image change was only meant to cover 1-band images
  src/grdimage.c
Labels: bug

#7873 More carefully detect if no increment in -T array arg
  src/gmt_support.c
  src/gmt_types.h
Labels: bug

#7876 Update filter1d.rst. Add reference to technical references
  doc/rst/source/filter1d.rst
Labels: documentation

#7881 Managed to get the sign wrong the first time
  src/psscale.c
Labels: bug

#7880 Prepare -i -o for common modifiers
  src/gmt_api.c
  src/gmt_common.h
  src/gmt_init.c
  src/gmt_io.c
  src/gmt_support.c
  src/psrose.c
Labels: maintenance

#7883 Fix catlabels and update PS
  test/baseline/psscale.dvc
  test/psscale/catlabels.sh
Labels: maintenance

#7891 Skip input ascii records with not enough columns
  src/gmt_io.c
Labels: maintenance

#7887 Enhance -o to accept the same transformations as -i
  doc/rst/source/explain_-icols_full.rst_
  doc/rst/source/explain_-ocols.rst_
  doc/rst/source/explain_-ocols_full.rst_
  doc/rst/source/reference/options.rst
  doc/rst/source/std-opts.rst
  src/gmt_init.c
  src/gmt_io.c
  src/gmt_synopsis.h
  test/gmt_core/gmt_io_cols.sh
Labels: enhancement, add-changelog

#7893 Update long-options for -o
  src/gmt_common_longoptions.h
Labels: maintenance

#7898 Disallow -B when grdimage -A is used
  doc/rst/source/grdimage.rst
  src/grdimage.c
Labels: maintenance

#7879 Static server issues
  src/gmt_internals.h
  src/gmt_private.h
  src/gmt_remote.c
  test/gmtest.in
  test/psxy/gallo.sh
Labels: enhancement

#7901 Try harder to guess date format and update template
  src/gmt_io.c
Labels: enhancement

#7902 Update gmt_support.c
  src/gmt_support.c
Labels: bug

#7903 sample1d: Remove note for monotonically increasing data.
  doc/rst/source/sample1d.rst
Labels: documentation

#7905 Fix description of -Fe
  doc/rst/source/sample1d.rst
Labels: documentation

#7900 Filling area between two time- or space-series
  doc/rst/source/plot.rst
  doc/rst/source/psxy.rst
  doc/scripts/GMT_fill_curves.sh
  src/gmt_constants.h
  src/gmt_init.c
  src/gmt_plot.c
  src/gmt_prototypes.h
  src/psxy.c
Labels: documentation, new feature, add-changelog

#7907 Add warning in x2sys if Cartesian but looks like geographic
  src/gmt_support.c
Labels: maintenance

#7913 Add option and list of GTHREADS to gmt-config
  src/CMakeLists.txt
  src/gmt-config.in
  test/baseline/grdfilter.dvc
  test/grdfilter/openmp.sh
  test/grdfilter/threads.sh
Labels: maintenance

#7915 Stress that IO_COL_SEPARATOR is for output formatting only
  doc/rst/source/gmt.conf.rst
  src/gmt_init.c
Labels: documentation, maintenance

#7909 Let pslegend -D+w accept a percentage relative to map width
  doc/rst/source/legend.rst
  src/gmt_prototypes.h
  src/gmt_support.c
  src/gmt_types.h
  src/pslegend.c
  src/psscale.c
Labels: enhancement

#7923 Use --metric (and aliases) for -j
  src/gmt_common_longoptions.h
Labels: maintenance

#7936 Need to reparse -o when output received from module call
  src/gmt_api.c
  src/gmt_init.c
  src/gmt_internals.h
  src/gmt_io.c
  src/gmt_prototypes.h
  src/grdinterpolate.c
Labels: bug

#7762 coast.rst: only use abbreviations when specifying continent
  doc/rst/source/coast.rst
Labels: documentation

#7961 Let grdcut -E extract a vertical slice from a 3-D cube
  doc/rst/source/grdcut.rst
  doc/rst/source/module_core_purpose.rst_
  src/gmt_api.c
  src/gmt_grdio.c
  src/gmt_prototypes.h
  src/grdclip.c
  src/grdcut.c
  test/baseline/grdcut.dvc
  test/grdcut/vert_cube_cuts.sh
Labels: new core module feature

#7956 Ensure geographic grids are written as such
  src/gmt_grdio.c
Labels: bug

#7968 Convert grdblend test to documentation figure
  doc/rst/source/grdblend.rst
  doc/scripts/GMT_blendtype.sh
  doc/scripts/images.dvc
  test/baseline/grdblend.dvc
  test/baseline/psxy.dvc
  test/grdblend/blend.sh
Labels: documentation

#7972 Let psconvert -N+kfill set alternate fade fill
  doc/rst/source/figure.rst
  doc/rst/source/psconvert.rst
  src/figure.c
  src/movie.c
  src/psconvert.c
Labels: documentation, enhancement, deprecation

#7969 Convert hex-binning test to a doc figure instead
  doc/rst/source/gmtbinstats.rst
  doc/scripts/GMT_hexbinning.sh
  doc/scripts/images.dvc
  test/baseline/gmtbinstats.dvc
  test/gmtbinstats/hex_data.txt
Labels: documentation

#7973 Pattern fill modifiers +f and +b got lost when -legend was used
  src/gmt_init.c
  src/gmt_support.c
  src/gmt_texture.h
Labels: bug

#7977 New version of ex15
  doc/examples/ex15/ex15.bat
  doc/examples/ex15/ex15.sh
Labels: documentation

#7974 TM gives widely different answer for spherical and elliptical
  doc/rst/source/explain_distcalc.rst_
  doc/rst/source/explain_distcalc_full.rst_
  doc/rst/source/explain_ellipsoidal.rst_
  doc/rst/source/grdproject.rst
  doc/rst/source/mapproject.rst
  src/gmt_common.h
  src/gmt_init.c
  src/gmt_map.c
  src/gmt_proj.c
  src/grdproject.c
  src/mapproject.c
  test/mapproject/snyder.sh
Labels: bug

#7978 update ex15 PS and dvc .git file
  .github/workflows/dvc-diff.yml
  doc/examples/images.dvc
Labels: documentation

#7981 Let --increment accept alias --inc
  src/gmt_constants.h
Labels: maintenance
