Repository GenericMappingTools/gmt, pull requests merged in 2023-09, with the labels that each got.

#7775 Let a temp fprintf behind
  src/psscale.c
Labels: maintenance

#7790 Fix the stuttering RST files
  doc/rst/source/gmtmath.rst
  doc/rst/source/legend.rst
  doc/rst/source/reference/features.rst
  doc/rst/source/supplements/potential/grdflexure.rst
  doc/rst/source/supplements/potential/grdgravmag3d.rst
  doc/rst/source/supplements/potential/talwani2d.rst
  doc/rst/source/supplements/x2sys/x2sys_list.rst
Labels: documentation

#7794 Add admin script to explore failure distribution
  admin/examine-failure-log.sh
Labels: documentation, maintenance

#7796 Fix misc typos
  doc/rst/_extensions/youtube/utils.py
  doc/rst/source/devdocs/contributing.rst
  doc/rst/source/plot.rst
  doc/rst/source/tutorial_jl.rst
  src/gmt_api.c
  src/gmt_init.c
  src/gmt_io.c
  src/gmt_support.c
  src/grdtrack.c
  src/seis/sacio.h
Labels: documentation

#7798 Add admin script that determines which remote data sets are used
  admin/remote_data_use.sh
  admin/remote_files_used.sh
Labels: maintenance

#7802 Fi remote name for day image and spelling
  test/baseline/grdview.dvc
  test/grdview/texture2_classic.sh
  test/grdview/texture2_modern.sh
Labels: maintenance

#7778 Enhance meca and coupe w.r.t. adjusting positions and connecting with a line
  doc/rst/source/supplements/seis/coupe.rst
  doc/rst/source/supplements/seis/meca.rst
  doc/rst/source/supplements/seis/pscoupe.rst
  doc/rst/source/supplements/seis/psmeca.rst
  src/gmt_init.c
  src/seis/CMakeLists.txt
  src/seis/meca.h
  src/seis/pscoupe.c
  src/seis/psmeca.c
  src/seis/pspolar.c
  src/seis/seis_defaults.h
  src/seis/utilmeca.c
  src/seis/utilmeca.h
  test/baseline/seis.dvc
  test/seis/seis_12.sh
Labels: documentation, enhancement, add-changelog

#7789 Treat stroke symbols like other symbols
  doc/examples/images.dvc
  doc/rst/source/explain_symbols.rst_
  doc/rst/source/gmt.conf.rst
  doc/scripts/GMT_base_symbols1.sh
  doc/scripts/GMT_seamount_density.sh
  doc/scripts/images.dvc
  src/gmt_constants.h
  src/gmt_defaults.h
  src/gmt_init.c
  src/gmt_keywords.txt
  src/gmt_support.c
  src/psxy.c
  src/psxyz.c
  test/baseline/filter1d.dvc
  test/baseline/grdgradient.dvc
  test/baseline/grdimage.dvc
  test/baseline/movie.dvc
  test/baseline/psbasemap.dvc
  test/baseline/psevents.dvc
  test/baseline/psxy.dvc
  test/baseline/psxyz.dvc
  test/filter1d/mfilter.sh
  test/grdvector/bothg.sh
  test/psbasemap/mapscales.sh
  test/psevents/event_lines.sh
  test/psxy/all_psxy_symbols.txt
  test/psxy/bezvec.sh
  test/psxy/decoratedlines.sh
  test/psxy/gallo.sh
  test/psxy/plot_symbols.sh
  test/psxy/vector2d_mods.sh
  test/psxyz/plot_symbols.sh
  test/psxyz/vector3d_mods.sh
Labels: documentation, enhancement, add-changelog

#7807 Use Latex math for log10 and log2 in docs
  doc/rst/source/colorbar.rst
  doc/rst/source/devdocs/long_options.rst
  doc/rst/source/explain_-J.rst_
  doc/rst/source/explain_-icols_full.rst_
  doc/rst/source/explain_array.rst_
  doc/rst/source/gmt.rst
  doc/rst/source/gmtmath.rst
  doc/rst/source/grd2cpt.rst
  doc/rst/source/grdmath.rst
  doc/rst/source/histogram.rst
  doc/rst/source/makecpt.rst
  doc/rst/source/reference/coordinate-transformations.rst
Labels: documentation

#7803 Fix the three scripts that were labelled KNOW_FAILURE
  test/grdvector/bothg.sh
  test/psxy/outline.sh
Labels: maintenance

#7810 Update WL_example_3.sh to use NETCDF driver
  test/gmtmex/WL_example_3.sh
Labels: maintenance

#7816 Fix lack of abs() in scale_down parameter in psscale
  doc/scripts/images.dvc
  src/psscale.c
Labels: bug

#7821 Fix dumb bug in -x parser
  src/gmt_init.c
Labels: bug

#7822 Use MAP_SYMBOL_PEN_SCALE instead of MAP_STROKE_WIDTH
  doc/rst/source/explain_symbols.rst_
  doc/rst/source/gmt.conf.rst
  src/gmt_defaults.h
  src/gmt_init.c
  src/gmt_keywords.txt
  src/psxy.c
  src/psxyz.c
Labels: documentation

#7826 Update 9 PS originals
  doc/scripts/images.dvc
  test/baseline/gmtmex.dvc
  test/baseline/potential.dvc
  test/baseline/psscale.dvc
Labels: maintenance

#7831 Default to color bars with gaps for categorical CPTs
  doc/rst/source/colorbar.rst
  src/psscale.c
  test/baseline/psscale.dvc
Labels: enhancement, add-changelog

#7827 Allow grdimage to process byte images without indexed colors, via CPT
  doc/rst/source/grdimage.rst
  src/grdimage.c
  src/psscale.c
Labels: enhancement

#7840 Fix gmt info's longitude-range output
  doc/rst/source/gmt.conf.rst
  src/gmtinfo.c
Labels: bug

#7841 Clean up Appendix M CPTs
  doc/rst/source/reference/cpts.rst
  doc/scripts/GMT_App_M_1a.sh
  doc/scripts/GMT_App_M_1b.sh
  doc/scripts/GMT_App_M_1c.sh
  doc/scripts/GMT_App_M_1d.sh
  doc/scripts/GMT_App_M_1e.sh
  doc/scripts/images.dvc
  share/cpt/gmt/rust2silver.cpt
  src/gmt_cpt_masters.h
Labels: documentation

#7808 Windbarbs supplement
  doc/rst/source/modules-classic.rst
  doc/rst/source/modules.rst
  doc/rst/source/plot.rst
  doc/rst/source/psxy.rst
  doc/rst/source/supplements/module_supplements_purpose.rst_
  doc/rst/source/supplements/windbarbs/barb.rst
  doc/rst/source/supplements/windbarbs/explain_windbarbs.rst_
  doc/rst/source/supplements/windbarbs/grdbarb.rst
  doc/rst/source/supplements/windbarbs/psbarb.rst
  src/CMakeLists.txt
  src/gmt_modern.c
  src/gmt_modern.h
  src/longopt/grdbarb_inc.h
  src/longopt/psbarb_inc.h
  src/psxy.c
  src/windbarbs/CMakeLists.txt
  src/windbarbs/README.windbarb
  src/windbarbs/grdbarb.c
  src/windbarbs/psbarb.c
  src/windbarbs/test/grdbarb_example.sh
  src/windbarbs/test/psbarb_example.sh
  src/windbarbs/windbarb.c
  src/windbarbs/windbarb.h
  test/baseline/.gitignore
  test/baseline/windbarbs.dvc
  test/windbarbs/grdbarb_01.sh
  test/windbarbs/grdbarb_02.sh
  test/windbarbs/psbarb_01.sh
  test/windbarbs/psbarb_02.sh
Labels: documentation, add-changelog, new module, supplement update
