Repository GenericMappingTools/gmt, pull requests merged in 2023-06, with the labels that each got.

#7489 Report dimensions of transposed data via -V
  doc/rst/source/gmtconvert.rst
  src/gmtconvert.c
Labels: documentation

#7488 Add -Fe for step-up sampling in sample1d
  doc/rst/source/sample1d.rst
  src/gmt_constants.h
  src/gmt_support.c
  src/sample1d.c
Labels: new feature

#7491 Update sample1d.rst
  doc/rst/source/sample1d.rst
Labels: documentation

#7492 Let -bof not be caught up in graphics format check
  src/gmt_api.c
Labels: bug

#7493 Clarify how many ASCII columns we can read
  doc/rst/source/cookbook/file-formats.rst
Labels: documentation

#7497 Fix new error in -R<dcw>+modifier parsing
  src/gmt_init.c
Labels: bug

#7500 Update grdmath.rst table of operators
  doc/rst/source/grdmath.rst
Labels: documentation

#7505 Improve math formatting for IGF in mgd77list do
  doc/rst/source/supplements/mgd77/mgd77list.rst
Labels: documentation

#7514 Just use consistent italics for grid format
  doc/rst/source/grdgradient.rst
Labels: documentation

#7513 Spell out directives nd modifiers for -S in synopisis and docs
  doc/rst/source/grdtrack.rst
  src/grdtrack.c
Labels: documentation

#7515 Spell out the modifiers for grdfilter -F in synopsis
  doc/rst/source/grdfilter.rst
  src/grdfilter.c
Labels: documentation

#7516 Use the propose +du in the default projection
  src/gmt_init.c
Labels: maintenance

#7517 histogram documentation minor improvements
  doc/rst/source/histogram.rst
Labels: documentation

#7524 gmtmath_table_identation
  doc/rst/source/gmtmath.rst
Labels: documentation

#7543 Improve parsing of -l for legend labels with font changes
  src/gmt_init.c
  test/baseline/pslegend.dvc
  test/pslegend/fontswitch.sh
Labels: bug

#7549 Fix regression that movie scripts could not use -Xc|f -Yc|f
  src/gmt_init.c
Labels: bug

#7552 Forgot to add -E+n to the list-making modifiers
  src/pscoast.c
Labels: bug

#7557 Do no free external trailing text strings
  src/gmt_api.c
  src/gmt_hidden.h
  src/gmt_io.c
Labels: bug

#7563 Update grdmath.rst
  doc/rst/source/grdmath.rst
Labels: documentation

#7566 Check for date later
  src/gmt.c
Labels: bug

#7568 Remove empty first row
  doc/rst/source/cookbook/features.rst
  doc/rst/source/cookbook/map-projections.rst
Labels: documentation

#7576 Improved detection of relative time ending in t
  src/gmt_io.c
Labels: bug

#7583 Exclude any trailing CR when reading DCW names
  src/gmt_dcw.c
Labels: enhancement

#7584 Update explain_-J.rst_
  doc/rst/source/explain_-J.rst_
Labels: documentation
