Repository GenericMappingTools/gmt, pull requests merged in 2023-01, with the labels that each got.

#7188 Let grid array memory be of even length
  src/gmt_api.c
  src/gmt_grdio.c
Labels: maintenance

#7189 Not use vDSP basics for >32-bit array lengths
  src/gmt_grdio.h
Labels: bug, maintenance

#7192 Smarter area weight grid saves memory in grdfilter
  src/gmt_private.h
  src/gmt_support.c
  src/grdfilter.c
Labels: maintenance

#7190 Fix some memory leaks in surface
  src/surface.c
Labels: bug, maintenance

#7194 surface -r changed the pad twice
  src/surface.c
Labels: bug

#7195 Fix grdmath EXTREME operator by adding operator SADDLE
  doc/rst/source/grdmath.rst
  src/grdmath.c
  test/grdmath/ops.sh
Labels: bug

#7196 Be clear on directive versus modifier
  doc/rst/source/explain_-B.rst_
  doc/rst/source/explain_-U.rst_
  doc/rst/source/explain_-XY.rst_
Labels: documentation

#7197 RPN documentation improvements
  doc/fig/RPN_fig.jpg
  doc/rst/source/RPN_info.rst_
  doc/rst/source/gmtmath.rst
  doc/rst/source/grdmath.rst
Labels: documentation

#7199 Let GMT determine position for text in example 33
  doc/examples/ex33/ex33.bat
  doc/examples/ex33/ex33.sh
Labels: maintenance

#7198 Clean up docs for grdtrack
  doc/rst/source/grdtrack.rst
  doc/rst/source/module_core_purpose.rst_
  src/grdtrack.c
Labels: documentation, maintenance

#7209 Create RPN_MoreOn.rst_
  doc/rst/source/RPN_MoreOn.rst_
  doc/rst/source/gmtmath.rst
  doc/rst/source/grdmath.rst
Labels: documentation

#7212 Changed link of online reStructuredText editor to a working one
  doc/rst/source/devdocs/rst-cheatsheet.rst
Labels: bug, documentation

#7214 Simplify inline function scale_and_offset_f
  src/gmt_grdio.h
Labels: bug

#7215 Allow format flags F and G in FORMAT_GEO_MAP to come first or last
  doc/rst/source/gmt.conf.rst
  src/gmt_init.c
  src/gmt_io.c
  src/gmt_io.h
  src/gmt_support.c
Labels: enhancement

#7218 Ensure we compute 64-bit index in grdfilter
  src/grdfilter.c
Labels: maintenance
