Repository GenericMappingTools/gmt, pull requests merged in 2024-04, with the labels that each got.

#8427 CI: Fix the docker workflow
  .github/workflows/docker.yml
Labels: maintenance

#8429 Add support for loongarch
  src/gmt_common_sighandler.c
Labels: maintenance

#8432 Fix the test/psevents/event_lines.sh on Windows
  test/psevents/event_lines.sh
Labels: maintenance

#8426 CI: Fix the ci-caches workflow and always use the "static" data server in CI
  .github/workflows/build.yml
  .github/workflows/ci-caches.yml
  .github/workflows/docker.yml
  .github/workflows/docs.yml
  .github/workflows/tests.yml
  ci/config-gmt-unix.sh
  ci/config-gmt-windows.sh
Labels: maintenance

#8445 CI: Run workflows based on changed files to save CI resources
  .github/workflows/build.yml
  .github/workflows/check-links.yml
  .github/workflows/code-validator.yml
  .github/workflows/docker.yml
  .github/workflows/docs.yml
  .github/workflows/lint-checker.yml
  .github/workflows/remind.yml
  .github/workflows/scm-check.yml
  .github/workflows/tests.yml
Labels: maintenance

#8447 Update movie.rst. Fix typo
  doc/rst/source/movie.rst
Labels: documentation

#8461 GMT_Call_Module: Fix the debugging message when a list of argument strings is passed
  src/gmt_api.c
Labels: bug

#8463 CI: Need to setup miniconda for macOS-14
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/tests.yml
Labels: maintenance
