Repository GenericMappingTools/gmt, pull requests merged in 2024-05, with the labels that each got.

#8470 Upgrade anim01
  doc/examples/anim01/anim01.sh
  doc/rst/source/animations/anim01.rst
Labels: documentation, enhancement

#8450 CI: Use 'gh run download' to download GMT caches
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/tests.yml
Labels: maintenance

#8484 doc: Redesign the gallery pages
  doc/rst/_static/style.css
  doc/rst/source/animations.rst
  doc/rst/source/gallery.rst
  doc/rst/source/users-contrib-symbols.rst
Labels: documentation

#8491 doc: Fix the order for sections included in the documentation
  doc/rst/source/index.rst
Labels: need-review

#8492 Fix typo in the comments of GMT_Cap.sh
  doc/scripts/GMT_cap.sh
Labels: documentation

#8499 Typo. Remove extra )
  doc/rst/source/reference/features.rst
Labels: documentation

#8501 cmake: Set GMT_BUILD_DATE to the current date or the last commit date
  cmake/modules/ConfigCMake.cmake
Labels: bug

#8481 CI: Cache GSHHG and DCW data as artifacts to simplify workflows
  .github/workflows/build.yml
  .github/workflows/ci-caches.yml
  .github/workflows/docker.yml
  .github/workflows/docs.yml
  .github/workflows/tests.yml
Labels: maintenance
