Repository GenericMappingTools/gmt, pull requests merged in 2024-01, with the labels that each got.

#8251 Final version of updates for 6.5: grdimage, colorbar, grdmix
  src/gmt_hidden.h
  src/gmt_plot.c
  src/gmt_prototypes.h
  src/grdimage.c
  src/grdmix.c
  src/postscriptlight.c
  src/postscriptlight.h
  src/psscale.c
  test/baseline/grdimage.dvc
  test/baseline/grdmix.dvc
  test/baseline/psscale.dvc
  test/grdimage/grdimage_Q_effects.sh
  test/grdimage/grid_transp.sh
  test/grdimage/image_vartrans.sh
  test/grdimage/transp_mix.sh
  test/psscale/interval-panel.sh
Labels: enhancement

#8257 Remove deprecated xy from grdimage's THIS_MODULE_OPTIONS and other fixes
  doc/rst/source/explain_core_full.rst_
  src/gmt_init.c
  src/gmt_parse.c
  src/gmt_synopsis.h
  src/grdimage.c
  test/grdfilter/spikes.sh
  test/grdfilter/threads.sh
Labels: bug, documentation

#8038 Getting ready for 6.5 release
  CITATION.cff
  cmake/ConfigDefault.cmake
  doc/rst/_static/version_switch.js
  doc/rst/source/install.rst
Labels: priority

#8259 When given multiple tables, report line number of bad records in the offending file
  src/gmt_io.c
Labels: bug

#8261 Ensure allocated path is long enough for pssolar
  src/gmt_plot.c
Labels: bug

#8263 Reset CMakeDefaults.cmake for the next 6.6.0 release
  cmake/ConfigDefault.cmake
Labels: maintenance

#8264 Update the release checklist based on the experience for releasing GMT 6.5.0
  .github/ISSUE_TEMPLATE/release_checklist.md
Labels: maintenance

#8267 Update the draft release workflow to include the win64 portable installer
  .github/workflows/draft-release.yml
Labels: maintenance

#8237 CI: Test building GMT on Ubuntu 23.10 and Fedora 39
  .github/workflows/docker.yml
Labels: maintenance

#8286 Relax the need for -R in grdproject
  src/gmt_support.c
  src/grdproject.c
Labels: deprecation

#8287 colorbar: Add modifier +n|N to -D option for placing colorbar NaN box on the right and to skip label
  doc/rst/source/colorbar.rst
  src/psscale.c
  test/baseline/psscale.dvc
  test/psscale/colorbar-nans-h.sh
  test/psscale/colorbar-nans-v.sh
Labels: documentation, enhancement, add-changelog

#8288 Maintenance PR only for better function name
  src/dimfilter.c
  src/filter1d.c
  src/gmt_prototypes.h
  src/gmt_support.c
  src/grd2kml.c
  src/grdcontour.c
  src/grdhisteq.c
  src/grdview.c
  src/gshhg/gshhg.c
  src/img/img2grd.c
  src/movie.c
  src/psconvert.c
  src/segy/pssegyz.c
  src/segy/segy2grd.c
Labels: maintenance

#8285 Update module names in docs
  doc/rst/source/gmtbinstats.rst
  doc/rst/source/gmtconnect.rst
  doc/rst/source/gmtconvert.rst
  doc/rst/source/gmtdefaults.rst
  doc/rst/source/gmtget.rst
  doc/rst/source/gmtinfo.rst
  doc/rst/source/gmtlogo.rst
  doc/rst/source/gmtmath.rst
  doc/rst/source/gmtregress.rst
  doc/rst/source/gmtselect.rst
  doc/rst/source/gmtset.rst
  doc/rst/source/gmtsimplify.rst
  doc/rst/source/gmtspatial.rst
  doc/rst/source/gmtsplit.rst
  doc/rst/source/gmtvector.rst
  doc/rst/source/gmtwhich.rst
  doc/rst/source/modules-classic.rst
  doc/rst/source/modules.rst
  doc/rst/source/supplements/potential/gmtflexure.rst
  doc/rst/source/supplements/potential/gmtgravmag3d.rst
  doc/rst/source/supplements/spotter/gmtpmodeler.rst
Labels: discussion, documentation, enhancement

#8289 CI: Bump ghostscript from 10.02.0 to 10.02.1
  ci/install-dependencies-linux.sh
  ci/install-dependencies-macos.sh
  ci/install-dependencies-windows.sh
Labels: maintenance

#8293 doc: Improve the documentation of gmtwhich
  doc/rst/source/gmtwhich.rst
Labels: documentation

#8297 Require movie canvas dimensions in integer pixels when using modifiers +c|i
  doc/rst/source/movie.rst
  src/movie.c
Labels: enhancement

#8302 Remove deprecated doc and usage language from grdview
  doc/rst/source/grdview.rst
  src/grdview.c
Labels: documentation, maintenance

#8304 coast: Clarify the default resolutions in classic and modern modes
  src/gmt_init.c
  src/grdlandmask.c
  src/pscoast.c
Labels: documentation

#8305 Hide legend -C but leave it under the hood
  doc/rst/source/explain_-F_box.rst_
  doc/rst/source/legend.rst
  src/pslegend.c
Labels: deprecation

#8311 Forgot to edit a temporary shorter length for debugging data types
  src/gmt_io.c
Labels: bug

#8316 Let grdmix create a RGB image for red, green, blue grids in 0-255 range
  doc/rst/source/grdmix.rst
  src/grdmix.c
Labels: enhancement, add-changelog

#8314 Improve windbarb docs, synopsis and usage for -Q and parsing of -Q
  doc/rst/source/supplements/windbarbs/barb.rst
  doc/rst/source/supplements/windbarbs/explain_windbarbs.rst_
  doc/rst/source/supplements/windbarbs/grdbarb.rst
  src/windbarbs/grdbarb.c
  src/windbarbs/psbarb.c
  src/windbarbs/windbarb.c
  src/windbarbs/windbarb.h
Labels: documentation, maintenance

#8318 Dateline crossing dcw polygons and tiles
  src/gmt_dcw.c
  test/baseline/grdimage.dvc
  test/grdimage/dcw-180-crossers.sh
Labels: bug

#8327 Fix bad movie -A parsing
  src/movie.c
Labels: bug

#8337 Fix URL
  doc/rst/source/supplements/mgd77/mgd77convert.rst
  doc/rst/source/supplements/mgd77/mgd77header.rst
  doc/rst/source/supplements/mgd77/mgd77info.rst
  doc/rst/source/supplements/mgd77/mgd77list.rst
  doc/rst/source/supplements/mgd77/mgd77manage.rst
  doc/rst/source/supplements/mgd77/mgd77path.rst
  doc/rst/source/supplements/mgd77/mgd77sniffer.rst
  doc/rst/source/supplements/mgd77/mgd77track.rst
Labels: documentation
