Repository GenericMappingTools/gmt, pull requests merged in 2024-10, with the labels that each got.

#8598 anim07.sh. Data registration (_g vs _p).
  doc/examples/anim07/anim07.sh
  doc/examples/anim08/anim08.sh
  doc/examples/anim11/anim11.sh
Labels: documentation

#8601 CI: Should not set GMT_USE_THREADS if optional package are not installed
  ci/config-gmt-unix.sh
Labels: maintenance

#8600 GMT_Put_Vector: Fix a bug when passing longitude/latitude strings
  src/gmt_api.c
Labels: bug

#8602 Upgrade anim06 to use lables (movie -L)
  doc/examples/anim06/anim06.sh
Labels: documentation
