Repository GenericMappingTools/gmt, pull requests merged in 2025-01, with the labels that each got.

#8611 Fix events for infinite symbols
  src/psevents.c
  test/psevents/events.sh
Labels: bug

#8659 Replace deprecated CURLINFO_CONTENT_LENGTH_DOWNLOAD
  src/CMakeLists.txt
  src/gmt_remote.c
Labels: maintenance

#8666 CI: Remove some Debian/Fedora versions to save CI resources
  .github/workflows/docker.yml
Labels: maintenance

#8665 Slightly increase the RMS value for test/grdvector/shrink.sh
  test/grdvector/shrink.sh
Labels: maintenance

#8668 Fix GMT_App_M_1?.sh so it passes test
  doc/scripts/GMT_App_M_1a.sh
  doc/scripts/GMT_App_M_1b.sh
  doc/scripts/GMT_App_M_1c.sh
  doc/scripts/GMT_App_M_1d.sh
Labels: bug

#8667 grdsample: Fix the incorrect handling of -Am and -Ap
  src/gmt_vector.c
  test/baseline/sample1d.dvc
Labels: bug

#8664 Slightly increase the RMS value for test/grdinterpolate/slices.sh
  test/grdinterpolate/slices.sh
Labels: maintenance

#8672 Update info about remote data set
  doc/rst/source/reference/features.rst
Labels: documentation
