Repository GenericMappingTools/gmt, pull requests merged in 2025-04, with the labels that each got.

#8711 Fix auto-legend for custom symbols
  src/gmt_init.c
Labels: bug

#8713 Add headings to symbols
  doc/rst/source/explain_symbols.rst_
Labels: documentation

#8702 DOCS: Update solar
  doc/examples/ex46/ex46.bat
  doc/examples/ex46/ex46.sh
  doc/rst/source/gallery/ex46.rst
  doc/rst/source/module_core_purpose.rst_
  doc/rst/source/solar.rst
Labels: documentation

#8716 sphdistance: Remove unused -A flag from source codes
  src/sphdistance.c
Labels: maintenance
